### ISSUE TITLE
Block: structure generator not working

### ISSUE THREAD

**Issue by Zarzuf** [Ivorforce/RecurrentComplex#1]
The structure generator block seem to be unable to spawn the selected structure when activated.
If I use ther /strucGen commend the structure spawns normally.
Sorry for not providing more context, but there is no crash log (since minecraft doesn't crash), nor error logs that i can post.
Everithing else seems to work normally... it's just the structure generator block that does nothing.

**Comment by Ivorforce** [comment]
For a lack of present information, I'll just close this.
