### ISSUE TITLE
Lightweight Mode Prevents Loot from Spawning

### ISSUE THREAD

**Issue by oitsjustjose** [Ivorforce/RecurrentComplex#102]
Well, mostly, see the title.

On Recurrent Complex  v. 1.2.1 on forge 2094, if the lightweight mode is enabled, none of the chests spawn with loot. I can confirm that as soon as I re-enabled this and loaded new structures, loot began spawning properly again :)

**Comment by 4rz0** [comment]
I can confirm that.
