### ISSUE TITLE
[1.7.10]Failed to fix item tag from structure with ID 'reccomplex:inventoryGenerationTag'

### ISSUE THREAD

**Issue by Managarmr719** [Ivorforce/RecurrentComplex#103]
Spams the server console with error "[Server thread/WARN] [ivtoolkit/]: Failed to fix item tag from structure with ID 'reccomplex:inventoryGenerationTag'" when the mod is in lightweight mode.

RecurrentComplex: 0.9.7.1
IvToolkit: 1.2.1

Server log:
https://gist.githubusercontent.com/Managarmr719/1dd2839b2cb815305da3c9804ffb8835/raw/8bb70296cac706fbd29366bfd123c862800e9a27/gistfile1.txt

**Comment by Ivorforce** [comment]
Are you in lightweight mode?

**Comment by Managarmr719** [comment]
Yes.

**Comment by Ivorforce** [comment]
I know the issue - I had fixed it already for 1.10. 
However, I can't get my 1.7 branch started up currently due to gradle issues. I'll try to fix it later.
