### ISSUE TITLE
Crash - 1.10.2 Latest on Hide GUI

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Ivorforce/RecurrentComplex#107]
Client Crashlog
https://gist.github.com/P3rf3ctXZer0/f7a037f80b18075cc90ef75940a6fac4

Full Log
https://gist.github.com/P3rf3ctXZer0/f76e8172f970ae3b9dd6c2d7dba3715f

Release Log
https://github.com/P3rf3ctXZer0/DeathPlagueGaming/releases/tag/r1.3.1

**Comment by Ivorforce** [comment]
I'd suggest not entering lightweight mode if you want to actually edit structures or use GUI. It's intended for servers only.

**Comment by P3rf3ctXZer0** [comment]
No worries I just disabled trees.
