### ISSUE TITLE
Issue - Cannot place copied structure.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Ivorforce/RecurrentComplex#108]
https://github.com/P3rf3ctXZer0/DeathPlagueGaming/releases/tag/r1.3.1

Unable to confirm copy paste
![2016-10-25_16 31 10](https://cloud.githubusercontent.com/assets/10351221/19705154/92c869ec-9ad0-11e6-9564-75d623c3f468.png)

Possible Cause
https://gist.github.com/P3rf3ctXZer0/bed21d5e071b4a3f4e58b7614705918b

**Comment by Thutmose** [comment]
I will get this fixed on my end.

**Comment by Thutmose** [comment]
it seems that StructureGenerationEventLite.getStructureName() is returning null? maybe it should return "pasted" or something in this case?

I will add a null check anyway on my side though.

**Comment by Ivorforce** [comment]
I was quicker :P

**Comment by P3rf3ctXZer0** [comment]
ty
