### ISSUE TITLE
Error loading resources from directory

### ISSUE THREAD

**Issue by C0rn3j** [Ivorforce/RecurrentComplex#109]
Forge version 2114

Modlist: http://pastebin.com/7qmWzWF8

[23:57:52] [Server thread/ERROR] [reccomplex]: Error loading resources from directory
java.nio.file.NoSuchFileException: ./cornlandiaReborn/structures/genericStructures

Starting the server produces a lot of errors that start like this.

**Comment by b0bst3r** [comment]
Looking for Craft Guide it seems which isnt' 1.1.0

http://pastebin.ubuntu.com/23388113/  Line 2326
