### ISSUE TITLE
Overlapping structures

### ISSUE THREAD

**Issue by piotrb** [Ivorforce/RecurrentComplex#11]
Had a weird world gen happen, ended up with 2 structures on top of eachother.

This was running on the RR3 pack with most things on, and using Realistic World Gen world type.
(not sure if the worldgen has anything to do with it per say tho)

![2015-03-03_22 48 24](https://cloud.githubusercontent.com/assets/13251/6479369/18c88700-c1f9-11e4-909a-e45c58953127.png)

**Comment by Ivorforce** [comment]
Thanks for reporting. While very rare, this was bound to happen in 0.9.5 and earlier. This is actively being prevented with 4b66fc0ca9029301833dafb8e0b6b3d0edee9b4c - or in other words, the 0.9.5.1 release :)
