### ISSUE TITLE
[1.7.10] Crash when trying to edit a custom item generator

### ISSUE THREAD

**Issue by Sunconure11** [Ivorforce/RecurrentComplex#112]
http://pastebin.com/V4mCETFj

**Comment by Ivorforce** [comment]
Are you in lightweight mode? Because you should never edit stuff in lightweight mode.

**Comment by Sunconure11** [comment]
I already solved this issue, it turns out that when you remove a mod that has an item in an item generator, the associated generator will crash. Would it be possible to add an option on all versions to automatically remove non-existent items from generators?

**Comment by Ivorforce** [comment]
That's already in 1.10+ (iirc - if not I'll add it later). I won't do it for 1.7-, but you can fairly easily manually remove the item before saving.
