### ISSUE TITLE
Mod seems to remove vanilla forest generation:

### ISSUE THREAD

**Issue by Compegen** [Ivorforce/RecurrentComplex#113]
I've been using the 1.10.2 version for the last 4 updates, and since this last patch, I've begun to notice the generation in my world has stopped working. Upon further investigation it appears that [vanilla trees no longer seem to generate if lightweight mode is on](https://sli.mg/a/lUVeDY).

**Comment by Ivorforce** [comment]
Fixed in 077dc8b0adbc12183eb007ad5f972208e79d09da.
