### ISSUE TITLE
[1.10.2] Poor Performance with world gen.

### ISSUE THREAD

**Issue by JAWSAWN** [Ivorforce/RecurrentComplex#114]
I've tested it with only RC on 1.10.2. I love how it adds trees and makes the terrain teeming with life. but every time I load new chunks and break blocks, they don't properly drop. Not FPS lag, having some block and chat lag. 

I don't remember any of those on 1.7 version. What happened? IS there ways to have better performance? Are you guys working on it?

3,5G given to mc.

**Comment by Ivorforce** [comment]
Try using the profiler to see what's causing the lag. 
Either the world generator is still running - in that case you can just sit back and wait a bit for it to complete. 
It might also be that you have lots of decaying leaves - a lot of people prefer to change the config option treeLeavesDecay to false. This will of course only work on new worlds.

**Comment by Castone22** [comment]
http://pastebin.com/zw16fqek
http://pastebin.com/KeGHnYFZ

I believe i might be having the same issue here. 

Seems to be related to tree growth?

**Comment by Ivorforce** [comment]
Try the latest nightly - the problem should either be gone or greatly reduced.

**Comment by Castone22** [comment]
Will do as soon as I'm in a spot I can.

**Comment by JAWSAWN** [comment]
@Ivorforce tried the 1.10.2 1.2.4 version, still bad. It might be worse in performance and broken blocks not popping up. Also are you going to support 1.10.2, halted support or it magicaly supports 1.10 from 1.11 versions with that mcjts mod?

**Comment by Ivorforce** [comment]
The changes were made purely in the 1.11 nightly builds. A release will be available soon, but not for 1.10.

**Comment by JAWSAWN** [comment]
but its too early to remove support from 1.10.2
 :L

**Comment by Ivorforce** [comment]
1.11 is not a very big update. It shouldn't be hard to update to it from 1.10.

**Comment by Castone22** [comment]
Only problem is I have to convince the other 30 or so devs making mods for my pack of the same thing.

**Comment by Ivorforce** [comment]
Are there that many mods not being updated yet? I'm honestly surprised. Looking across curse I don't see many out of date myself.

**Comment by Baughn** [comment]
Let's see. It's not quite 30 mods, I don't think, but I have some automation for this... https://github.com/TPPIC/Test-Factory-Please-Ignore/blob/1.11/MODS.md

(Ignore the "1.10" line, the code writing MODS.md has no idea that I asked for 1.11 versions this time around.)

So that's... 56 mods.

Right. Welp. It's not 30.

**Comment by Ivorforce** [comment]
I'll close this for now as the issue itself should be resolved. A backport of this feature is a different question to be discussed in a new issue.
