### ISSUE TITLE
[1.2.3.4] Using /#export on a server causes you to be kicked

### ISSUE THREAD

**Issue by belathus** [Ivorforce/RecurrentComplex#115]
This shows up in the console right after using the export command: http://pastebin.com/w8rYT267

**Comment by Ivorforce** [comment]
Can you send the full log of that session?

**Comment by belathus** [comment]
I can send it over in about 10 hours.

**Comment by belathus** [comment]
My apologies. I admit I forgot to send that log over. Here is a new one that should show similar: http://paste.ee/p/QJNDX

**Comment by Saereth** [comment]
Is there a new build out with this fix? We've got dozens of recurrent to export and no ability to presently :(
Do you have a jenkins somewhere? Dont mind if it's not a completely stable release.

**Comment by Ivorforce** [comment]
You can use the [nightly builds](https://drone.io/github.com/Ivorforce/RecurrentComplex/latest).

**Comment by Saereth** [comment]
perfect, ty!
