### ISSUE TITLE
[RecComplex 1.2.3.4] Lightweight Mode Disabling Chest Loot (again)

### ISSUE THREAD

**Issue by oitsjustjose** [Ivorforce/RecurrentComplex#116]
Sorry to bug you about this again! Looks like lightweight mode breaks Dungeon Loot again :(

Using:
Forge 12.18.2.2121
Recurrent Complex 1.2.3.4

**Comment by Ivorforce** [comment]
I just tested it - I don't have that issue.
Can you send me the logs of a session where you generate some loot?

**Comment by oitsjustjose** [comment]
Sorry - been swamped with college, I completely forgot.

[Here's the log](http://paste.ee/p/uTZWz), is it possible that I need to delete some pre-existing files of RecComplex's? It looks like the CME is causing my error, it shows up twice at the very bottom (sorry for the long log, hard to show since I don't actually crash) which is at the same time that I had opened a chest from RecComplex.

**Comment by oitsjustjose** [comment]
Tried it out on a new world; no issues there. Guess maybe I came across generation that occurred while the bug was still in place...? Not sure. Sorry to waste your time!

**Comment by oitsjustjose** [comment]
Haha just kidding - village generation came up empty in the watch tower in this brand new world.. sorry again D:

**Comment by Ivorforce** [comment]
Maybe just the tower loot is broken then. I'll check.

**Comment by oitsjustjose** [comment]
I'd check all of the village loot, it seemed like all of the village components that RecComplex adds is having difficulties with loot in lightweight mode.

**Comment by oitsjustjose** [comment]
(Sorry, I'd help more by adding a PR, but I haven't added structures to world gen since I was responsible for Mystic Ruins in Minecraft 1.4.7)

**Comment by Ivorforce** [comment]
Fixed in 2ac3e8c05f8bceb916ba2174aad06e9e71ccf69b.
