### ISSUE TITLE
Can't figure out how to blacklist a dimension

### ISSUE THREAD

**Issue by aridhol** [Ivorforce/RecurrentComplex#119]
I don't know if its a bug or if its me - but I cannot for the life of me figure how to blacklist a dimension entirely.

I've tried !id=**#**  and just !**#** but it is not working... Anyone able to help me with this real quick?

**Comment by Ivorforce** [comment]
The expression you're looking for is

`   !0 `

At least, if you want to disable dimension 0. There should be plenty of examples on the wiki.
