### ISSUE TITLE
Strange broken world gen of structures .. 

### ISSUE THREAD

**Issue by piotrb** [Ivorforce/RecurrentComplex#12]
Not sure if this is by design to have the structures partially damaged or what .. but I've ran into this particular castle a few times extremely damaged, seemingly missing whole walls .. 

This just looks off and you end up with a lot of items on the ground (I see the contents of chests dumped out, stuff that should be on walls (like ladders), etc, lots of clutter on the ground.

![2015-03-03_22 55 46](https://cloud.githubusercontent.com/assets/13251/6479381/4db943d2-c1f9-11e4-89af-727bc1613910.png)

**Comment by Ivorforce** [comment]
Yes, this is intentional - it's a special block transformer called 'ruins'. It looks a bit better in the nightlies, and I do plan on improving it further in the future too.
This castle is currently the only build I have applied the transformer to, though.

**Comment by piotrb** [comment]
Different castle .. even more broken .. I havn't see even a mostly whole one yet .. 

(all images are different angles of the same)

![2015-03-03_23 06 27](https://cloud.githubusercontent.com/assets/13251/6479438/1edf3a70-c1fa-11e4-91dc-bc05492e74fb.png)
![2015-03-03_23 06 37](https://cloud.githubusercontent.com/assets/13251/6479439/1edfd516-c1fa-11e4-8b2b-8c5e485388a3.png)
![2015-03-03_23 06 42](https://cloud.githubusercontent.com/assets/13251/6479441/1ee0f964-c1fa-11e4-894a-4730ef3c6ad7.png)
![2015-03-03_23 06 49](https://cloud.githubusercontent.com/assets/13251/6479440/1edfdebc-c1fa-11e4-9e19-80744e046ba0.png)

**Comment by piotrb** [comment]
Cool, as long as its something that you are keeping an eye on .. maybe I'm just overly picky about seeing a tonne of stuff strewn on the ground .. perhaps have the ruins code clean up loose entities on the ground soon after generation?

**Comment by Ivorforce** [comment]
Yeah, the stuff on the ground is a side effect of not being able to turn off block drops on the fly. I mean, it's only logical - a wall crumbles, and the ladders fall to the ground - but I realize that in MC, stuff on the ground feels kind of wrong. I'll try to address it in the future :)
