### ISSUE TITLE
Server-Side Crash; Concurrent Modification Exception 

### ISSUE THREAD

**Issue by oitsjustjose** [Ivorforce/RecurrentComplex#120]
[Here's the log](http://pastebin.com/DEkPYDXS)

So, it's a server-side crash, can't seem to narrow down which structure causes it though. I know that this log doesn't help much particularly (no actual references to Recurrent Complexes), but I haven't had this issue until adding it.

**Comment by Ivorforce** [comment]
Can you post the whole log?

**Comment by oitsjustjose** [comment]
Sure, [here you are](http://puu.sh/snoPZ/dd7d183b4a.log) - sorry for the puush link, it was too long for PasteBin. 

Never realized you outputted where you were generating structures; that's super useful!

**Comment by Ivorforce** [comment]
That's not the full log dude. There should be a crash at the end.
Try paste.ee or hastebin.com, maybe they'll take your log.

**Comment by oitsjustjose** [comment]
Nope, that's the whole thing. Just gonna close this issue; it's not fair to assume it's you when I can't find anything that proves it. If I find more info later that makes me believe that, I'll re-open this one.
