### ISSUE TITLE
ReC trees replacing non-air blocks.

### ISSUE THREAD

**Issue by xenoflot** [Ivorforce/RecurrentComplex#124]
Hi,

I've found that the current version of ReC is replacing non-air blocks during tree generation. The following pics were taken with only ReC, TheOneProbe and Journeymap in the pack.

http://i.imgur.com/cjzfGSo.png
http://i.imgur.com/7ZyoXzD.png

IvToolkit-1.2.9
recurrentcomplex-1.2.4

Cheers!

**Comment by Ivorforce** [comment]
Yeah, trees will cut through terrain on world gen currently to enhance performance a bit. I'm not certain yet if I will change that (though you can if you edit the tree transformer preset to ensure for air upon vanilla decoration generation as well).
