### ISSUE TITLE
User-made reccomplex trees not spawning in BOP biomes

### ISSUE THREAD

**Issue by TitusArmillius** [Ivorforce/RecurrentComplex#125]
[images](http://imgur.com/a/vPE1c)

Above is a link to two images, the stacks of trees is a vanilla roofed forest biome with the weight of a custom jungle tree I added set to 30.

surrounding are BOP biomes, which have no custom-made reccomplex trees (ensured correct biome expressions).

This bug occurs both using the RTG and BOP world types.

Side issue, when the weight of a tree type is dramatically increased tree stacking occurs as seen in the picture, this should not be occurring.

**Comment by Ivorforce** [comment]
This is a known issue and must be fixed on BoP's side.

See: https://github.com/Glitchfiend/BiomesOPlenty/issues/880
