### ISSUE TITLE
RC Crash: Could not initialize class ivorius.reccomplex.RCConfig

### ISSUE THREAD

**Issue by An-Sar** [Ivorforce/RecurrentComplex#126]
I am on MacOS, I was able to produce this crash in the vanilla launcher with a group of other mods, and in Multimc with only RC and IvToolkit installed.

Forge version is **13.19.1.2188**

_net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Recurrent Complex (reccomplex)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class ivorius.reccomplex.RCConfig
    at ivorius.reccomplex.RecurrentComplex.preInit(RecurrentComplex.java:111)_

Full Crash log: **http://pastebin.com/y8tcdtkd**

**Comment by An-Sar** [comment]
The crash occurs with forge versions later than 0.2172

**Comment by spoopyghostramses** [comment]
Also getting this crash with ONLY Recurrent Complex and IVToolKit loaded.

**Comment by Syndaryl** [comment]
[crash-2016-12-09_21.12.33-client.txt](https://github.com/Ivorforce/RecurrentComplex/files/643815/crash-2016-12-09_21.12.33-client.txt)
Same crash. This is a new installation of RC, so I didn't have a config file. Before it crashed it managed to create an (empty) config, and then kaput.

**Comment by Ivorforce** [comment]
Should be resolved in 3094c9eadc036920b3b12d0342c57a415e918029 / 1.2.5.1.
