### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by xJon** [Ivorforce/RecurrentComplex#13]
Hey!
First of all thank you for making such a fun mod.
I'm here because a weird problem with the spawning rates of the structres.
I'm using the defaults rates on my modpack, and I know I can low them, but my problem is that I see the same structures over and over again on a very small area, and I don't see a diversity of structres.
You can see that this has been reported and confirmed there: http://bit.ly/1ANrxDz
Playing with v0.9.5.
Thanks!

**Comment by Ivorforce** [comment]
Hey,
thanks for reporting! The issue has been reported to me already, and was fixed with 63ae3cc1e64b489782ca5c54f99992b7f957ee46 - or in other words, release 0.9.5.1. :)
