### ISSUE TITLE
Reccurent Complex Trees have sheared leaves in them

### ISSUE THREAD

**Issue by Peach774** [Ivorforce/RecurrentComplex#130]
When you go to cut down a recurrent complex tree that is either from world gen or from a sapling, some of the larger, puffier trees have sheared leaves in them which do not decay which leaves floating leaves in the air.

**Comment by Ivorforce** [comment]
Which ones are you referring to (/#whatisthis) ? Because I'm pretty sure with treeLeavesDecay enabled neither should have sheared ones in them.

**Comment by Peach774** [comment]
When planted, some of the trees that are generated, the giant ones, have leaves that do not decay

**Comment by Ivorforce** [comment]
Can you say which one? There are a lot of trees. Try using /#whatisthis inside the tree after activating the memorizeSaplings option in the config.
