### ISSUE TITLE
Crashing:  Could not initialize class ivorius.reccomplex.RCConfig

### ISSUE THREAD

**Issue by spoopyghostramses** [Ivorforce/RecurrentComplex#131]
Receiving a crash with Recurrent Complex. IVToolkit works fine alone.

This crash happens with/without other mods installed.

[crash-2016-12-13_09.46.03-client.txt](https://github.com/Ivorforce/RecurrentComplex/files/649195/crash-2016-12-13_09.46.03-client.txt)

**Comment by Ivorforce** [comment]
Should be resolved in 3094c9eadc036920b3b12d0342c57a415e918029 / 1.2.5.1.
