### ISSUE TITLE
1.11 JVM Crash

### ISSUE THREAD

**Issue by RViper80** [Ivorforce/RecurrentComplex#133]
I'm exploring the world on a dedicated server and the JVM crashes sometimes upon generating something from the mod.

JVM Stack traces:  
[Log 1](http://pastebin.com/XR3Rw04p)
[Log 2](http://pastebin.com/A63jV8u2)

The last lines in the server log files are:
> [11:43:48] [Server thread/TRACE] [reccomplex/]: Generated structure 'SpruceTree' in StructureBoundingBox{x0=-406, y0=80, z0=505, x1=-405, y1=81, z1=507}

and

> [12:06:49] [Server thread/TRACE] [reccomplex/]: Generated structure 'SpruceTree2' in StructureBoundingBox{x0=-196, y0=64, z0=557, x1=-191, y1=78, z1=564}

It's my guess that whatever did cause the crash didn't have a chance to be appended to the log though, if it's actually caused by a specific structure at all.

Forge 2188, Recurrent 1.2.5.1, IV 1.3

**Comment by Ivorforce** [comment]
JVM crashes are something I cannot control - it's a bug in the Java distribution. I can only recommend reporting it to Oracle.

**Comment by RViper80** [comment]
Hmm... ok.   I have turned off natural tree generation and it hasn't occurred since, so guess I keep the standard Minecraft trees.
