### ISSUE TITLE
[Suggestion]: Chisel N' Bits Support

### ISSUE THREAD

**Issue by Lanse505** [Ivorforce/RecurrentComplex#134]
I did a cursory check and couldn't find a post mentioning it so decided to post one here :P 

I'm working on a rather large scale project where we'd hopefully be using ReC has our Schematic System of Choice for storing and handling building schematics from our Build Server to our "implementation" server.

However at the current moment from cursory testing, it seems that CnB blocks simply get replaced by Air when storing them to a Schematic, which in some our "schematic" builds would end-up with large missing portions or just "air" schematics.

Would this be something you'd think about adding support for?
CnB is an amazing mod for builders to take advantage off and they would lend nicely to building ReC Schematics for spawning in-world.

//Best Regards 
Lanse505

**Comment by ChipWolf** [comment]
:+1:

**Comment by Ivorforce** [comment]
Closed since this cannot be fixed on my end.

**Comment by Ivorforce** [comment]
@Lanse505 Should work in the C&B test release + IvToolkit nightly + Recurrent Complex nightly.

**Comment by Ivorforce** [comment]
@Lanse505 Can you send me a log of a session where it doesn't work? If it's on ReC's end it should probably log an error somewhere.

**Comment by Lanse505** [comment]
Short Version:
https://gist.github.com/Lanse505/2103fa3d8097b97095b42ad0dfc7c4e0

Long Version:
https://gist.github.com/Lanse505/d3d11214466e0dca5082ad31893970f9

**Comment by Lanse505** [comment]
@Ivorforce any progress? or do you need more information?

**Comment by Ivorforce** [comment]
I'm not really sure... Seems to be on @AlgorithmX2's end. It tries to read it as minecraft:mod.chiselsandbits.tileentitychiseled, which seems like what it is registered as, or was at least. It worked when I tested it. Maybe he has more insight?

**Comment by AlgorithmX2** [comment]
Hmm, maybe its because the registration is "minecraft:mod.chiselsandbits.TileEntityChiseled" maybe its a case issue?

I didn't change it to lowercase cause nothing complained about it, and it still loads the old worlds fine.

**Comment by Ivorforce** [comment]
Hmm... It's an idea, but technically it should lowercase consistently on registration _and_ lookup. @Lanse505, can you check what exactly the ID of the C&B tile entity is in your world? (Maybe f3 shows it on mouse over, otherwise you need to check the world nbt or something)

**Comment by Ivorforce** [comment]
Ping @Lanse505 - you still here? :P

**Comment by Lanse505** [comment]
Yea x'D
Sorry been abit busy with a few project things.
I can confirm that the newest CnB and ReC builds works with CnB Schematics.
Only thing that is a bit wonky seems to be rotations.
But that's kinda to be expected.

**Comment by Ivorforce** [comment]
You can switch off rotations and mirror in the structure info, of course.

#235 for full support.

**Comment by Ivorforce** [comment]
Righty, so https://github.com/Ivorforce/IvToolkit/commit/766ad1a19b2c51f1793d9cab91be5b6e92593626 should enable mirror and rotation support with C&B (and anything else that has this implemented). I'd ask you to test it but it seems drone.io went offline. We'll have to hope it just works in the next release :P

**Comment by Lanse505** [comment]
@Ivorforce <3 You're amazing man xD <3
