### ISSUE TITLE
[issue] 1.2.6.2-1.10 tree generation is too wild! and replaces blocks

### ISSUE THREAD

**Issue by winsrp** [Ivorforce/RecurrentComplex#143]
when a big tree is generated and there are other structures or blocks on the way the tree will replace anything in its way (including the grass type!) for tree bark.

in BoP if you put dirt as ground on a volcano biome, it will also replace the dirt under it with ash!...

Very wild trees in deed!

**Comment by Ivorforce** [comment]
Is this on world generation or sapling generation? Because on the former they currently ignore surrounding terrain on generation for performance (although with the recent changes I might be able to re-enable the surround check, thinking about it)

**Comment by winsrp** [comment]
this is on sapling generation, we have them setup with progresive automation to chop the trees down and when the tree grows, it replaces ground, components, machines, walls and everything in its path..... wild trees in deed.

**Comment by Ivorforce** [comment]
By default, trees are set up (via their transformers) to check for existing blocks before generation. Have you modified the tree transformer preset?

**Comment by winsrp** [comment]
nope... set the mod, let it run and it went wild..... only now I had to check the config to actually turn big trees off as they are destroying everything!
