### ISSUE TITLE
Issue - 1.10.2 Forge 221 - No wand when typing /#wand

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Ivorforce/RecurrentComplex#144]
So basically back in the day if you typed /#wand you would get a wand instead now a days we get this instead.
![2017-01-18_16 49 21](https://cloud.githubusercontent.com/assets/10351221/22086463/69027f10-dd9e-11e6-8da2-95aa4976f834.png)

**Comment by Ivorforce** [comment]
Not sure what you are referring to. /#wand has always acted the way it does now - it mimicks the wand tool from 2D graphic programs in a 3D space.

**Comment by P3rf3ctXZer0** [comment]
Oh my bad. I am running on 72 hours awake.
