### ISSUE TITLE
Major Bug - 1.10.2 Forge 221 - /#exportschematic does not function!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Ivorforce/RecurrentComplex#145]
![2017-01-18_17 00 40](https://cloud.githubusercontent.com/assets/10351221/22086721/b351a95a-dd9f-11e6-9c53-7b442d103022.png)

https://gist.github.com/P3rf3ctXZer0/b541dedd86a0372987c312135871095f

**Comment by Ivorforce** [comment]
Your version of IvToolkit is outdated.

**Comment by P3rf3ctXZer0** [comment]
What do you mean? This is the only 1.10.2 available? @Ivorforce 
![latest](https://cloud.githubusercontent.com/assets/10351221/22089443/da6b701e-ddb0-11e6-9b17-7318f5a5cd29.PNG)

**Comment by P3rf3ctXZer0** [comment]
![help](https://cloud.githubusercontent.com/assets/10351221/22089509/2c22aefe-ddb1-11e6-8d01-e0967b62fc38.PNG)

**Comment by P3rf3ctXZer0** [comment]
![1 10 2](https://cloud.githubusercontent.com/assets/10351221/22089518/421ce44a-ddb1-11e6-81ca-2fe3525e64c4.PNG)

**Comment by P3rf3ctXZer0** [comment]
![plezsaee](https://cloud.githubusercontent.com/assets/10351221/22089534/654856b6-ddb1-11e6-94dd-7d88ee8124b7.PNG)

**Comment by P3rf3ctXZer0** [comment]
Am I missing something?

**Comment by P3rf3ctXZer0** [comment]
https://github.com/Ivorforce/RecurrentComplex/issues/146

**Comment by P3rf3ctXZer0** [comment]
![123123](https://cloud.githubusercontent.com/assets/10351221/22090469/6bf42304-ddb7-11e6-9e4e-ca476ad8b7fc.PNG)
