### ISSUE TITLE
Major Bug - 1.10.2 Forge 221 - /#exportschematic does not function! #145 <- Not fixed!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Ivorforce/RecurrentComplex#146]
https://github.com/Ivorforce/RecurrentComplex/issues/145

**Comment by P3rf3ctXZer0** [comment]
I have latest available release.

**Comment by P3rf3ctXZer0** [comment]
![123123](https://cloud.githubusercontent.com/assets/10351221/22090475/77ebb1fe-ddb7-11e6-989a-043b113f9c29.PNG)

**Comment by Towsty** [comment]
IvToolkit 1.2.9 - RecurrentComplex 1.2.7-1.10 - MinecraftForge 2221 

Same issues on /#exportschematic, same errors in console as above.

**Comment by P3rf3ctXZer0** [comment]
@Ivorforce can I get some input?
Are you even going to fix this?
Provide a file maybe?
