### ISSUE TITLE
Request Enhancement - Split Schematics that are too big to import - 1.10.2 Prevent Crashing

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Ivorforce/RecurrentComplex#148]
https://gist.github.com/P3rf3ctXZer0/9cd76a3da2ba28ea0ef3f968204f9e3c

**Comment by P3rf3ctXZer0** [comment]
https://github.com/Ivorforce/RecurrentComplex/issues/149

**Comment by Ivorforce** [comment]
This is on my todo list - however, for now it should suffice to turn previews off (/#preview none)
