### ISSUE TITLE
Major Corruption - 1.10.2 Forge 221 - /#importschematic when files are too big

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Ivorforce/RecurrentComplex#149]
After importing a schematic that exceeded a certain amount of bytes my world will not load and is corrupted beyond repair.

![ghghg](https://cloud.githubusercontent.com/assets/10351221/22122015/cc8502c6-de4b-11e6-8261-b21059c6b16f.PNG)

**Comment by P3rf3ctXZer0** [comment]
https://github.com/Ivorforce/RecurrentComplex/issues/148

**Comment by P3rf3ctXZer0** [comment]
https://gist.github.com/P3rf3ctXZer0/36b42217392bf8b277b6da34f5f5f07a

**Comment by Ivorforce** [comment]
You need to clear just your player data from the NBT and it will work again.

**Comment by P3rf3ctXZer0** [comment]
Okay thank you!
