### ISSUE TITLE
World Crash/Freeze

### ISSUE THREAD

**Issue by kenijey** [Ivorforce/RecurrentComplex#150]
my open lan server freezed. i looked at fml log and it seems like recurrent complex causes. and deleted this mod, issue solved. here is the latest fml log
[fml-client.txt](https://github.com/Ivorforce/RecurrentComplex/files/719993/fml-client.txt)
using game 1.11.2 forge 2223 latest recurrent complex and ivtoolkit.

**Comment by Ivorforce** [comment]
I can't see a crash in there. It's entirely possible that the server is still generating a bigger structure at the moment (some rare ones can span multiple chunks and cause chain generating, resulting in a lag spike). I'd recommend waiting 5 minutes at before assuming a total freeze.

**Comment by kenijey** [comment]
Hello.
Here it is the my latest log file. Please look at to the end.

[latest.txt](https://github.com/Ivorforce/RecurrentComplex/files/721774/latest.txt)

But what happened? I go somewhere in my server. And same thing happened. I remembered you, then started to wait. Waited 2 mins, not touching to the game. And i go eat, drink water, etc.... did many thing; and i came back to the computer, approximately waited 25 mins, but it still as it is! then opened taskmgr and closed minecraft, because it was freezed. PLEASE help, i don't want to delete your mod, it is a good mod...
And, my fml-log file is 30 megabytes. If you want to see it, i can make .rar it and upload somewhere. And i have a crash report now.
[crash-2017-01-22_10.36.12-server.txt](https://github.com/Ivorforce/RecurrentComplex/files/721773/crash-2017-01-22_10.36.12-server.txt)
And, if this problem is not fault of your mod, then i'm so sorry, but please tell it to me. I can delete another mod but your mod. Thanks a lot.
