### ISSUE TITLE
[1.7.10] Unplayable FPS after importing structure on server

### ISSUE THREAD

**Issue by xenoswift** [Ivorforce/RecurrentComplex#151]
After importing a structure into a server, I get inconsistent chunkloading directly around the structure and unplayable framerate, worsening near the center of the structure.
I thought it was the Negative Space blocks but the problem still exists after replacing them with stone using WorldEdit.

![2017-01-21_14 15 24](https://cloud.githubusercontent.com/assets/8413024/22177035/5cea3392-dfe4-11e6-8f09-d417d6beb2e7.png)

Attached capture of inside the structure on the server with basic F3 menu open. I've never experienced this when importing structures on SSP. Render distance doesn't matter, chunks stay inconsistently loaded and FPS is still in the tens. I removed some assorted furniture on the off-chance they were the problem but no  change.

As an aside, the structure files exist both on the server and the client. Is this a problem for Recurrent Complex or am I just unlucky?
When importing I did receive the error about possible looped structure generation. I assumed that was irrelevant given its a fairly tail structure. Is the presence of the structures on the server and client possibly putting something into a loop causing abysmal FPS? If that's the case, why is my TPS stable at 20?

**Comment by xenoswift** [comment]
After using WorldEdit to replace the area with air, the framerate issue is partly resolved but I have chunk updates in the hundreds on a server with nothing constructed and nothing chunkloaded.

![2017-01-21_14 28 53](https://cloud.githubusercontent.com/assets/8413024/22177127/3a13a252-dfe6-11e6-975e-d4b4cab2d2df.png)
 
Going up to the surface--not even thirty blocks--chunk updates are gone and FPS is stable at 60.

![2017-01-21_14 30 02](https://cloud.githubusercontent.com/assets/8413024/22177136/4eb71126-dfe6-11e6-8c66-ccad6ca18487.png)

**Comment by Ivorforce** [comment]
Keep in mind that Recurrent Complex has no effect on the environment, ticks or anything else after an import is complete. It's one of the principles i keep in mind when developing.
The lag must be caused by the imported area - confused tile entities, cache building or whatever else it could be. Try restarting client and server next time and see if that resolves the problem - otherwise, press shift-f3 to see where exactly the lag is coming from.

**Comment by xenoswift** [comment]
I've restarted server and client several times. 

Here, I've started the exact same pack and everything on my desktop instead of on my server box. I've generated the structure in air. 

![2017-01-21_14 42 54](https://cloud.githubusercontent.com/assets/8413024/22177377/63145184-dfea-11e6-8d22-888816af9987.png)


No problems. But in recreating the circumstances of importing underground, I have the same result as earlier; unplayable framerate and hundreds of chunk updates per second even after reasonable pause.

![2017-01-21_15 00 03](https://cloud.githubusercontent.com/assets/8413024/22177384/796b6d46-dfea-11e6-9f4a-b6a984d27d05.png)

Moving out of the structure returns some of the performance.

Running and looking over Opis there are no nearby Tile Entities it can detect, and of those it can detect they are using less than 10 microseconds of update time. All other entity counts are less than 50 microseconds and the most intensive Entity detected is a minecart chest.

**Comment by Ivorforce** [comment]
If it's neither caching / garbage collecting nor tile entities or entities I really cannot say. All I can tell you is that ReC does not do anything after the command has completed running. 
You can try removing the mod and see if that fixes the issue - if it does, I'll try to look into it somehow.

**Comment by xenoswift** [comment]
Problem still exists after removing recurrent complex. 

![2017-01-21_15 24 28](https://cloud.githubusercontent.com/assets/8413024/22177528/b66ab49c-dfed-11e6-8f3f-90aee6bd638f.png)

**Comment by Ivorforce** [comment]
Then, like I said, it's not (directly) caused by it and I cannot do anything about it. I'm guessing it's some mod's content getting confused and causing lag, or similar.

**Comment by xenoswift** [comment]
still getting ~300 Chunk updates and crazy resource usage but I have 45 FPS now.
After removing IE's steel fences.

![2017-01-21_15 37 02](https://cloud.githubusercontent.com/assets/8413024/22177625/8ed5a912-dfef-11e6-9607-b30dea3867a0.png)

I don't even

**Comment by xenoswift** [comment]
So after trying without Immersive Engineering running I pasted the exact same structure underground --TWICE, one right under the other-- and I have perfect framerate. Render usage is high but I still have the negative space blocks and I know those can be heavy in high amounts. I'll just cull them from the structures.

I still have this error which is strange since the structure is only about 10 blocks high. I did see a release on your Curse page that there's an update so I'll update and see if that fixes it.
[15:47:06] [Server thread/WARN] [reccomplex]: Structure generated with over 30 l
ayers; most likely infinite loop!

But I think the original topic of crippled performance is closed. The fault is Steel Fences from Immersive Engineering.

**Comment by Ivorforce** [comment]
The warning is false, don't worry about it :)
Negative Space blocks are meant for generating structures only (/#gen instead of /#import). You don't need to use them if you just move structures.

**Comment by xenoswift** [comment]
Yeah I think that was a 4am no coffee decision to add the negative space. Thanks for essentially giving me a sounding board to hammer out the issue

**Comment by xenoswift** [comment]
Just as a small request, can you look into anything in Recurrent Complex's 1.7 version that may be asking for chunk updates when the player is near a RecCom-created structure? I float at about 130-150 chunk updates when standing still in a structure and down near the expect 0-15 when I leave the bounds of the structure.

**Comment by Ivorforce** [comment]
It completely depends on how the mods implement their blocks - so, some might not like being transferred from one position to another, so to say. Like I said, to Minecraft, after generation, it is as though the player had built the structure by hand. Recurrent Complex will never touch it again afterwards.

**Comment by xenoswift** [comment]
Aight. I think I'm just on a hair-trigger for performance weirdness right now I'll stop bothering you. :> Thank you again for your time
