### ISSUE TITLE
Custom trees spawn near the saplings and the saplings arent destroyed

### ISSUE THREAD

**Issue by EnderStar** [Ivorforce/RecurrentComplex#152]
Hi, i placed 3 oak saplings in the position tospawn a custom tree with bonemeal and it spawned but next to the saplings also the saplings werent destroyed. Using v.1.2.7.1 for 1.10.2
Thanks!

**Comment by Ivorforce** [comment]
Hey, you must have configured the pattern wrong. The position of the saplings you set there must be relative to the structure origin :)

**Comment by EnderStar** [comment]
This happens with the default trees, just added the mod and spawned a sapling
