### ISSUE TITLE
Multiplayer Server will not start with mod

### ISSUE THREAD

**Issue by GamerbyDesign** [Ivorforce/RecurrentComplex#153]
I am using Forge 12.18.3.2219 on Minecraft 10.2.  I will post the crash log soon.

**Comment by Ivorforce** [comment]
Is there a crashlog coming or...?

**Comment by GamerbyDesign** [comment]
Sorry I've been really busy as of late.  Anyways I was on 1.2.6.2 and upgraded to 1.2.7.1 and it fixed the issue
