### ISSUE TITLE
[Compat Request]Compat with Stacks On Stacks' placed ingots

### ISSUE THREAD

**Issue by thephoenixlodge** [Ivorforce/RecurrentComplex#157]
Currently trying to include placed ingots from SoS in a structure results in an unknown error on attempting to gen the structure. As such, I would like to request the addition of compatability for generating structures with these ingot piles.

StacksOnStacks: https://minecraft.curseforge.com/projects/stacksonstacks

**Comment by Ivorforce** [comment]
Can you post a log of a session where the error occurred?

**Comment by thephoenixlodge** [comment]
Here's the relevant part of the log with the error that comes up when generating:
http://pastebin.com/7v5b9HVW

I can post a more full log if needed, though curiously the error only shows up in the latest.log file and not in the fml-client-latest.log file

After actually seeing the error in the log this time (last time the console was frozen), I tried changing the placement of the ingot stacks to a spot more in line with their placement rules, but it still produced the same error.

**Comment by Ivorforce** [comment]
'Illegal position' haha

I'll try to get a hold of the author and see what we can figure out.

**Comment by thephoenixlodge** [comment]
Thanks, I look forward to being able to make structures with piles of ingots as loot :)

**Comment by Ivorforce** [comment]
Got a hold of Amadornes and they said they'll get a fix out in the next version of MCMultipart.

**Comment by Ivorforce** [comment]
Oh right, I closed this a bit prematurely. Of course this one fix won't guarantee compatibility - let me know if it's still causing problems with the next release.
