### ISSUE TITLE
Exception in server tick loop server crash when player logs on.

### ISSUE THREAD

**Issue by Apocryphai** [Ivorforce/RecurrentComplex#158]
Player was in an Aroma1997 mining dimension and the server crashed. Now the server crashes again as soon as that player logs in.

Minecraft crash log: https://zerobin.net/?abb3b649bab28874#qebn85fLe+cqor3zHbw16hgTQIuuqXAuHrA5zjt5HNI=

FML log: https://zerobin.net/?7dc514835d5d20a1#xfW9KSFGqB8LoVJ1K2ZwJwyPQpnAZooig4LoLFPG5O0=

**Comment by Ivorforce** [comment]
Your version of Recurrent Complex is outdated (or you need to downgrade IvToolkit to a lower version as well).
