### ISSUE TITLE
Recurrent Complex and Apache Commons Libraries Crash

### ISSUE THREAD

**Issue by GodNero** [Ivorforce/RecurrentComplex#16]
Minecraft - 1.7.10
Forge - 10.13.3.1389

Files In the mods and library folders when following crash logs occurred:
Recurrent Complex - 0.9.6.1
IvToolkit - 1.1.1
Commons-Codec - 1.9
Commons-Compress - 1.8.1

The following crashes happen after we updated from Forge 1291 to the current release 1389:
Recurrent Complex and both Commons Libaray files: http://puu.sh/hmeOL/7e49af13b8.txt
Recurrent Complex and Commons-Codec: http://puu.sh/hmf2Z/77d6eb8bdd.txt
Recurrent Complex and Commons-Compress: http://puu.sh/hmf3H/7dfbf6a04a.txt

I have narrow the issue down to Recurrent Complex/IVToolKit and Either or Both  Commons-Codec and Commons-Compress Library Files that are required for INPureCore. INPureCore was not left in the mods folder in the three crash reports above, however it was present during the first crash not listed here, as the game will load with out INPureCore present and having the library files in their respective folder.

The crash occurs after the user, my self in this case, attempts to generate a new world. I attempted this Using all world types available in the Resonant-Rise 3 Mod Pack;
BoP, Realistic World Generation (Alpha), Fun World Gen, Old World Gen, as well as Vanilla.

I tested this set up with Recurrent Complex nightly build 0.9.6.1.n242 and the issue seems to have been fixed, but I figured I would let you know that this is a issue with the current public release.

-Nero RR3 Pack Dev

**Comment by Ivorforce** [comment]
I'm suspecting this is an FML bug related to https://github.com/MinecraftForge/FML/commit/d14d1a8fea4c9242c944079ab8e4cdd516dfce4c

Please try using a build before this commit (1.7.10-10.13.3.1385, for example), and report back how it plays out. If it doesn't crash on that build, it's Forge's fault and I'll report it to the aforementioned commit.

**Comment by RedsaphirCZ** [comment]
With forge 1.7.10-10.13.3.1385 works fine, it's forge related bug

**Comment by Ivorforce** [comment]
Ported to https://github.com/MinecraftForge/FML/issues/651 for hope of a fix.

**Comment by liach** [comment]
Add a `compile "org.apache.commons:commons-lang3:3.2.1"` to the dependencies task in build.gradle?

**Comment by Ivorforce** [comment]
Apache Commons lang should be, and was, inherently part of any Forge / Minecraft distribution before the 10.13.3.1388 release. I should not need additional gradle dependencies.

**Comment by cpw** [comment]
@Ivorforce if you'd spent a minute looking, you'd have noticed that it still is. However, the version is wrong. Mojang ships the 3.1 version, which *doesn't* include the Triple class. Forge, for some reason, is shipping 3.2.1 in the dev env. I am correcting both these errors.

**Comment by JAWSAWN** [comment]
Isn't this fixed yet?

**Comment by Ivorforce** [comment]
I wish.... cpw did make a [fixing commit](https://github.com/MinecraftForge/FML/commit/7c10b93a2ded2799d41b73b67a2766c31e992d8a), but it doesn't look like they released a build with it yet...

**Comment by Ivorforce** [comment]
Can confirm newest builds fix the issue.

**Comment by JAWSAWN** [comment]
Forge or RC?

**Comment by liach** [comment]
The library bug fixed since build 1399 right?

**Comment by JAWSAWN** [comment]
I can confirm that it works without any problem in the forge version 1401.

**Comment by Tsyklop** [comment]
Forge 1388 crash... laset version mods
