### ISSUE TITLE
structures generate in other dimensions

### ISSUE THREAD

**Issue by Hypsellis** [Ivorforce/RecurrentComplex#164]
I get Recurrent Complex structures in the Betweelands and AbyssalCraft dimensions while they aren't supposed to generate at all in these dimensions. You seem to have forgotten to check the dimension for knowing where your structures are supposed to generate them.

**Comment by Ivorforce** [comment]
There is a dimension check - however, it's dependent on the dimensions using the DimensionDictionary, which hasn't been merged into Forge yet (though it is available for use inside ReC's code).
You can disable generation for those dimensions yourself using the universalDimensionMatcher.

**Comment by Hypsellis** [comment]
Oh yeah sorry, I found the option, now it works fine, anyway thanks for the answer. :)
