### ISSUE TITLE
Leaves generating in random places (mainly on water)

### ISSUE THREAD

**Issue by tomfulghum** [Ivorforce/RecurrentComplex#165]
In my custom modpack, leaves are randomly generating where they shouldn't be. It's always one birch leaf and one spruce leaf block. Here's a screenshot:

https://imgur.com/a/zvIv7

RC is definitely the source of the problem, since those leaves are not generated with only RC disabled. /#whatisthis doesn't give any information. As far as my observation goes, it only happens in Taiga biomes.

Other installed mods which greatly influence terrain generation are:
- Rougelike dungeons
- Biomes'o'plenty
- Natura
- Quark (realistic world type)

Any idea which structure could be the cause of this?

**Comment by Ivorforce** [comment]
Try enabling memorizeDecoration in the config and generating a new world. Then /#whatisthis should work.

**Comment by tomfulghum** [comment]
That worked! Apparently the culprit is "SpruceTree". I'm going to try disabling it and see how that affects the world.

**Comment by Ivorforce** [comment]
Okay, interesting. I will check the structure myself as well :)

**Comment by tomfulghum** [comment]
Yep, disabling the structure "SpruceTree" fixed the problem. 
By the way, changing the structureGenerationMatcher through the in-game config requires a game restart to take effect. Don't know if that's intentional.

**Comment by Ivorforce** [comment]
Not entirely - it merely requires a /#reload  (or one for every affected type - CUSTOM, MODDED or WORLD). :)

**Comment by tomfulghum** [comment]
Ah, okay. Thanks for the quick help!

**Comment by Ivorforce** [comment]
Fixed in 7d7cdb225eed09697a9f1ec57f922af21d412666.
