### ISSUE TITLE
Acacia leaves on Oak tree

### ISSUE THREAD

**Issue by DeGariless** [Ivorforce/RecurrentComplex#166]
Offender:
structures\nature\trees\GenericTreeSmall.rcst

This oak tree has acacia leaves. [Here is a replacement file](https://www.dropbox.com/s/8mk6ue10a64wklz/GenericTreeSmall.rcst?dl=1) changing the leaves to oak leaves

Edit: Forgot to include some key information
MC: 1.10.2
Forge: 2254
RC: 1.2.9.1-1.10.2

**Comment by DeGariless** [comment]
Upon further inspection, There is another tree oak tree that has birch leaves. I haventn't found the file for that one yet

**Comment by Ivorforce** [comment]
Fixed in ddf99161afa2b9d5446b15b5a02f8af3fe0cf353. Let me know if there are others.
