### ISSUE TITLE
Flat structure

### ISSUE THREAD

**Issue by drakray** [Ivorforce/RecurrentComplex#168]
I came across this kind of structure VERY often, structure with only 1 layer of block
![2017-03-18_12 53 49](https://cloud.githubusercontent.com/assets/4303126/24074202/4a773b0c-0bda-11e7-8241-21b3d748be68.png)

Is this intended?

**Comment by Ivorforce** [comment]
Perhaps it's a bit extreme. Those are the result of the ruins transformer being a bit harsh - I'll adjust this a bit later.

**Comment by drakray** [comment]
MC 1.11.2
Forge 2259
IvT 1.3.2.1
RC 1.2.10

**Comment by P3rf3ctXZer0** [comment]
@Ivorforce I would like to note this seems to be more evident when using any none default settings with the exception of the BIOMESOP generator.

**Comment by Ivorforce** [comment]
What do you mean by 'none default settings ' and 'BIOMESOP generator'?

**Comment by drakray** [comment]
it wasn't only those two, I often find "flat" structure, of rather VERY destroyed one, like Castle, and multiple kind of house

**Comment by Ivorforce** [comment]
They are supposed to be partially (or almost completely) destroyed. They're supposed to be ruins, if that is not clear :P

**Comment by drakray** [comment]
Ah ok, I thought there was a chance to find fairly intact Castle in the wild(as I saw some in old version) ;)
No problem though
