### ISSUE TITLE
[1.10.2] [RC 1.2.9.1] [Terrain Control 2.8.2] Exception preparing structure feature

### ISSUE THREAD

**Issue by Alaberti** [Ivorforce/RecurrentComplex#169]
I just got this error on a dedicated server. Crash log: http://pastebin.com/raw/YiPm8Y5T

**Comment by Alaberti** [comment]
Seems to happen in desert biomes.

**Comment by Ivorforce** [comment]
It kind of looks like MC is missing the biome info for that particular biome. Try reporting this to TerrainControl.
