### ISSUE TITLE
Custom Trees break tile entities, Like botania flowers

### ISSUE THREAD

**Issue by darkshadow543** [Ivorforce/RecurrentComplex#171]
I have a custom mod pack with many mods, and the main complaint here is that the trees/ replanted saplings destroyed an expensive tile.  Could you add a check to prevent saplings from replacing tiles or a config to disable custom trees from saplings or sapling replanting?

**Comment by Ivorforce** [comment]
There is already a check for trees to never destroy tiles that are non-replaceable (e.g. air / grass). There are also already plenty of options to adjust or completely disable custom saplings. What version are you on?

**Comment by Ivorforce** [comment]
Closing stale issue.
