### ISSUE TITLE
[1.2.10] Trees Without Trunks

### ISSUE THREAD

**Issue by MurphysChaos** [Ivorforce/RecurrentComplex#172]
Trees in 1.2.10 are generating without trunks. Started noticing far from world spawn (around 8000,-5000).

I deleted the nearby regions from my world, reverted to 1.2.9.1, and the trees started generating correctly again.

![2017-03-26_22 20 12](https://cloud.githubusercontent.com/assets/98659/24385280/4aa42c5c-1337-11e7-8823-c615abba6a86.png)

**Comment by Ivorforce** [comment]
Try redownloading 1.2.1.0. There was a version of it that was up for a few hours (I believe) that had this problem, but I quickly deleted it in favour of one that had a few more hotfixes applied.

**Comment by Ivorforce** [comment]
Closing stale issue.
