### ISSUE TITLE
Crash when using structure spawn list

### ISSUE THREAD

**Issue by OtterofDeath** [Ivorforce/RecurrentComplex#173]
Whenever I try to generate a structure that has a spawn script that uses a structure list, the game crashes. Furthermore, after experiencing this crash, my game for some reason thinks that save that crashed is a multiplayer server. Whenever I try to open that save it gives a "Disconnected from server" error and kicks me to the multiplayer section of the main menu. 

Crash report attached
[Crash.txt](https://github.com/Ivorforce/RecurrentComplex/files/884317/Crash.txt)

**Comment by Ivorforce** [comment]
Are you on the latest version? Because I think that's been fixed in 1.2.10.

**Comment by OtterofDeath** [comment]
I'm using 1.2.10 for Minecraft 1.10. But I'm also testing this with structures I made with an older version of Recurrent Complex, would that be a problem?

**Comment by Ivorforce** [comment]
Nope, ReC should be 100% backwards compatible (and afaik no version of the structure files should be broken). I'll investigate then.

**Comment by Ivorforce** [comment]
Not sure how this would even happen but I think it shouldn't happen again. If it reoccurs in the next version (probably 1.2.10.1) please reopen the issue.
