### ISSUE TITLE
[1.11.2] Particular spruce tree does not decay leaves properly

### ISSUE THREAD

**Issue by Rosethorns** [Ivorforce/RecurrentComplex#174]
http://i.imgur.com/S3NpnDN.png
http://i.imgur.com/NVdy4iu.png

This particular tree is a pain when clear cutting. Can anything be done about it?

**Comment by Ivorforce** [comment]
I don't recognize it (perhaps because of the texture pack + foliage mod). Could you turn memoreGeneration / memoreSaplings on and do /#whatisthis inside? (Must be another newly generated tree though).

**Comment by Ivorforce** [comment]
Closing stale issue.
