### ISSUE TITLE
1.10.2 Bug Hunting - Has anyone had these issues in world generation before?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Ivorforce/RecurrentComplex#176]
![2017-04-08_05 25 48](https://cloud.githubusercontent.com/assets/10351221/24831291/f6ac56f4-1c5c-11e7-8893-0944e89d6214.png)
![2017-04-08_05 25 53](https://cloud.githubusercontent.com/assets/10351221/24831293/f6b885be-1c5c-11e7-9fd9-501d2aa92f94.png)
![2017-04-08_05 25 56](https://cloud.githubusercontent.com/assets/10351221/24831296/f6bc8a42-1c5c-11e7-8965-9583b0e86553.png)
![2017-04-08_05 26 08](https://cloud.githubusercontent.com/assets/10351221/24831295/f6bafe48-1c5c-11e7-81cf-8828f06a1e57.png)
![2017-04-08_05 26 13](https://cloud.githubusercontent.com/assets/10351221/24831294/f6babcc6-1c5c-11e7-9e8e-5692951ab0fa.png)
![2017-04-08_05 26 46](https://cloud.githubusercontent.com/assets/10351221/24831297/f6bcac98-1c5c-11e7-9985-d3d79ef2f7ac.png)
![2017-04-08_05 27 06](https://cloud.githubusercontent.com/assets/10351221/24831292/f6b725d4-1c5c-11e7-9ea2-1e5458546a63.png)
![2017-04-08_05 27 14](https://cloud.githubusercontent.com/assets/10351221/24831298/f6c37212-1c5c-11e7-9bd1-1dfe437a7f41.png)
![2017-04-08_05 27 24](https://cloud.githubusercontent.com/assets/10351221/24831299/f6c4f0d8-1c5c-11e7-885b-c45c7bcf5d97.png)
![2017-04-08_05 27 32](https://cloud.githubusercontent.com/assets/10351221/24831300/f6c4f902-1c5c-11e7-89fd-ef310af8abfa.png)
![2017-04-08_05 27 40](https://cloud.githubusercontent.com/assets/10351221/24831301/f6c65586-1c5c-11e7-9009-aa6f9875ba9a.png)

This is not a bug report please don't close until I can figure out the issue.

**Comment by P3rf3ctXZer0** [comment]
https://github.com/fewizz/NotEnoughIDs/issues/58

**Comment by P3rf3ctXZer0** [comment]
https://github.com/ternsip/StructPro/issues/6

**Comment by P3rf3ctXZer0** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/issues/980

**Comment by Ivorforce** [comment]
Seems like you removed world generation mods and loaded the same world again - maybe there were some leftover world files or something.

**Comment by P3rf3ctXZer0** [comment]
Okay that is a concept ; I don't know how though these bugs are on a fresh file set.

**Comment by P3rf3ctXZer0** [comment]
https://github.com/Sinhika/SimpleOres2/issues/7

**Comment by P3rf3ctXZer0** [comment]
I am going to remove all ore and world generation mods when I get home.

**Comment by Ivorforce** [comment]
It should mostly just be biome mods rather than ore / world gen ones, i.e. stuff that modifies terrain heights.
