### ISSUE TITLE
[1.10.2] Server Crashes

### ISSUE THREAD

**Issue by Ra-Zim** [Ivorforce/RecurrentComplex#177]
I am using Recurrent Complex in the light mode or whatever it's called. I pre-gen'd the world and everything has been fine for about two months, but starting yesterday, I've been getting multiple crashes pointing to this mod as the problem. I disabled the mod and everything was fine, I then re-enabled it and the server is crashing again. Here are some of the crash reports I've gotten:

https://pastebin.com/G1q1vNpd
https://pastebin.com/hkmP8uw6 (most are like this)

**Comment by Ivorforce** [comment]
Try updating to 1.10.

**Comment by ChriLP** [comment]
I had the same problem, used Verson 1.2.4 of the mod and it worked. ;D

**Comment by Ivorforce** [comment]
Closing stale issue.
