### ISSUE TITLE
Question - How do I add schematics as active spawning structures?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Ivorforce/RecurrentComplex#180]
I was wondering how I add active schematics like those found on other websites and how do I make sure they are not ruin structures and fully spawn?

**Comment by Ivorforce** [comment]
You put the schematics inside the structures/schematics folder (run /#files to find it), do /#convert <schematicname> or /#importschematic <schematicname> and from there you can work with it as a normal structure. They'll only look like ruins if you add a ruins transformer to it.

Please refer to [the wiki](http://minecraft-recurrent-complex.wikia.com/wiki/Guide:_Building_a_Structure) for more info on this :)

**Comment by P3rf3ctXZer0** [comment]
Can you post this on the front page or have a direct QA link? I guarantee someday I will forget. XD @Ivorforce

**Comment by Ivorforce** [comment]
It's really just /#importschematic (which is linked on the wiki) and building a structure from it (which is linked from the wiki). Nothing extraordinary to especially write a new article about...
