### ISSUE TITLE
Question - How do I do a mass conversion?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Ivorforce/RecurrentComplex#181]
I have like 2600 schematics ... and I really don't want type /#convertschematic *filename and set it to active ... Is there a faster way?

**Comment by Ivorforce** [comment]
What, why do you have so many schematics?
Most schematics need to be set up individually either way - like what biomes do they spawn in, and at what height at the very least - even if you don't consider adjusting the blocks to use natural floor and space blocks to integrate into the terrain better. So you'd need to individually configure each structure either way, making a mass conversion command pointless.
