### ISSUE TITLE
Request - A Way to Disable Ruin Structure Generation? 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Ivorforce/RecurrentComplex#182]
I was browsing the configuration files and noticed there is currently no to prevent ruin structure generation which I find pretty tacky. Since I love structure generation is there a way you could add the following generation commands?

Ignore Ruin Generation Attribute=true / false
Disable Spawning Ruin Structures= true /false

**Comment by Ivorforce** [comment]
There are plenty of ways to disable structures - [see the wiki](http://minecraft-recurrent-complex.wikia.com/wiki/Disabling_Structures).
