### ISSUE TITLE
Question - How do I make a structure only generate in sand?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Ivorforce/RecurrentComplex#183]
![10](https://cloud.githubusercontent.com/assets/10351221/25316412/8c59198c-282c-11e7-9b89-b2a7e86aeab7.PNG)

while converting a schematic I am trying to make this only spawn if there is a minimum of 200 sand blocks near generation site.

**Comment by Ivorforce** [comment]
I recommend using the biome expressions to limit the generation to $SANDY - type biomes.
You can further limit generation using the placer to a surface or generation site consisting of sand blocks. You can read up on this on the wiki.
