### ISSUE TITLE
Crashes when villages are present

### ISSUE THREAD

**Issue by toyarmy5000** [Ivorforce/RecurrentComplex#184]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  IvToolkit (IvToolkit-1.2.2.jar)
  CCCDeobfPlugin (unknown)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.34-universal.jar)
  DLFMLCorePlugin (DynamicLights-1.8.jar)
  WallpaperLoadingPlugin (wallpaper-0.9-1.8.jar)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.82-universal.jar)
  Mine and Blade: Battlegear2 (1.8-MB_Battlegear2-Bullseye-1.0.10.1.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 4/25/17 11:50 AM
Description: Exception preparing structure feature

java.lang.RuntimeException: StructureComponent "ivorius.reccomplex.dynamic.vanillagen.VillageWoodMill_VanillaGen1" missing ID Mapping, Modder see MapGenStructureIO
	at net.minecraft.world.gen.structure.StructureComponent.func_143010_b(StructureComponent.java:40)
	at net.minecraft.world.gen.structure.StructureStart.func_143021_a(StructureStart.java:81)
	at net.minecraft.world.gen.structure.MapGenStructure.func_143026_a(MapGenStructure.java:274)
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:42)
	at net.minecraft.world.gen.MapGenBase.func_175792_a(SourceFile:28)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_180514_a(ChunkProviderGenerate.java:575)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.gen.structure.StructureComponent.func_143010_b(StructureComponent.java:40)
	at net.minecraft.world.gen.structure.StructureStart.func_143021_a(StructureStart.java:81)
	at net.minecraft.world.gen.structure.MapGenStructure.func_143026_a(MapGenStructure.java:274)

-- Feature being prepared --
Details:
	Is feature chunk: True
	Chunk location: 45,-81
	Chunk pos hash: -347892350931
	Structure type: net.minecraft.world.gen.structure.MapGenVillage
Stacktrace:
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:42)
	at net.minecraft.world.gen.MapGenBase.func_175792_a(SourceFile:28)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_180514_a(ChunkProviderGenerate.java:575)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Mac OS X (x86_64) version 10.11.4
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 575534936 bytes (548 MB) / 1965555712 bytes (1874 MB) up to 1965555712 bytes (1874 MB)
	JVM Flags: 2 total; -Xms2048m -Xmx2048m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 62 mods loaded, 62 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHIJAAAA	Forge{11.14.4.1563} [Minecraft Forge] (modpack.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.5.34} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{1.2.2} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.82} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.82-universal.jar) 
	UCHIJAAAA	battlegear2{1.8} [Mine & Blade Battlegear 2 - Bullseye] (1.8-MB_Battlegear2-Bullseye-1.0.10.1.jar) 
	UCHIJAAAA	securitycraft{v1.8.2} [SecurityCraft] ([1.8] SecurityCraft v1.8.2.jar) 
	UCHIJAAAA	bspkrsCore{7.01} [bspkrsCore] ([1.8]bspkrsCore-universal-7.01.jar) 
	UCHIJAAAA	FloatingRuins{1.8.r01} [FloatingRuins] ([1.8]FloatingRuins-universal-1.8.r01.jar) 
	UCHIJAAAA	imsm{1.8} [Instant Massive Structures Mod] ([1.8]InstantMassiveStructuresMod2.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (Backpacks-Mod-1.8.jar) 
	UCHIJAAAA	BetterLeather{2.0} [Better Leather] (BetterLeather-universal-1.8-2.1.0.jar) 
	UCHIJAAAA	buildingbrickscompatvanilla{1.1.2} [Building Bricks Vanilla Compat] (BuildingBricks-1.1.2.jar) 
	UCHIJAAAA	buildingbricks{1.1.2} [Building Bricks] (BuildingBricks-1.1.2.jar) 
	UCHIJAAAA	cfm{4.0.1} [MrCrayfish's Furniture Mod] (cfm-4.0.1-mc1.8.jar) 
	UCHIJAAAA	ChestTransporter{2.1.0} [Chest Transporter] (ChestTransporter-2.1.0-MC1.8.jar) 
	UCHIJAAAA	chisel{@VERSION@} [Chisel 3] (Chisel-Mod-1.8.jar) 
	UCHIJAAAA	ComputerCraft{1.76} [ComputerCraft] (ComputerCraft1.76.jar) 
	UCHIJAAAA	craft_convenience{1.0} [Craft Convenience] (Craft Convenience by NukeDuck [1.8][1.0].jar) 
	UCHIJAAAA	dldungeonsjdg{1.8.7b} [Doomlike Dungeons] (DoomlikeDungeons-1.8.7b-MC1.8.jar) 
	UCHIJAAAA	DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	exoticbirds{1.0} [Exotic Birds] (Exotic Birds 1.8 - 1.0.3b.jar) 
	UCHIJAAAA	ModUtilsLib{2.0.3} [ModUtilsLib] (ModUtilsLib-2.0.3-mc1.8.jar) 
	UCHIJAAAA	FastLadder{1.0.2} [FastLadder!] (FastLadder-1.0.2-mc1.8.jar) 
	UCHIJAAAA	flansmod{5.3.1} [Flan's Mod] (Flan's Mod-1.8-5.3.1.jar) 
	UCHIJAAAA	InfernalMobs{1.6.5} [Infernal Mobs] (InfernalMobs-1.8.jar) 
	UCHIJAAAA	ism{1.5.9 MC-1.8} [Instant Structures Mod (ISM)] (ism-1.5.9 MC-1.8.jar) 
	UCHIJAAAA	RadixCore{1.8-2.1.0} [RadixCore] (RadixCore-1.8-2.1.0-universal.jar) 
	UCHIJAAAA	MCA{1.8-5.1.1.2} [Minecraft Comes Alive] (MCA-1.8-5.1.1.2-universal.jar) 
	UCHIJAAAA	mineralogy{2.5.1} [Mineralogy] (mineralogy-2.5.1.jar) 
	UCHIJAAAA	MiniBosses{1.2.8} [Mini-Bosses] (MiniBosses-1.2.8.jar) 
	UCHIJAAAA	morematerials{1.0.20150301.0} [More Materials] (morematerials-1.0.20150615.0-MC1.8-20150614.jar) 
	UCHIJAAAA	papertazermod{1.0} [Papertazers Base Mod] (Papertazers Base Mod-1.0 (1).jar) 
	UCHIJAAAA	parachutemod{3.1.1} [Parachute Mod] (parachutemod-1.8.0-3.1.2-151.jar) 
	UCHIJAAAA	reccomplex{0.9.7.2} [Recurrent Complex] (RecurrentComplex-0.9.7.2.jar) 
	UCHIJAAAA	corerm{1.2c} [RikMuld's Core] (RikMuldsCore_1.2c.jar) 
	UCHIJAAAA	roadmod{1.2} [Road Mod] (Road Mod - 1.2 (1).jar) 
	UCHIJAAAA	Roguelike{1.4.4} [Roguelike Dungeons] (RoguelikeDungeons-1.8-1.4.4.jar) 
	UCHIJAAAA	AS_Ruins{15.5} [Ruins Spawning System] (Ruins-1.8.jar) 
	UCHIJAAAA	SaltMod{1.8.c} [Salty Mod] (SaltyMod-1.8-1.8.c-1.jar) 
	UCHIJAAAA	shipwrecks{1.7.0} [Shipwrecks!] (shipwrecks-1.8.0-1.7.1.jar) 
	UCHIJAAAA	SophisticatedWolves{3.6.0} [SophisticatedWolves] (SophisticatedWolves-3.6.0.jar) 
	UCHIJAAAA	thetitans{0.21} [The Titans Mod] (The-Titans-Mod-1.8.jar) 
	UCHIJAAAA	camping{2.2f} [The Camping Mod 2] (TheCampingMod_2.2f.jar) 
	UCHIJAAAA	thutcore{2.1.3} [ThutCore] (thutcore-2.1.3.jar) 
	UCHIJAAAA	thuttech{2.1.5} [Thut's Tech] (thuttech-2.1.7.jar) 
	UCHIJAAAA	TooMuchTNT{3.0} [TooMuchTNT] (TooMuchTNT v3.0.jar) 
	UCHIJAAAA	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.8.jar) 
	UCHIJAAAA	wallpaper{0.9} [Wallpaper] (wallpaper-0.9-1.8.jar) 
	UCHIJAAAA	worldedit{6.1} [WorldEdit] (worldedit-forge-mc1.8-6.1.jar) 
	UCHIJAAAA	worldoverhaulmod{1.8_6_1} [World Overhaul Mod] (worldoverhaul-1.8-6_1.jar) 
	UCHIJAAAA	XaeroMinimap{1.9} [Xaero's Minimap] (Xaeros_Minimap_1.9_Forge_1.8.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
IvToolkit (IvToolkit-1.2.2.jar)
  
CCCDeobfPlugin (unknown)
  
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.34-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
DLFMLCorePlugin (DynamicLights-1.8.jar)
  atomicstryker.dynamiclights.common.DLTransformer
WallpaperLoadingPlugin (wallpaper-0.9-1.8.jar)
  com.pau101.wallpaper.core.WallpaperClassTransformer
NEICorePlugin (NotEnoughItems-1.8-1.0.5.82-universal.jar)
  codechicken.nei.asm.NEITransformer
Mine and Blade: Battlegear2 (1.8-MB_Battlegear2-Bullseye-1.0.10.1.jar)
  mods.battlegear2.coremod.transformers.EntityPlayerTransformer
  mods.battlegear2.coremod.transformers.ModelBipedTransformer
  mods.battlegear2.coremod.transformers.NetClientHandlerTransformer
  mods.battlegear2.coremod.transformers.NetServerHandlerTransformer
  mods.battlegear2.coremod.transformers.PlayerControllerMPTransformer
  mods.battlegear2.coremod.transformers.ItemRendererTransformer
  mods.battlegear2.coremod.transformers.RenderItemTransformer
  mods.battlegear2.coremod.transformers.MinecraftTransformer
  mods.battlegear2.coremod.transformers.ItemStackTransformer
  mods.battlegear2.coremod.transformers.ItemInWorldTransformer
  mods.battlegear2.coremod.transformers.EntityAIControlledByPlayerTransformer
  mods.battlegear2.coremod.transformers.EntityOtherPlayerMPTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['toyarmy5000'/294, l='New World', x=893.50, y=112.70, z=-1070.61]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by toyarmy5000** [comment]
i am using technic launcher, and using 1.8

**Comment by Ivorforce** [comment]
Check if the VillageWoodMill structure is loaded. You can at least get rid of the crash by having it loaded  (or making a new structure called VillageWoodMill with a village structure generation info named 'VanillaGen1', if all else fails).

I'm afraid though that 1.8 is no longer supported, and I won't be making additions for it.

**Comment by toyarmy5000** [comment]
how do you load it though?

**Comment by Ivorforce** [comment]
There are several options (like the structureLoadMatcher) related to it. You can make sure it's loaded by doing /#gen VillageWoodMill - if that works it's loaded.
