### ISSUE TITLE
[1.11.2] Crossmod Crash with Minecolonies

### ISSUE THREAD

**Issue by Terpo** [Ivorforce/RecurrentComplex#186]
When adding Minecolonies to a small modlist with ReccurentComplex the game crashes on world load.
Forge 2282
minecolonies-universal-1.11.2-0.7.683
RecurrentComplex-1.2.10
IvToolkit-1.3.2.1

Crashlog: https://gist.github.com/Terpo/ca262da8de4517a8da7308d2f27073d8

Reference: https://github.com/Minecolonies/minecolonies/issues/899

**Comment by Ivorforce** [comment]
Should be fixable/fixed from their end. Let me know if there are persistent issues.

**Comment by Terpo** [comment]
They fixed it already, forgot to close that one.
