### ISSUE TITLE
Really need help with this one

### ISSUE THREAD

**Issue by PSILONCRAFT** [Ivorforce/RecurrentComplex#187]
I am the creator of PROJEC PSILONCRAFTED and i use yor mod. its amazing but since i use 153 mods there are bound to be problems. Im sending you this issue because your mod is one that prints out with a error in my setup. i will send you the server log and hope for a proper answer to the adressing issue

Best regards PSILONCRAFT
[crash-2017-04-30_23.33.02-server.txt](https://github.com/Ivorforce/RecurrentComplex/files/967061/crash-2017-04-30_23.33.02-server.txt)

**Comment by Ivorforce** [comment]
Try redownloading 1.2.10 or waiting for the next version. As far as I can see the bug should not be able to occur anymore.

**Comment by Ivorforce** [comment]
Closing stale issue.
