### ISSUE TITLE
No structure in the /#list on multiplayer 1.11.2

### ISSUE THREAD

**Issue by Ricdan** [Ivorforce/RecurrentComplex#188]
Hi,
I'm building an all new online survival server for me and my friends. We tryed your mod on Solo survival and found it amazing.
I'm now trying to make it work on the server... But unfortunately, no structure appears in the /#list.
I found the issues #63 and #154 but it didn't helped me. I'm wondering if it could be a permission problem and how could i be resolving it, the server being rented at Roxserver.
Here is a part of the fml log : https://pastebin.com/TUwdbqDR
You'll probably need more information, just tell me what you need, i'll do my best to help you (helping me ;) ).

Thanks for your time,

Ricdan

**Comment by Ivorforce** [comment]
Yes, that should definitely be a permission problem - same as #154. If you have trouble setting up your permissions correctly I recommend asking your provider, they might be of help for this :)

**Comment by Ricdan** [comment]
I have to admit, that i don't know which files need to access to which other files... So actually, i don't know what do i have to do to resolve the problem, or what asking to my provider.
There's the ligne saying 
`java.nio.file.AccessDeniedException: E:\UserFiles\ERICD2\GameServers\TC85316533370680442515586\Minecraft\minecraft_server.1.11.2.jar`
and it goes on for each of the mods installed on the server : 
`[19:47:45] [Server thread/ERROR] [reccomplex/reccomplex]: Error reading from resource location 'baubles:'
java.nio.file.AccessDeniedException: E:\UserFiles\ERICD2\GameServers\TC85316533370680442515586\Minecraft\mods\Baubles-1.11-1.4.3.jar`

So, does the RecurrentComplex-1.2.10.jar file need more permissions ?

**Comment by Ivorforce** [comment]
Recurrent Complex needs the user that starts the Java application, or rather the application itself to have read access for the server jar and each of the mod jars.

**Comment by Ricdan** [comment]
So, Roxserve doesn't provide the tools to give the needed permissions for Recurrent Complex to work.
Too bad, i liked your mod a lot.
We are moving to ruins.
Thanks again for your great work and your time.
