### ISSUE TITLE
Crash with Biomes O' Plenty

### ISSUE THREAD

**Issue by BrisingrAerowing** [Ivorforce/RecurrentComplex#191]
[Crash Log](https://gist.github.com/BrisingrAerowing/aaf3d9354bbf75fca855c3baa6f83353)

It seems that this mod tried to get a property from a block that didn't support said property.

RecComplex: 1.3
MC: 1.10.2

**Comment by Hypsellis** [comment]
Same crash with last version on 1.11.2

**Comment by miuirussia** [comment]
confirm it

**Comment by MadByteDE** [comment]
Crashes for me too. FML log says this:
[FML log error](https://gist.github.com/MadByteDE/84c4a1f21e77c87b68775a2941a09e5f)
And the server log says this:
[Server log error](https://gist.github.com/MadByteDE/f4c46cf88ee3ca488df938052c23d0d2)

**Comment by ohois** [comment]
Same here
Minecraft 1.10.2
Forge: 12.18.3.2281
RecurrentComplex: 1.3
IvToolkit: 1.3.3
BoP: 5.0.0.2162

[Exception that triggered the crash](https://gist.github.com/ohois/bd7c574d7d20230de5ea697b95879e8b)

**Comment by Ivorforce** [comment]
Lots of testing later, I think I got all of the remaining generation bugs too. There were more than I'd like to admit, haha.

Let me know if I forgot anything.

[RecurrentComplex-1.3.1.1-1.10.jar.zip](https://github.com/Ivorforce/RecurrentComplex/files/1005062/RecurrentComplex-1.3.1.1-1.10.jar.zip)
