### ISSUE TITLE
[1.3.1] Village Structures are cut off at chunk +8

### ISSUE THREAD

**Issue by miuirussia** [Ivorforce/RecurrentComplex#197]
![2017-05-08_18 33 14](https://cloud.githubusercontent.com/assets/1270028/25809096/b8d264e8-3414-11e7-93df-12c7c8bfbdeb.png)
![2017-05-08_18 33 46](https://cloud.githubusercontent.com/assets/1270028/25809114/bf7478b8-3414-11e7-983b-6c62f9c2b71b.png)

Maybe because bc9c03bc4838389ffdd614a3f35cdd8d3e644684 working not as expected

**Comment by BrisingrAerowing** [comment]
I am seeing this too. Quite annoying.

**Comment by Darkosto** [comment]
I'm seeing this, too. But more importantly (I'm currently testing) I think structures outside of villages are not spawning at all.

**Comment by Scratchman** [comment]
I'm seeing structures generate outside of villages, but not many. I'm definitely seeing the brokeness in villages, seems to happen more to the structures I've added to the /structures/active folder.

Thanks for the great mod :)

**Comment by BrisingrAerowing** [comment]
@miuirussia I did a custom build with that commit reverted and the issue has vanished, so that commit is indeed the problem here.

I don't thing @Ivorforce would like it if I redistributed the binary, but I will gist the patch I used.

Apply the patch with `git apply --reverse fix-rc-issue-197.patch`

[Here's the patch itself](https://gist.github.com/BrisingrAerowing/105a3e90d7159214955eb3fcaec10c95)

**Comment by chland** [comment]
This **might** be related as its probably caused by the same underlying problem: I'm currently playing around with a custom modpack that uses the latest Biome Bundle + OpenTerrainGenerator and I tested the last 3 RC-versions in combination with it (1.2.10, 1.3, 1.3.1) and villages were totally messed up. Most of the RC-structures only generated partially and even some vanilla-structures were broken. The same happened for a lot of structures outside of villages. Stuff like that huge mayan-style pyramid only generated half.

**Comment by sweetsosweet** [comment]
I'm having this problem too, with or without OpenTerrainGenerator.

**Comment by kragnoth** [comment]
structures inside of villages seem to break at chunk line +8

**Comment by Ivorforce** [comment]
Didn't mean to close automatically, but I did find a big issue.

Here's a patched jar:
[RecurrentComplex-1.3.1.jar.zip](https://github.com/Ivorforce/RecurrentComplex/files/1001752/RecurrentComplex-1.3.1.jar.zip)

Let me know if this one works. Otherwise I'll reopen this issue.

**Comment by miuirussia** [comment]
For 1.10.2?

**Comment by Ivorforce** [comment]
1.11

**Comment by miuirussia** [comment]
If I build for 1.10.2 with three latest commits, is source code will be same?

**Comment by Ivorforce** [comment]
If you switch to branch 1.10 and cherry pick the commits, yes - though i will do that soon myself if nobody here is on 1.11 anyway.

**Comment by Scratchman** [comment]
Thanks for the fix Ivorforce.

I'd need a version for 1.10.2.

**Comment by Ivorforce** [comment]
Here's a 1.10 build then: 

[RecurrentComplex-1.3.1.1-1.10.jar.zip](https://github.com/Ivorforce/RecurrentComplex/files/1003578/RecurrentComplex-1.3.1.1-1.10.jar.zip)

**Comment by miuirussia** [comment]
Tested, working normally

**Comment by Ivorforce** [comment]
Cool, release is on the way.

**Comment by chland** [comment]
Did some quick tests as I don't have much time: looked fine on a 1.10.2 Testworld with BoP-terraingen but was still broken on a BiomeBundle/OTG-world. Unfortunatly I don't have time to do more tests right now but will do some additional tests later today.

**Comment by kragnoth** [comment]
Will test this out on 1.11.2, thanks Ivorforce

**Comment by Scratchman** [comment]
Tried out your latest fix,  RecurrentComplex-1.3.1.1-1.10.jar.zip, but I'm still seeing the same brokeness in villages.

http://imgur.com/a/UuD4S

**Comment by Ivorforce** [comment]
That looks like something different entirely. Kind of like a ruins transformer, actually - with the gravity option enabled.

Can you make sure the only buildings affected are from ReC? (#whatisthis). If so, please open this up as a new issue since it's unrelated.

**Comment by miuirussia** [comment]
Crash, when I enter to Nether
[crash-2017-05-17_22.17.59-server.txt](https://github.com/Ivorforce/RecurrentComplex/files/1008723/crash-2017-05-17_22.17.59-server.txt)

**Comment by Ivorforce** [comment]
Can you report that in a new issue, please?

**Comment by miuirussia** [comment]
Ok, https://github.com/Ivorforce/RecurrentComplex/issues/204

**Comment by chland** [comment]
So, I did some tests with a very minimalistic pack based upon RecurrentComplex-1.3.1.1-1.10.jar (basically it only contained "Chunk-Pregenerator", "JourneyMap" and depending on the test Quark, BB+OTG, etc.

Here are the results:

* Biome Bundle / OTG: villages are totally broken
* Quark Realistic Terrain: villages generate "as expected"
* Alternate Terrain Generation: villages generate "as expected"
* Realistic Terrain Generation + Climate Control: villages generate "as expected"

Looks like OTG does "something" that messes up structure-generation in villages pretty badly.

**Comment by Scratchman** [comment]
For those that might still be having some generation problems, I've found there is a conflict between the CustomOreGen mod and the MUON mod. It seems to affect villages but not structures outside of villages.

**Comment by Ivorforce** [comment]
I'd recommend you submit bug reports to OTG, or CustomOreGen and MUON, respectively. This issue should be fixed from ReCs side now, and structures should generate the same as vanilla structures.
