### ISSUE TITLE
[1.10.2] Crash when entering to Nether

### ISSUE THREAD

**Issue by miuirussia** [Ivorforce/RecurrentComplex#204]
Tested with:
https://github.com/Ivorforce/RecurrentComplex/files/1003578/RecurrentComplex-1.3.1.1-1.10.jar.zip

Crash report:
https://github.com/Ivorforce/RecurrentComplex/files/1008723/crash-2017-05-17_22.17.59-server.txt

**Comment by xannor** [comment]
I had the same issue in 1.11.2 when entering the nether the first time. I however was kicked due to extreme worldgen lag so I got ticking world instead of ticking entity.

Crash Report:
https://gist.github.com/xannor/1d269c839411fc5d7a8d631cb4009002
