### ISSUE TITLE
"Extreme" path-"networks" when RC is installed

### ISSUE THREAD

**Issue by chland** [Ivorforce/RecurrentComplex#205]
One thing I noticed when using RC (for quite some time now, and just tested again with the lastes verison on 1.10.2 -> RecurrentComplex-1.3.1.1-1.10.jar) is, that a lot of villages end up with some crazy path-network around them. You'll get a lot of paths leading into the area around the village without any buildings at them. Here is a screenshot of what i mean: http://imgur.com/a/5VOIg (its the same village generated with and without RC installed).

**Comment by Ivorforce** [comment]
I've noticed this too. Do you happen to know if this happens with other mods that add a large amount of village buildings? To me it kind of looks like it's just unbalanced as to how many road pieces are added per building generated...

**Comment by Ivorforce** [comment]
Linking this up to https://github.com/MinecraftForge/MinecraftForge/issues/3918. It might be related, but I'm not 100% sure. I think it may be trying to place some large structure but can never quite get a position where it fits. I will investigate further.

**Comment by chland** [comment]
Unfortunatly, I can't remember ever using a mod that caused similar problems. I played around with Ruins and PlaceMod but if I remember correctly, Ruins doesn't add stuff to villages and PlaceMod only spawned its own villages using its own logic. 

But thanks for looking into it!

**Comment by Ivorforce** [comment]
I added a dirty hack to resolve the issue. Apparently it happens because the village tries to spawn in the structure, which doesn't want to spawn because of the village's biome but the algorithm just thinks it can't find a place to spawn, so it makes more paths to create one.
