### ISSUE TITLE
Buildings are generating incomplete

### ISSUE THREAD

**Issue by 8ong8ong** [Ivorforce/RecurrentComplex#206]
Hi, i am using your mod in a pack that i am making, I am finding a lot structures form the mod spawning not completed. often the building will be cut in half or just a wall or part of the building is spawning. Any help or ideas on this matter would be appreciated,. thanks

**Comment by Ivorforce** [comment]
See #191. Please update to 1.3.1.1. Apparently the bug still exists but only with OTG installed (probably to be fixed on their side).
