### ISSUE TITLE
Dedicated Server Forge Cascading Worldgen Lag

### ISSUE THREAD

**Issue by Konclan** [Ivorforce/RecurrentComplex#208]
The console is outputting errors saying when generating chunks the mod is creating lag and to report it to the mod author

I've been researching into it and found this:
https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/
I hope you fix this as I really love these structures

**Comment by Ivorforce** [comment]
Duplicate of #155.
