### ISSUE TITLE
1.11.2 Generation Crash

### ISSUE THREAD

**Issue by phit** [Ivorforce/RecurrentComplex#209]
I keep seeing this crash every so often, no custom Buildings just stock stuff running in lightweight/minimal mode.

RecurrentComplex-1.3.1.1
http://vpaste.net/MyfBL

**Comment by Eufranio** [comment]
Same. Besides that, the console keeps spamming this: `Skipping BlockEntity with id minecraft:rcspawnscript`

**Comment by Ivorforce** [comment]
Didn't test it but this should fix your problem. Let me know if it's not fixed (in 1.3.1.2).
