### ISSUE TITLE
Typo (?) on the config file?

### ISSUE THREAD

**Issue by xJon** [Ivorforce/RecurrentComplex#21]
I'm looking at the config file generated by the latest version (v0.9.6.2), because I want to see if I can disable structure generation for a specific biome.
I looked and saw at line number 10 _maybe_ what I'm looking for?
>Biomes in which no biomes will spawn at all. This is for biomes that generally don't work well with structures. [default: ]

Did you mean "Biomes in which no structure will spawn at all"? I hope, at least.
Thanks for the support!

**Comment by Ivorforce** [comment]
Yep, that's exactly what this does. It's obsolete in the current nightly / next release (where I use biome expressions instead), but for 0.9.6.2, this is what you want.

**Comment by xJon** [comment]
And it works :+1:

**Comment by xJon** [comment]
I've tested it today again and weirdly enough it doesn't work anymore. I looked at my config file and I saw that the line has changed; now I see on line 9-11 this:
>    S:disabledBiomes <
        Mining Biome
     >
Maybe due to the change it doesn't work anymore? I'm trying to disable structure generation for the Mining Biome.

**Comment by Ivorforce** [comment]
Are you on the nightlies, or 0.9.6.2? I didn't actually change anything for this issue - rather, in the nightlies, this option doesn't exist anymore in the first place (replaced by structureGenerationMatcher).

**Comment by xJon** [comment]
v0.9.6.2, as always. Really weird. Do you have any idea?

**Comment by Ivorforce** [comment]
Try using the GUI rather than editing the text file. Maybe your input is just wrong.

**Comment by xJon** [comment]
Checked, and no, it detects it:
![image](https://cloud.githubusercontent.com/assets/8945347/7610488/f9eb4448-f985-11e4-9210-ea641c6d298f.png)

**Comment by Ivorforce** [comment]
Odd... I've been looking through the commit history, and it's a bit confusing somehow. Does your config happen to include the universalBiomeMatcher + universalDimensionMatcher already? If so, the disabledBiomes option has been removed there already.

**Comment by xJon** [comment]
This is how my current config file looks like: http://pastebin.com/Qn3JeUJq
It indeed has universalBiomeMatcher + universalDimensionMatcher, AND disabledBiomes.

**Comment by Ivorforce** [comment]
FML keeps outdated config options in it, unfortunately (for good reason though). I'll have to see if there's a way to remove them manually. The option, however, is unused with universalBiomeMatcher in place.

**Comment by xJon** [comment]
So I can do this?:
>     # Biome Expression that will be checked for every single structure. Use this if you want to blacklist / whitelist specific biomes that shouldn't have structures. [default: ]
    S:universalBiomeMatcher=Mining Biome

How can I tell it to blacklist and not whitelist?

**Comment by Ivorforce** [comment]
Structure Expressions are already covered on the wiki: http://minecraft-recurrent-complex.wikia.com/wiki/Expression#Structure_Expression.C2.A0
Your expression has two problems:
1) Space - You'll need to escape it (Mining\ Biome)
2) It will match *only* the mining biome now - which is the wrong way round.
I recommend you just get familiar with them - they aren't hard to understand :)

About the change, no clue... That's what I was looking up in the commit history, and not finding an answer for. Oh well, it happens :P

**Comment by xJon** [comment]
@Ivorforce Why wrong way round though? This dimension has only one biome :P
So as I understood I need to set it up like this?
># Biome Expression that will be checked for every single structure. Use this if you want to blacklist / whitelist specific biomes that shouldn't have structures. [default: ]
S:universalBiomeMatcher=!Mining\ Biome

**Comment by Ivorforce** [comment]
Yep, that would be it.

**Comment by xJon** [comment]
And it indeed works. Thanks for the support @Ivorforce!
