### ISSUE TITLE
[1.10] Maze generation can get stuck in an endless loop

### ISSUE THREAD

**Issue by TheBrain0110** [Ivorforce/RecurrentComplex#211]
I'm on the 1.10 branch (v 1.3.1.1, and even tried building the latest commit), and I've had Maze generation go into an endless loop on multiple occasions as well. I've even left the server running overnight, and it's still using 100% CPU and not responding in the morning. I did a CPU sample and it was definitely related to maze generation, but I didn't save exactly what method it was stuck on. I'll try and get another sample later.

Possibly related to #198 ? But taking a long time to finish is somewhat different from *never* finishing...

**Comment by Ivorforce** [comment]
I can't really imagine the algorithm running _forever_. Did you alter the allowed reverses in the config?

**Comment by Ivorforce** [comment]
As of 43d85aa385a59ae0bb00ceb4b826490a1bbbee64, maze generation is now limited to 20s (configurable).  For further performance issues please refer to #198.
