### ISSUE TITLE
I think the chunk partial generation is still a bit broken

### ISSUE THREAD

**Issue by BrisingrAerowing** [Ivorforce/RecurrentComplex#212]
![2017-05-25_16 05 01](https://cloud.githubusercontent.com/assets/250409/26468355/179a8c7e-4164-11e7-8ee8-021efe9fbedc.png)

Yeah.... Not so sure about it working just yet.

This also happens when a building spawns on the border of two or more biomes. Not sure why it happened here, as it is all in a desert.

**Comment by Ivorforce** [comment]
Can you send me the world seed + coords?

**Comment by BrisingrAerowing** [comment]
Seed: 8190482382498953449
I can't remember the coordinates, but Admist shows me (148, -4028). Any village may work, especially if it crosses biome boundaries.

**Comment by cjburkey01** [comment]
You were at -737, -1451

**Comment by Ivorforce** [comment]
Fixed in the latest commits (next release).
