### ISSUE TITLE
[1.10] Latest commit still crashing on multithreaded complementing

### ISSUE THREAD

**Issue by TheBrain0110** [Ivorforce/RecurrentComplex#213]
I was getting a crash during world gen, so I came looking for a new build that might address it. Lucky me, there was a recent commit that looked to do just that:

c7abd829 Fix multithreaded complementing sometimes crashing the game.

There wasn't a release on Curse, but I built my own from source and loaded it on my server.

And then a little while exploring later, I got the exact same crash again:

https://gist.github.com/TheBrain0110/dc30cacf2e4d3b2988b4f3f4eb388194

So, looks like it still needs some work...

**Comment by Ivorforce** [comment]
Yeah, I can see why... It's not multithreading this time but rather chained chunk gen. I'll see how I can fix this.
