### ISSUE TITLE
[1.10.2] [RC 1.3.1.2-1.10] Exception ticking world

### ISSUE THREAD

**Issue by Alaberti** [Ivorforce/RecurrentComplex#215]
https://pastebin.com/LhPNRKfz

Also running Open Terrain Generator v18, Biome Bundle v5 as the world generators if that matters.

**Comment by Ivorforce** [comment]
Do you have lightweight mode enabled?

**Comment by Alaberti** [comment]
Yes

**Comment by Ivorforce** [comment]
Did this happen more than once? And on the latest version still? 
Did the world load after you closed it?
And any way to recreate this? (you could find out what structure was involved by using /#whatisthis and similar)

**Comment by Alaberti** [comment]
Sorry for the delay; no, this issue has not repeated itself in your latest versions.

**Comment by Ivorforce** [comment]
I'm not 100% sure if this fixes all current issues related to this, but it should at least fix most. Let me know if it happens again in 1.4.2+.
