### ISSUE TITLE
RecurrentComplex 1.3.2 - Trees generating with non-decayable leaves

### ISSUE THREAD

**Issue by Dubster94** [Ivorforce/RecurrentComplex#219]
Hello! There are some trees that generate with non-decayable leaves. This one in particular is a spruce tree that generates with a big trunk. Here's a picture showing the issue:

![2017-06-09_12 33 49](https://user-images.githubusercontent.com/28359146/26972043-2d7633e2-4d10-11e7-8f51-2d1da510d5b8.png)

I realize this may have been done in order to bypass the decay rule in order to make more intricate trees, but it gets really messy when you chop one of these trees down and all leaves just stay there.

**Comment by Ivorforce** [comment]
Can you /#whatisthis the tree and tell me what it is? (you might have to enable memorizeDecoration and generate a new tree)

**Comment by Dubster94** [comment]
Um, how do I go about doing that? The /#whatisthis claims there's nothing there when I mouse over the tree.

**Comment by Ivorforce** [comment]
You have to stand right next to the trunk - your pointer is irrelevant. If it still doesn't recognize it you will have to enable memorizeDecoration and find a newly generated one, since this one didn't get memorized.

**Comment by Dubster94** [comment]
Okay, what is the command to memorize decoration? :)

**Comment by Ivorforce** [comment]
It's in the config (Main Menu -> Mods -> Recurrent Complex -> General)

**Comment by Dubster94** [comment]
Okay, all done. The tree in question is called "LodgepolePine".
