### ISSUE TITLE
[1.4-1.10.2] Structures are cut in the middle

### ISSUE THREAD

**Issue by BrisingrAerowing** [Ivorforce/RecurrentComplex#222]
![2017-06-17_10 58 15](https://user-images.githubusercontent.com/250409/27253934-0ddd6522-534c-11e7-8336-08f8ee4fe80c.png)
![2017-06-17_10 58 34](https://user-images.githubusercontent.com/250409/27253935-0de83484-534c-11e7-8109-eebf2b31c10b.png)

This is a bit annoying.

**Comment by lolorz13** [comment]
I too have this issue, on further investigation it seems to be happening on the 8th block in my chunks and it runs on both the z and x axis. In the image below I aligned myself on the z axis slice from the house on the left. (no other mods installed)
![2017-06-18_21 39 07](https://user-images.githubusercontent.com/22108177/27267545-d91243f2-546e-11e7-9beb-da1d1ad40a2c.png)

**Comment by Cakx** [comment]
I have the same issue in 1.11.2 with version 1.4! (frequently seen this problem in one of my selfmade structures)

**Comment by GrumpNugget** [comment]
Also getting Structures cut. on 1.10.2

**Comment by RedlorMC** [comment]
I am also experiencing this issue. Let me know if I can provide any more data to help troubleshoot.

Java:1.8.0_121
MC: 1.11.2
Forge: 13.20.0.2313
Recurrent Complex: 1.4

**Comment by Luke616** [comment]
Confirming that this is happening on MC1.11.2 with ver 1.4, here are more pics confirming that it happens on the 8th block of a chunk and on both axes.

![2017-06-22_16 03 07](https://user-images.githubusercontent.com/3951604/27453836-c1851030-5765-11e7-970e-90218f0a26c6.png)
![2017-06-22_16 03 40](https://user-images.githubusercontent.com/3951604/27453838-c2a5ac68-5765-11e7-8674-79b6630752c8.png)

**Comment by Dune-Jumper** [comment]
I'm getting this too. 1.3.2 seems to be the latest 1.10.2 version that doesn't have this issue.

**Comment by mgwerner** [comment]
1.11.2  Forge 13.20.0.2300  RecurrentComplex-1.4


Same issue

**Comment by Ivorforce** [comment]
1.4.2 is out now with the fix. Let me know if it reappears.

**Comment by mgwerner** [comment]
Got rid of the gaps in the structure when I deleted the region and rentered to load it fresh.  But, this ugliness is still there:

![2017-06-30_02 47 44](https://user-images.githubusercontent.com/12369588/27704901-b2d39104-5d3e-11e7-89aa-1a95901b1ed2.png)

But worse:

![2017-06-30_02 51 37](https://user-images.githubusercontent.com/12369588/27705013-151d5f8e-5d3f-11e7-99f9-676c8d070c1f.png)
![2017-06-30_02 51 27](https://user-images.githubusercontent.com/12369588/27705012-15191c80-5d3f-11e7-95dd-8b292035445c.png)

**Comment by Ivorforce** [comment]
That should be fixed in 1.4.3.1 :)

From the changelog: 
> * If generation and transformer IDs are missing, consistently randomize them across loads. This fixes structures sometimes spawning with negative space blocks in the world

If it still happens there please let me know.

**Comment by mgwerner** [comment]
It is 1.4.3.1, I just updated, deleted the regions, went abck to see how they reloaded, and the screens are what I found.  Restored the old regions and found this again, as it was before the updated release:

![2017-06-27_15 00 29](https://user-images.githubusercontent.com/12369588/27706074-afd6717a-5d42-11e7-8dd0-26729e7eb74a.png)

**Comment by Ivorforce** [comment]
Yes, this will only work for newly generated structures (as in, not only delete the region files, but also the reccomplex-structuredata.dat files).

**Comment by mgwerner** [comment]
Now I get it.  I'll try deleting both when I can play again.  Thanks for your patience.

**Comment by mgwerner** [comment]
I've wandered about the world, both into regions that were deleted and new ones.  No gaps in the structures, and no placeholders or open spaces below ground level.  I would say that, at this point, it is fixed.  Thanks!
