### ISSUE TITLE
Game crashing. Exception StringIndexOutOfBounds

### ISSUE THREAD

**Issue by mimien** [Ivorforce/RecurrentComplex#223]
Been getting these with the newest release, on new world generations on creative while exploring.

[crash-2017-06-16_21.50.34-server.txt](https://github.com/Ivorforce/RecurrentComplex/files/1082834/crash-2017-06-16_21.50.34-server.txt)
[crash-2017-06-16_22.26.36-server.txt](https://github.com/Ivorforce/RecurrentComplex/files/1082835/crash-2017-06-16_22.26.36-server.txt)
[crash-2017-06-17_18.57.11-server.txt](https://github.com/Ivorforce/RecurrentComplex/files/1082836/crash-2017-06-17_18.57.11-server.txt)

Any idea what causes it?

**Comment by xSparky911x** [comment]
I too am getting this crash

https://pastebin.com/ge4mhKeD

**Comment by IncognitoJam** [comment]
https://pastebin.com/itT3uqWt

I also had this issue when players were exploring the world.

**Comment by Jo-Mamma75** [comment]
So @Ivorforce , since you closed this issue does that mean we should expect an update here shortly?

**Comment by Ivorforce** [comment]
Yes, a few hours.

**Comment by Jo-Mamma75** [comment]
Very fine. Thank you. We were trying to determine what we were going to do with FoolCraft in the next update.

**Comment by sandalle** [comment]
I'm also getting this crash on Minecraft 1.11.2 and noticed that there's a new Recurrent Complex release for 1.10 and 1.12, wondering if one will be made for 1.11 as well. ;)

[crash-2017-06-20_22.13.56-server.txt](https://github.com/Ivorforce/RecurrentComplex/files/1090386/crash-2017-06-20_22.13.56-server.txt)

**Comment by scalda** [comment]
All seems to working fine now in the new version you released last night for 1.10.2. thanks for the hard work

scalda
Iskall85 Community Administrator
FoolCraft DevTeam
