### ISSUE TITLE
Export command doesn't seem to import the settings when specifying a specific structure to export

### ISSUE THREAD

**Issue by belathus** [Ivorforce/RecurrentComplex#224]
I'm trying to edit an existing structure. If I am recalling correctly, I use "/#import \<structure name\>" to recreate the structure, edit it as needed, then use "/#export \<structure name\>" to re-save the structure. However, using export, it doesn't copy the parameters of the existing structure, forcing me to recreate those parameters (like the generation settings, the placer, the transformer, etc.).

**Comment by Ivorforce** [comment]
You need to provide /#export with the structure id again. (/#export YourStructure, or /#export --from YourStructure in 1.4

**Comment by belathus** [comment]
The command I entered for modifying the structure was "/#export SpawnTeamScatter" to modify a structure named "SpawnTeamScatter"

**Comment by belathus** [comment]
Oh, wait, I have to use "--from"?

**Comment by Ivorforce** [comment]
In 1.4+, yes.
