### ISSUE TITLE
[1.10.2] Game crashing, Biome Bundle installed?

### ISSUE THREAD

**Issue by ImadethisjustforNVIDIAFleX** [Ivorforce/RecurrentComplex#226]
Idk if this is being caused by RC or BB, but here are the details and the crash report:

Minecraft Version: 1.10.2
Recurrent Complex Version: 1.4-1.10
IvToolkit Version: 1.3.3-1.10
Biome Bundle Version: 1.10.2-v5.1
Open Terrain Generator Version: 1.10.2-v20

---- Minecraft Crash Report -------- Minecraft Crash Report ----
WARNING: coremods are present: IvToolkit (IvToolkit-1.3.3-1.10.jar) SCFMLCorePlugin (StalkerCreepers-1.10.2.jar)Contact their authors BEFORE contacting forge
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]
Time: 6/18/17 3:38 PMDescription: Exception ticking world
java.lang.StringIndexOutOfBoundsException: String index out of range: 345 at java.lang.String.substring(String.java:1950) at ivorius.reccomplex.random.item.Book.bookPages(Book.java:130) at ivorius.reccomplex.random.item.Book.poem(Book.java:46) at ivorius.reccomplex.random.item.Book.any(Book.java:27) at ivorius.reccomplex.item.ItemBookGenerator.generateInInventory(ItemBookGenerator.java:42) at ivorius.reccomplex.world.storage.loot.InventoryGenerationHandler.generateAllTags(InventoryGenerationHandler.java:59) at ivorius.reccomplex.world.storage.loot.InventoryGenerationHandler.generateAllTags(InventoryGenerationHandler.java:72) at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generateTileEntityContents(GenericStructure.java:162) at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.setBlock(GenericStructure.java:147) at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generate(GenericStructure.java:248) at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generate(GenericStructure.java:71) at ivorius.reccomplex.world.gen.feature.StructureGenerator.generate(StructureGenerator.java:195) at ivorius.reccomplex.world.gen.feature.WorldGenStructures.planStructureInChunk(WorldGenStructures.java:120) at ivorius.reccomplex.world.gen.feature.WorldGenStructures.lambda$planStructuresInChunk$793(WorldGenStructures.java:77) at ivorius.reccomplex.world.gen.feature.WorldGenStructures$$Lambda$134/1469541425.accept(Unknown Source) at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) at ivorius.reccomplex.world.gen.feature.WorldGenStructures.planStructuresInChunk(WorldGenStructures.java:77) at ivorius.reccomplex.world.gen.feature.WorldGenStructures.decorate(WorldGenStructures.java:216) at ivorius.reccomplex.events.handlers.RCForgeEventHandler.onPreChunkDecoration(RCForgeEventHandler.java:83) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_9_RCForgeEventHandler_onPreChunkDecoration_Pre.invoke(.dynamic) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) at com.khorn.terraincontrol.forge.events.TCToForgeEventConverter.onPopulateStart(TCToForgeEventConverter.java:104) at com.khorn.terraincontrol.TerrainControlEngine.firePopulationStartEvent(TerrainControlEngine.java:87) at com.khorn.terraincontrol.TerrainControl.firePopulationStartEvent(TerrainControl.java:73) at com.khorn.terraincontrol.generator.ObjectSpawner.populate(ObjectSpawner.java:105) at com.khorn.terraincontrol.forge.generator.TXChunkGenerator.func_185931_b(TXChunkGenerator.java:109) at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000) at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964) at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154) at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126) at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147) at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222) at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) at java.lang.Thread.run(Thread.java:745)
A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- Head --Thread: Server threadStacktrace: at java.lang.String.substring(String.java:1950) at ivorius.reccomplex.random.item.Book.bookPages(Book.java:130) at ivorius.reccomplex.random.item.Book.poem(Book.java:46) at ivorius.reccomplex.random.item.Book.any(Book.java:27) at ivorius.reccomplex.item.ItemBookGenerator.generateInInventory(ItemBookGenerator.java:42) at ivorius.reccomplex.world.storage.loot.InventoryGenerationHandler.generateAllTags(InventoryGenerationHandler.java:59) at ivorius.reccomplex.world.storage.loot.InventoryGenerationHandler.generateAllTags(InventoryGenerationHandler.java:72) at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generateTileEntityContents(GenericStructure.java:162) at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.setBlock(GenericStructure.java:147) at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generate(GenericStructure.java:248) at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generate(GenericStructure.java:71) at ivorius.reccomplex.world.gen.feature.StructureGenerator.generate(StructureGenerator.java:195) at ivorius.reccomplex.world.gen.feature.WorldGenStructures.planStructureInChunk(WorldGenStructures.java:120) at ivorius.reccomplex.world.gen.feature.WorldGenStructures.lambda$planStructuresInChunk$793(WorldGenStructures.java:77) at ivorius.reccomplex.world.gen.feature.WorldGenStructures$$Lambda$134/1469541425.accept(Unknown Source) at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) at ivorius.reccomplex.world.gen.feature.WorldGenStructures.planStructuresInChunk(WorldGenStructures.java:77) at ivorius.reccomplex.world.gen.feature.WorldGenStructures.decorate(WorldGenStructures.java:216) at ivorius.reccomplex.events.handlers.RCForgeEventHandler.onPreChunkDecoration(RCForgeEventHandler.java:83) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_9_RCForgeEventHandler_onPreChunkDecoration_Pre.invoke(.dynamic) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) at com.khorn.terraincontrol.forge.events.TCToForgeEventConverter.onPopulateStart(TCToForgeEventConverter.java:104) at com.khorn.terraincontrol.TerrainControlEngine.firePopulationStartEvent(TerrainControlEngine.java:87) at com.khorn.terraincontrol.TerrainControl.firePopulationStartEvent(TerrainControl.java:73) at com.khorn.terraincontrol.generator.ObjectSpawner.populate(ObjectSpawner.java:105) at com.khorn.terraincontrol.forge.generator.TXChunkGenerator.func_185931_b(TXChunkGenerator.java:109) at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000) at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964) at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154) at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126) at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147) at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
-- Affected level --Details: Level name: Biome Bundle All players: 1 total; [EntityPlayerMP['34ivan43'/986, l='Biome Bundle', x=554.92, y=65.46, z=-42.14]] Chunk stats: ServerChunkCache: 536 Drop: 0 Level seed: -676246042473965393 Level generator: ID 06 - OTG, ver 0. Features enabled: true Level generator options: OpenTerrainGenerator Level spawn location: World: (-128,52,192), Chunk: (at 0,3,0 in -8,12; contains blocks -128,0,192 to -113,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511) Level time: 9742 game time, 9742 day time Level dimension: 0 Level storage version: 0x04ABD - Anvil Level weather: Rain time: 18792 (now: false), thunder time: 17329 (now: false) Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: trueStacktrace: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) at java.lang.Thread.run(Thread.java:745)
-- System Details --Details: Minecraft Version: 1.10.2 Operating System: Windows 8 (amd64) version 6.2 Java Version: 1.8.0_25, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 518087544 bytes (494 MB) / 2052034560 bytes (1956 MB) up to 2134114304 bytes (2035 MB) JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95 FML: MCP 9.32 Powered by Forge 12.18.3.2281 14 mods loaded, 14 mods active States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored UCHIJAAAA mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) UCHIJAAAA FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281.jar) UCHIJAAAA Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281.jar) UCHIJAAAA ivtoolkit{1.3.3-1.10} [IvToolkit] (minecraft.jar) UCHIJAAAA mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) UCHIJAAAA openterraingenerator{v20} [Open Terrain Generator] (OpenTerrainGenerator-1.10.2-v20.jar) UCHIJAAAA biomebundle{5.1} [Biome Bundle] (Biome_Bundle-1.10.2-v5.1.jar) UCHIJAAAA chameleoncreepers{1.4.1} [Chameleon Creepers] (chameleoncreepers-1.4.1-1.10.2.jar) UCHIJAAAA extendedrenderer{v1.0} [Extended Renderer] (coroutil-1.10.2-1.1.16.jar) UCHIJAAAA coroutil{1.10.2-1.1.16} [CoroUtil Library] (coroutil-1.10.2-1.1.16.jar) UCHIJAAAA configmod{v1.0} [Extended Mod Config] (coroutil-1.10.2-1.1.16.jar) UCHIJAAAA reccomplex{1.3.2-1.10} [Recurrent Complex] (RecurrentComplex-1.4-1.10 (1).jar) UCHIJAAAA special_ai{1.1.3} [Special AI] (special_ai-1.10.2-1.1.3.jar) UCHIJAAAA zombieawareness{1.10.2-1.11.7} [Zombie Awareness] (zombieawareness-1.10.2-1.11.7.jar) Loaded coremods (and transformers): IvToolkit (IvToolkit-1.3.3-1.10.jar) SCFMLCorePlugin (StalkerCreepers-1.10.2.jar) atomicstryker.stalkercreepers.common.SCTransformer GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread. Profiler Position: N/A (disabled) Player Count: 1 / 8; [EntityPlayerMP['34ivan43'/986, l='Biome Bundle', x=554.92, y=65.46, z=-42.14]] Type: Integrated Server (map_client.txt) Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by esotericist** [comment]
looks like more of #223 to me.
