### ISSUE TITLE
Random crash relating to the book generator

### ISSUE THREAD

**Issue by Sunconure11** [Ivorforce/RecurrentComplex#228]
https://pastebin.com/keknAa93

But I haven't even touched it on 1.11.2...

**Comment by bogger33** [comment]
I got this too

**Comment by Ivorforce** [comment]
Duplicate of #227.

**Comment by Sunconure11** [comment]
Issue happens for me on 1.11.2, any plans to bring the fix over there?

**Comment by Ivorforce** [comment]
Did I enter it wrong in curse? The releases are for 1.11 and 1.10

Am 21.06.2017 02:56 schrieb "Anonymous" <notifications@github.com>:

**Comment by Sunconure11** [comment]
I see releases for 1.12 and 1.10. I think you did.
