### ISSUE TITLE
"Floaty" structures (Suggestion)

### ISSUE THREAD

**Issue by chland** [Ivorforce/RecurrentComplex#229]
I was wondering if it was possible to make it less likely for (default-)structure to spawn at positions where most of them is floating in the air.

Quite often while exploring my test-worlds i encounter RC-structures that are generated at the side of hills. Unfortunatly, this means that only a small part of them is touching the ground and the rest generates mid-air.

I don't know if this is even possible (because I imagine this could lead to cascading chunk-generation) but I think it could be a good idea to check if the bottom of the bounding box of a structure is touching the ground in most places and abort generation if it isn't. Basically something like this: http://imgur.com/tMYPADO (generation of A would be aborted, B would be generated).

**Comment by chland** [comment]
Oh, I just saw https://github.com/Ivorforce/RecurrentComplex/issues/218 which is basically the same thing.

**Comment by Ivorforce** [comment]
I'll take a look in this thread later too, but I'm closing this to keep discussion to #218.
