### ISSUE TITLE
crash in 1.12_Forge 2340 RC 1.4.1

### ISSUE THREAD

**Issue by JasonKillsUs** [Ivorforce/RecurrentComplex#231]
It seems that Forge had change something essential several mods are crashing, so does this mod:

"https://pastebin.com/QCjwGULs"
thanks for the update to 1.12 anyway :-)

**Comment by P3rf3ctXZer0** [comment]
I can confirm this crash as well!
https://gist.github.com/P3rf3ctXZer0/e59419909de706fd0d4360330ddc630b

**Comment by Ivorforce** [comment]
Did I enter it wrong on curse? ReC isn't updated to 1.12, 1.4.1 is for 1.11

Am 21.06.2017 13:58 schrieb "P3rf3ct_Zer0" <notifications@github.com>:

**Comment by Sunconure11** [comment]
@Ivorforce You did, its currently listed as 1.12 for some reason, when looking at the code alone, it has no support for 1.12.

**Comment by sandalle** [comment]
I mentioned in https://github.com/Ivorforce/RecurrentComplex/issues/223 that there's a 1.4.1 for MC 1.10 and 1.12, but not 1.11 . I thought perhaps 1.11 needed more work and was happy for progress on 1.12. ;)

**Comment by Ivorforce** [comment]
File is properly listed as 1.11 in curse now.
