### ISSUE TITLE
Crashing whilst traversing in the world

### ISSUE THREAD

**Issue by o0Karvanaama0o** [Ivorforce/RecurrentComplex#236]
Not sure if there is a conflict between OTG (OpenTerrainGenerator) and recurrent, i have no idea what its saying to me.

https://pastebin.com/5Uv05xW7

**Comment by Ivorforce** [comment]
Please update to 1.4.1

Am 24.06.2017 08:59 schrieb "o0Karvanaama0o" <notifications@github.com>:

**Comment by o0Karvanaama0o** [comment]
Can confirm working. Thank you sir for all your hard work.
