### ISSUE TITLE
Transformers don't apply in structures sometimes after a crash

### ISSUE THREAD

**Issue by mgwerner** [Ivorforce/RecurrentComplex#237]
1.11.2 Forge 13.20.0.2300 RecurrentComplex-1.4

Region was deleted and reloaded.

![2017-06-24_21 02 30](https://user-images.githubusercontent.com/12369588/27509037-0fdd939e-5926-11e7-872a-0eb7f2aa282f.png)

**Comment by Ivorforce** [comment]
Did it generate properly after the region was regenerated?

Am 24.06.2017 15:42 schrieb "mgwerner" <notifications@github.com>:

**Comment by mgwerner** [comment]
It did not, I tried deleting the region twice.  Same issue.

However, I started a new world with the same seed and the structure is there, without the space blocks.

**Comment by teutates1989** [comment]
Not sure if it should have it's own issue but i had a similar problem.
my saved crashed because of the recursive mod chunk loading and when reloading the save i had this (see screenshot below) 
Version:  RecurrentComplex-1.4.1.jar
with other crashes i have not being able to recreate the appearance of those blocks 
![2017-06-23_21 27 59](https://user-images.githubusercontent.com/11924154/27509450-795005e2-58fd-11e7-92f5-221b10855a1b.png)

**Comment by mgwerner** [comment]
I probably should have mentioned that the reason I deleted the region was that I had the region rendering crash and was unable to get the save to load.  It was a new world, so deleting and restarting was not a problem.

**Comment by mgwerner** [comment]
New world, no regions deleted, but there was a chunk rendering crash (reported in another thread on this site).  This is just ugly:

![2017-06-27_15 00 29](https://user-images.githubusercontent.com/12369588/27574565-8be61d10-5b49-11e7-9d36-8070a5130ad1.png)

**Comment by Ivorforce** [comment]
I was not able to reproduce this yet by deleting region files. It seems to me the structure instance saves improperly without saving its transformers. Can you send me the reccomplex-structuredata.dat file for one of these saves (and the coordinates for the affected structure)?

**Comment by Ivorforce** [comment]
I think I tracked the problem down. Let me know if this happens in 1.4.3.1 forward.

**Comment by aelfwyne** [comment]
This appears to be the same problem i was having which I had to resolve by deleting the DAT files as well as the region files.

Hope it's fixed in the new version.
