### ISSUE TITLE
Missing Inventory Generator

### ISSUE THREAD

**Issue by ulkunderscore** [Ivorforce/RecurrentComplex#238]
I filled a custom Inventory Generation Component Tag, but I can't find a custom Inventory Generation Tag to put it into.
Versions: MC 1.11.2, RC 1.4, IvToolkit 1.3.3

**Comment by Ivorforce** [comment]
Did you enter a group id? Can you screenshot your inventory generator's gui screens?

**Comment by ulkunderscore** [comment]
I tried again and now there is one. It must have been the restart or maybe I missed the ID like you said. Thanks for the help.

**Comment by Ivorforce** [comment]
I hope it's not some kind of creative menu caching. That would be a problem for inventory generation tags in general. I'll check it out either way.
