### ISSUE TITLE
[1.11.2][1.4] Crash while generating some new chunks.

### ISSUE THREAD

**Issue by Rosethorns** [Ivorforce/RecurrentComplex#239]
This has happened twice so far and is not easily testable other than to wander about until it happens.

But the client crashes with a out of range error. Pastebin follows.
https://pastebin.com/RZnRgh12

**Comment by seulil** [comment]
same here. crash when generating terain/exploring

**Comment by maham** [comment]
Same here. Seems like it have something to do with the poetry books.

**Comment by kreezxil** [comment]
Confirmed:

server crash report: https://gist.github.com/a00f183a1aa86ee3d3394f7af12e5837
server fml log: https://gist.github.com/d0ed8ec23892fe35cfb340f0a0044713

**Comment by seulil** [comment]
I manage to bypass this by editimg cfg. Somethng with poetry book chance was 0.0...chamged to 1.0 fixes crashes. Dunno what exactly that optiom do...but works for me now 😂

**Comment by mgwerner** [comment]
Happens over and over, whether walking, boating or flying.  Happens more often the fast I am moving across the map. Here are the logs.

[crash-2017-06-27_13.51.56-server.txt](https://github.com/Ivorforce/RecurrentComplex/files/1104290/crash-2017-06-27_13.51.56-server.txt)

[2017-06-26-7.log.gz](https://github.com/Ivorforce/RecurrentComplex/files/1104292/2017-06-26-7.log.gz)

**Comment by Ivorforce** [comment]
Please update to 1.4.1. The version's pretty stable - the only bug left there is #222 afaik, which I will upload a fix for today or tomorrow.
