### ISSUE TITLE
/#replace command seems disfunctional 

### ISSUE THREAD

**Issue by Titus-Armillius** [Ivorforce/RecurrentComplex#241]
I tried /#replace minecraft:air 0 minecraft:dirt & #0 , but unfortunately this did not work, so I guess this command change din the latest update.

Could you indicate/update the wiki to show the new commands?

**Comment by Ivorforce** [comment]
The wiki has been updated to document the new command changes, mostly. I recommend using /help #replace to view how it's used now (iirc it would be /#replace air dirt & #0)
