### ISSUE TITLE
[1.12][v1.4.3] Fatal errors during world load

### ISSUE THREAD

**Issue by starg09** [Ivorforce/RecurrentComplex#245]
Client stucks at the "Building Terrain" screen, and the launcher log [outputs this error](https://gist.github.com/starg09/1620e786d0b3cfb147630512e2d17d5f) (only appears on the event log, not on the log file). Only thing that can be done at that point is force-kill the java process.

Versions used:

* MC 1.12
* Forge 2387 (RB)
* IvToolkit 1.3.3
* RecComplex 1.4.3

**Comment by starg09** [comment]
(Updated the gist to one with only IVToolkit and RecComplex, since it seems to happen even with the two them alone)

**Comment by Ivorforce** [comment]
Duplicate of #224.

**Comment by starg09** [comment]
Ahh, took a bit to submit and didn't notice that one... Sorry! :P

**Comment by Ivorforce** [comment]
No problem, I'm glad it gets reported in the first place :)
