### ISSUE TITLE
[bug] 1.4.3.1 fences are back on trees!

### ISSUE THREAD

**Issue by kreezxil** [Ivorforce/RecurrentComplex#246]
in issue #96, fences appeared on some trees. they are now appearing again on acacia trees.

![image](https://user-images.githubusercontent.com/3880072/27756474-5625ec52-5dbd-11e7-9aab-7e3a5ffbecc9.png)

**Comment by Ivorforce** [comment]
It's a design choice that was made by the author of the trees, not a bug. If you don't like them you can always run 
    /#map SomeTree #fill air fence
to remove them from the structure.

**Comment by kreezxil** [comment]
So you're saying the vanilla acacia tree uses fences in it's model but
they're taken out in the final render?

**Comment by Ivorforce** [comment]
If I recall correctly, fences have always been on those trees.

**Comment by QuImUfu** [comment]
@kreezxil I think you are misunderstanding this. The tree is a user made structure included in Recurrent Complex (there are quite a lot of new structures and variants of trees included in RC) and spawned as variant of the vanilla acacia tree. If you dislike it you can edit the structure to spawn without the fences with the commands Ivorforce mentioned.
