### ISSUE TITLE
Crash during Server Boot after Upgrading 132->1432

### ISSUE THREAD

**Issue by aelfwyne** [Ivorforce/RecurrentComplex#247]
Was running 132 version on 1.11.2 MC. 

Upgraded server to 1432 version, and server crashes during bootup while executing Rec Complex init. 

Pastebin below:
https://pastebin.com/AYzsPHrM

**Comment by Ivorforce** [comment]
1.4.3.2 is, as listed on curse, for MC 1.12. 1.4.3.1 is the same for MC 1.11.

**Comment by aelfwyne** [comment]
Thanks for the update... 

Are you sure the version checking is correct then? Because I don't think I was getting the "wrong version" error that I would normally get, but rather other errors.

As far as having the wrong version - that actually happened with several others yesterday. I think there's a glitch on Curse that downloads the wrong one sometimes. I actually watched one twice in a row when I clicked on the 1.11 version actually downloaded the 1.12 instead. First time I thought I misclicked, second time I actually *watched* it download the wrong file. Several downloaded the 1.10 versions when I clicked on the 1.11.... of course none of that is anything you can fix. But likely how I ended up with the wrong version.

**Comment by Ivorforce** [comment]
I'd report that to curse maybe. ReC doesn't have an internal MC version check - which I should maybe change some time.
