### ISSUE TITLE
Villages no longer spawning

### ISSUE THREAD

**Issue by mgwerner** [Ivorforce/RecurrentComplex#248]
After last update to 1.4.3.1, deleted regions and .dat file as instructed, now there are structures from this mod, but no villages, either in the chunks where they were prior to deleting regions, or in any other chunks I can find.  I have explored a lot, and the villages were close together and some huge (using Improved Villagers mod), but now there are none.

**Comment by Ivorforce** [comment]
Village generation is triggered by vanilla. It's possible that it doesn't handle deleting region files well. If this is a one-time problem, I recommend using /#vanilla gen Village to spawn your villages back in manually.
