### ISSUE TITLE
[crash] 1.4.4-1.11 crashes dedicated server Forge 1.11.2 build 2393

### ISSUE THREAD

**Issue by kreezxil** [Ivorforce/RecurrentComplex#252]
Notes:
     on startup with corrupted registry, server loads fine when mod is removed, for now i'll roll back to previous version of mod

crash report:
https://gist.github.com/92e53200787996b03236cb904fd3c3c8

fml server latest:
https://gist.github.com/1c31ffc39405419f31487a944ac1331f

**Comment by kreezxil** [comment]
Sorry, this isn't you at all.

**Comment by VallenFrostweaver** [comment]
Who was it and can you direct me? I'm having the same crash
