### ISSUE TITLE
Cascading worldgen lag

### ISSUE THREAD

**Issue by lolorz13** [Ivorforce/RecurrentComplex#254]
Recurrent complex 1.44 (latest) for 1.11.2
Noticeable freezes ingame for 20 seconds+ near the end with an unmodified RC install it says that it cannot find a fitting component as well for mazes (possibly related?)
[latest.log.txt](https://github.com/Ivorforce/RecurrentComplex/files/1142640/latest.log.txt)

**Comment by lolorz13** [comment]
Outdated java, update seems to have fixed the issue

**Comment by Ivorforce** [comment]
Updating java might improve performance, but it doesn't solve either problem. For the cascading lag, please refer to #155. For maze generation lag, #198. Cascading lag will usually be limited to < 1s lag spikes, maze generation can sometimes take quite a while though. I'm always working on improving performance there.
