### ISSUE TITLE
Mystcraft and RecurrentComplex compat

### ISSUE THREAD

**Issue by kragnoth** [Ivorforce/RecurrentComplex#255]
Recurrent complex currently tries to generate content in the dimension that Mystcraft uses for profiling blocks for instability.

https://github.com/XCompWiz/Mystcraft-Issues/issues/182

Could the mystcraft-test dimension be blacklisted by default if present, to prevent a default installation of both from conflicting?  I removed recurrent complex, and then blacklisted the dimension for generation, and generation of the profiling went from 3 hours to 30 minutes.

**Comment by Ivorforce** [comment]
Since generations can easily change IDs, I do not intend on blacklisting any by default - it will just cause random compatibility if the mod or people in the config change anything. I recommend using the dimension dictionary from their side.

**Comment by dev-clavis** [comment]
What is the dimension dictionary
