### ISSUE TITLE
[1.11.2] Scriptblock command  "/summon"  summons two mobs instead of one!

### ISSUE THREAD

**Issue by Cakx** [Ivorforce/RecurrentComplex#256]
Hey There! I created a custom archer tower and placed a scriptblock on top of it, which has a simple summon skeleton command.
 
Thats my command:

/summon skeleton ~ ~ ~ {ArmorItems:[{id:leather_boots,Count:1b},{id:leather_leggings,Count:1b},{id:leather_chestplate,Count:1b},{id:leather_helmet,Count:1b}],HandItems:[{id:bow,Count:1b},{id:arrow,Count:8b}],HandDropChances:[0.085F,0.7F],Attributes:[{Name:generic.maxHealth,Base:40}],Health:40.0f,PersistenceRequired:1,LeftHanded:1}

Its just a skeleton with leather armor and equipment.

If i do /#copy /#paste with my tower in my structure design world - everything is fine, just one skeleton spawns.

If i do /#gen myTower - everything is fine, just one skeleton spawns!

However, when i load a new world (survival or creative) to find my new archer tower naturally generated in the world, it always generates with two summoned skeletons at the same position. Unfortunatly that's a critical problem in my modpack development as the skeletons usally hit themselfes which makes them useless. 

**Edit:**

I also tested it with simpler commands and in Minecraft 1.12:

/summon Zombie ~ ~ ~ {PersistenceRequired:1}

Results in two spawned Zombies during world gen.

I used this version:
RecurrentComplex-1.4.4-1.11

and also tried:
RecurrentComplex-1.4.3.3

**Comment by Skoteh90** [comment]
So I'm having an issue very similar to yours. Only during the world gen, my buildings (I think) sometimes double spawn on top of themselves. Resulting in double the mobs, and any chest will destroy the previous chest dropping the items contained within, so double items.

All the blocks are replaced so the structure looks fine, but any entity/item is now doubled.

Minecraft version: 1.11.2
Forge version: 1.11.2-13.20.1.2386

I've used both versions,
RecurrentComplex-1.4.4-1.11.jar
RecurrentComplex-1.4.3.1.jar
