### ISSUE TITLE
Inventory tag causing crash 

### ISSUE THREAD

**Issue by darkshadow543** [Ivorforce/RecurrentComplex#257]
I added botania items into a new tag and when I went to save, it crashed the game.  During that time, I also deleted some of the items in my inventory.  Here is the crash report, and it appears to be client side.
[crash-2017-07-30_14.45.04-client.txt](https://github.com/Ivorforce/RecurrentComplex/files/1185914/crash-2017-07-30_14.45.04-client.txt)

**Comment by Ivorforce** [comment]
Hrm... Looks like your tag contains too much information. I didn't know that was (realistically) possible...
Are you using a large amount of items, or items with a large amount of data or something?

**Comment by darkshadow543** [comment]
Items from botania, some Items, such as mana/terrasteeel armor and rings may contain a lot of data.

**Comment by darkshadow543** [comment]
Pack I was working on is no longer in use. Nor was ever uploaded.
