### ISSUE TITLE
cannot change spawn type from decoration

### ISSUE THREAD

**Issue by TandJ21** [Ivorforce/RecurrentComplex#258]
im trying to make my custom structure be a rare spawn but its stuck on decoration and i cannot change it as its blacked out and locked.

the mod version im on is 1.4.4 for minecraft 1.10.2
if i have done something wrong in the exporting of the structure i need to know as i have asked modpack makers i know and mod devs and no one seems to know whats going on or how to fix it
![2017-07-30_19 59 46](https://user-images.githubusercontent.com/29962329/28756815-cd43e826-756d-11e7-9937-b095ef92e166.png)

**Comment by Ivorforce** [comment]
This looks like it isn't reading the rcnc files. Try running /#sanity and seeing if that complains about anything.

**Comment by Ivorforce** [comment]
Closing stale issue.
