### ISSUE TITLE
[1.11.2 - version 1.4.4] Server crashing and won't start without crash

### ISSUE THREAD

**Issue by VallenFrostweaver** [Ivorforce/RecurrentComplex#259]
Not really sure where to begin with this one as I've not experienced something like this before. Here's the pastebin crash report: https://pastebin.com/N7rGj1PD

**Comment by Ivorforce** [comment]
java.lang.Errors are usually Java-internal problems. I have no idea how this might be caused, so I'd just close this issue for now and hope it doesn't come back. If it does, please reopen the issue :)
