### ISSUE TITLE
Item Frames and structure rotation

### ISSUE THREAD

**Issue by Thutmose** [Ivorforce/RecurrentComplex#26]
Items frames will drop if the structure is rotated and generated

**Comment by Ivorforce** [comment]
Cannot reproduce. Can you provide some reliable setup?

**Comment by Thutmose** [comment]
here is an example, the highlighted thing is what I copied, the pasted one closest to me has the frame in the wrong spot (same block, wrong face).

![image](https://cloud.githubusercontent.com/assets/2363472/10004329/2cc223b8-607f-11e5-893f-ece375b83a37.png)

**Comment by Thutmose** [comment]
here is another example, with a few extra frames, and some more rotations:

![image](https://cloud.githubusercontent.com/assets/2363472/10004534/3303f3fe-6080-11e5-9135-07d1693bc6c5.png)

**Comment by Ivorforce** [comment]
Fixed in the newest IvToolkit nightly.
