### ISSUE TITLE
Server crash when generating world #1

### ISSUE THREAD

**Issue by davqvist** [Ivorforce/RecurrentComplex#261]
MC 1.12
Forge 2426
RC 1.4.4

https://pastebin.com/XRjANHwp

We were exploring in the overworld on the server when the server crashed, can't really provide more info unfortunately.

**Comment by Ivorforce** [comment]
java.lang.Errors are usually problems with the Java version itself. Try updating and just hope that it doesn't happen again. If it does happen regularly, please report back and I'll try to make a workaround :)
