### ISSUE TITLE
How to disable loot gen in mod?

### ISSUE THREAD

**Issue by swingguy0** [Ivorforce/RecurrentComplex#266]
Hello, I love the mod so far, but don't want any loot to generate in chests at all because this unbalances the game for me. How can I change the settings in my game to prevent loot from generating in chests?

I found this setting in the file but am unsure of what to set it to in hopes of getting the above result:

    # Resource Expression that will be applied to each loading inventory generator, determining if it should be set to 'active'. [default: ]
    S:inventoryGeneratorGenerationMatcher=

**Comment by Ivorforce** [comment]
That is just for loading inventory generators. Theoretically you can disable all loot by setting it to false, but then you'll also disable 'loot' that is not meant as loot and more for decorational items in chests.

If you want to be more specific I'd recommend instead editing the individual generators by right clicking the component items and sorting out what items unbalance your setup.
