### ISSUE TITLE
String too long for VM (OutOfMemoryError)

### ISSUE THREAD

**Issue by Nexusdog** [Ivorforce/RecurrentComplex#267]
I've spoken to the author of the Dungeons 2 mod about this issue, but he's pointed me in your direction. Apologies if this is wasting your time, if it's not RC.

https://pastebin.com/D3ajWrPr

**Comment by Nexusdog** [comment]
Um.. I have no idea. I've been getting this bug where I can't place blocks, trees, whatever. I think it's also related to Cyclic 1.7.8 but I can't narrow it down specifically - it seems a combination of several mods is causing this weirdness.

**Comment by Ivorforce** [comment]
It looks more like your VM settings are off in general. Perhaps it's got something to do with the launcher? Any update on this?

**Comment by BrisingrAerowing** [comment]
I've gotten this several times with various combinations of mods. It seems to be completely random as to when it occurs. I'm thinking that sometimes the poem generator fails to set an exit condition, and just keeps looping and chewing up RAM while generating a poem.
