### ISSUE TITLE
1.12.1: "loading a chunk during chunk population and causing chunk loading lag cascade" log messages

### ISSUE THREAD

**Issue by Darkmega18** [Ivorforce/RecurrentComplex#268]
Just reporting that your mod seems to be spamming the console full of these messages during world gen which is making it take a while:

[B#349]  [20:08:59] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk (253, 237  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  [20:09:00] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk (251, 237  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  [20:09:00] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk (251, 238  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  [20:09:01] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk (250, 238  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[B#349]  [20:09:01] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk (250, 240  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

had to report a similar but also massive amount of dumping from lost thaumaturgy too. :V

**Comment by Darkmega18** [comment]
Ah, I see this has been seen before. but yes, just saying. I from the other things I think I understand what problem it's causing now. so I probably got the rough end of the stick and it was this and a couple of other mods also spitting these which caused my world to generate all the way to buggery (it was generating out into the 3000s and 4000 ranges in some cases cause of the cascades), so um... yeah, seems like problem. D:

**Comment by chrisisonwildcode** [comment]
[12:44:44] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk (-82, -49  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.


This would suggest that Recurrent Complex loading a chunk during a chunk population is a bad thing for forge. Maybe explore when chunk loading is happening?

**Comment by Ivorforce** [comment]
See #155 for this. (duplicate)

Remember that the problem isn't as critical as the logs may have you think - it will mostly become a bigger problem once many mods do the same, resulting in world generation lag. Recurrent Complex does have an issue with it (that I will address) but it's not enough to cause big trouble on its own.

**Comment by cyberpwnn** [comment]
It actually is, You put enough players into a spread out world (triggering more chunks to generate) giving a higher chances for something in your mod to generate (larger than a specific chunk). More cascading always creates more cascading, it spreads spatially, and having more areas generated at a time causes more chances for it to peg the main thread until forge kills it after 60 seconds. 

I understand the pains of genning without causing cascading, but it is a real problem.
