### ISSUE TITLE
[1.10.2-1.4.5] Script blocks redstone activation not usable in structures

### ISSUE THREAD

**Issue by thephoenixlodge** [Ivorforce/RecurrentComplex#269]
If a Script block is allowed to trigger on spawn, it works fine, but if set to only trigger on redstone, it still removes itself instantly when the structure it's in generates, so it never gets a chance to be activated. 

As such, my plans for spawning a substructure under certain conditions cannot work, since these script blocks are (as far as I can tell) the only way to spawn structures automatically other than worldgen, since the /#gen command requires the /#confirm followup so cannot be used to gen structures in regular command blocks.

EDIT: Okay, I stand corrected, /#gen works in command blocks, but I can't set the relative y level that way, it just uses the placement from the structure it's genning, which voids its usefulness when I'm trying to gen a basement under a building

**Comment by Ivorforce** [comment]
Hrm... Why do you want to generate a basement while the player is still playing? As part of some kind of progression? If you can describe your exact setup I might be able to either help you or create a new solution for this :)

I do have this planned - as in, that script blocks can stay and be redstone-activated at runtime. It requires some reformatting though and as such I haven't done it yet.

As a workaround, using /#import might work for you. With this command you can set the y value - just note that it would mean your structure would be imported as-is.

**Comment by thephoenixlodge** [comment]
The general gist is that the player does a quest with Custom NPCs, upon completion of which a scoreboard tag gets added to their player data which lets the basement spawn as the area for the followup quest. @Mordenkainen put together a fix for me already and as far as I was aware was going to make a pull request with it.

**Comment by Mordenkainen** [comment]
Pull request submitted... Ignore the first one... Typos and all that.

**Comment by Ivorforce** [comment]
Closing as the PR was resolved.
