### ISSUE TITLE
FML log: canceled generation

### ISSUE THREAD

**Issue by MinecraftPlaye** [Ivorforce/RecurrentComplex#271]
Could an option be added to stop the FML log from beeing spammed with those messages:

> Generated structure 'StonePlantMound' in StructureBoundingBox{x0=370, y0=67, z0=-80, x1=375, y1=77, z1=-75} (0)
> [23:06:17] [Server thread/TRACE] [reccomplex/]: GenericTree2 canceled generation at BlockPos{x=357, y=66, z=-36} (0) (failed to place)

My FML log is full of these messages for a few hundred lines until (2 minutes server time) until other stuff was logged.

Minecraft 1.11.2
Forge Mod Loader version 13.20.1.2454
reccomplex(Recurrent Complex:1.4.5-1.11): RecurrentComplex-1.4.5-1.11.jar

**Comment by Ivorforce** [comment]
There _is_ an option for this: if you set failingStructureLogExpression to "false", it won't log any of these.

If there are really hundreds of these though I'd check if your setup makes sense the way it is. If they always fail to spawn perhaps it would be more useful to deactivate or tweak them, as them always trying to spawn can reduce performance.
