### ISSUE TITLE
Server crashed while generating chunks. [HUGE crash log]

### ISSUE THREAD

**Issue by Croxalicious** [Ivorforce/RecurrentComplex#273]
Our server crashed while exploring and generating chunks and spit this crash log out.
[https://pastebin.com/nwDHj4y5](url)

I've been scouring it up and down for an hour and can't make heads or tails of what could be wrong.
I only assume it's RecComplex related due to it happening during chunk generation and repeated references to the mod in the log.

Sorry for posting this here if it's not related.
Thanks in advance.

**Comment by Ivorforce** [comment]
A java.lang.Error is usually more or less random and cannot really be avoided. Try seeing if you can update your JVM and just hope it won't happen again - if it does please reopen the issue.
