### ISSUE TITLE
[1.12.2]While Reccurent Complex generating strutures it's cascading with worldgen and causes lags

### ISSUE THREAD

**Issue by Foxgreat** [Ivorforce/RecurrentComplex#279]
While Mod tries to generate their structures it sends to console warn "Worldgen cascading constructions"

Also many times i see such constructions in world.
[Weird construction generation](http://prntscr.com/gqmppu)

Sometimes if i loaded new chunks with my friend it causes a crash of server.
[My crash report](https://cdn.discordapp.com/attachments/347030426520649729/362650136817696770/crash-2017-09-27_17.18.34-server.txt)

Server memory 1-2gb 
Forge 14.23.0.2491
Reccurent Complex 1.4.5.1
Minecraft 1.12.2

**Comment by Ivorforce** [comment]
For the cascading chunk problem, see #155. It's a bug, but it's not critical for anything.

I don't recognize the structure. Could you go inside and run /#whatisthis? It's possible it was just saved as-is (with the strong borders).

The crash report is a java error - so a problem with the java distribution itself. Try updating your JVM. It _really_ shouldn't occur often though. If it does, please open a new issue for it.
