### ISSUE TITLE
The GUI is so difficult

### ISSUE THREAD

**Issue by Autopoietico** [Ivorforce/RecurrentComplex#280]
I'm trying to replicate the fallen trees that appear in the Minecraft Bedrock edition, but I couldn't do it with the structure editor, I tried to use the default "vanilla decoration" option, because it looked perfect, but the fallen logs appear on the water, and there's no option to avoid it.
![fallen_logs](https://user-images.githubusercontent.com/8708366/31158111-fa0c0aec-a884-11e7-973f-c0b6cd6c281c.jpg)
So I try to use the "natural" generation option, using the default option of "generate on the surface", but this option makes it extremely rare or almost impossible for fallen trees to appear, playing with the options I have only managed to make them appear on the sky, but not naturally on a flat grass floor.
![2017-10-03_22 07 33](https://user-images.githubusercontent.com/8708366/31158431-54427ac6-a887-11e7-8d1b-494ba29dbb28.png)
There's an easy way to program something like that? I don't think the generator doesn't have simple options for this...

**Comment by Ivorforce** [comment]
Depending on how you want these to spawn, I'd recommend either of the two generation options you've tried.

Vanilla decoration means it replaces some of the other trees, natural generation means it spawns in place of other structures.

To prevent them from spawning in water, I recommend looking at how _I_ did it with the trees themselves: They have natural blocks below each block touching the floor that has an ensure transformer (sustains.trees), as well as one for all other blocks (is:air | is:leaves | is:replaceable). The easiest approach for you would be to simply include natural floor blocks below all your logs and use the tree transformer preset :)

**Comment by Autopoietico** [comment]
I'm gonna try again, I hope I don't rage so much, thanks!!!
