### ISSUE TITLE
Feature Request ? Replace Vanilla Temples

### ISSUE THREAD

**Issue by MeinKraft** [Ivorforce/RecurrentComplex#282]
Is it or would it be possible to spawn my own structures inplace of the Vanilla Minecraft temples/dungeons.

So when the world decides to spawn a Jungle Temple or Ocean Monument etc, my own structure would be put in their place, but maintain the fact it is an Ocean Monument or Witch Hut or Jungle Temple etc

Maybe I could have 3 of my own Witch Hut structures to replace the standard Witch Huts? Randomly chosen of course

**Comment by Ivorforce** [comment]
This will be possible as of f591199d571c8dde546088ed8dff9512f02d368e / the next update.
