### ISSUE TITLE
Immersive Engineering Crates / Actually Additions Display Stands

### ISSUE THREAD

**Issue by MeinKraft** [Ivorforce/RecurrentComplex#283]
Can you add support for Immersive Engineering Wooden/Reinforced Crates using the generator tags the same way normal chests can.  You cant right click a generator tag on them and they wont generate loot when generated into the world. - the  same for Display Stands from Actually Additions in 1.12 - 1.10 works fine

Thanks

**Comment by Ivorforce** [comment]
Hmm that's gonna be hard... ReC supports all default inventory tile entities, but I'm not too keen on supporting mods that aren't using the default system for whatever reason. I'll hit up the authors though and see where that gets me :)

**Comment by Ivorforce** [comment]
Nevermind, it's my fault for not supporting capabilities yet. Will get to that.
