### ISSUE TITLE
I think that RC is lagging and crashing the server.

### ISSUE THREAD

**Issue by beesyndicate** [Ivorforce/RecurrentComplex#284]
Please any insight would be helpful. Thank you in advance.

[crash-2017-10-20_10.36.39-server.txt](https://github.com/Ivorforce/RecurrentComplex/files/1402355/crash-2017-10-20_10.36.39-server.txt)

[server output.txt](https://github.com/Ivorforce/RecurrentComplex/files/1402357/server.output.txt)

**Comment by Ivorforce** [comment]
I _think_ whatever 'pengu hammercore' is froze the server by taking too long on a single tick. Try sending it to them. It's hard to say though.
