### ISSUE TITLE
[Question] Blacklisting generation in certain dimensions

### ISSUE THREAD

**Issue by NillerMedDild** [Ivorforce/RecurrentComplex#285]
Hey!

I'm unsure how to use the config for blacklisting generation in dimensions, this one:
    # Dimension Expression that will be checked for every single structure. Use this if you want to blacklist / whitelist specific dimensions that shouldn't have structures. [default: ]
`S:universalDimensionMatcher=`

It didn't work with dimension ID, so what does it accept?

**Comment by Ivorforce** [comment]
Please refer to the [wiki entry on expressions](http://minecraft-recurrent-complex.wikia.com/wiki/Expression). There are concrete examples for blacklists and whitelists there.
