### ISSUE TITLE
[Feature Request] Adventure/Rare config

### ISSUE THREAD

**Issue by MeinKraft** [Ivorforce/RecurrentComplex#286]
Could you add the distance between structure generation to the config files

To go from Adventure 330 chunks to Rare 1666 to Ultra Rare 6666 chunks is quite a jump

thanks

**Comment by Ivorforce** [comment]
You can just [edit the natural generation categories yourself](http://minecraft-recurrent-complex.wikia.com/wiki/Natural_Generation_Category_File) .
