### ISSUE TITLE
[QUESTION] /locate command in 1.12

### ISSUE THREAD

**Issue by davqvist** [Ivorforce/RecurrentComplex#288]
So, vanilla added the locate command. I tried to use it with RC structures without any luck. So I am wondering if am doing something wrong, or if there is no support for it, or if it can't be done because RC structures are different to Minecraft structures? Looking at your code it seems that the latter is true because you don't use the MapGenStructure class, right?

Would be interesting if you could give any information about that.

**Comment by Ivorforce** [comment]
Yes, /locate works precisely because of vanilla's predictive structure generation algorithm.

ReC uses a different approach to generation and thus can't offer the same functionality in the same way. It's probably possible to implement it but I don't really plan on doing it. Is there something specific you're trying to accomplish? :)

**Comment by davqvist** [comment]
2 things:
- Easier debugging of rarer structure distributions
- (not necessary related to /locate, but ... ) The mod In Control offers to restrict spawning of mobs to structures. As this didn't work, I assumed that this is because RC structures != Minecraft structures. The easiest way to determine if this is true was for me to test if /locate works.

**Comment by Ivorforce** [comment]
The first I understand - I'll keep it in mind for future reference but I can't promise a feature addressing this.

If you want the mob spawning functionality you can pitch the idea to In Control - it should be pretty easy to set up an adapter for ReC structures (ReC does fire structure generation events, for example) :)

**Comment by davqvist** [comment]
Thanks, Not sure how structure generation events help though as they only fire once.

**Comment by Ivorforce** [comment]
Other mods such as Pokecube use these events to enable custom 'biomes' where structures spawned to control mob spawning - the same would be possible with in control.

Another approach would be keeping track of ReC's structure list, querying it live to see if structures are nearby and change mob spawns accordingly. This one would require a bit more effort though.

**Comment by davqvist** [comment]
Interesting, thanks for clarification. Not sure if that would be worth my effort, though.
