### ISSUE TITLE
ton´s of entrances in the log file: casading worldgen lag...

### ISSUE THREAD

**Issue by JasonKillsUs** [Ivorforce/RecurrentComplex#290]
Not o much an issue rather an annoyance:)
Recurrent Complex loaded a new chunk (13, 6  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
MC 1.12.2/Forge_2541

**Comment by Ivorforce** [comment]
See #155
