### ISSUE TITLE
Mod licensing

### ISSUE THREAD

**Issue by asiekierka** [Ivorforce/RecurrentComplex#291]
I've noticed that IvToolkit is Apache 2.0, whereas this project is missing a license. Is it intentional that this mod is proprietary, with only visible source?

**Comment by Ivorforce** [comment]
Yes, that's exactly it - mostly because the IvToolkit contains most of the technologically interesting parts, while ReC contains the implementations which I do not intend to give away for others to copy per se (e.g. to fork and release themselves). I'm open to any specific thoughts though :)

**Comment by asiekierka** [comment]
Alright, won't inquire further.

Copyleft licenses let you take forks' changes back, so you might want to consider something like the LGPL or GPL. But if that's not satisfactory, guess you'll have to stay visible source only!
