### ISSUE TITLE
/#move downwards doesn't work

### ISSUE THREAD

**Issue by ulkunderscore** [Ivorforce/RecurrentComplex#294]
This does work:
`/#move -x -1`
`/#move -z -1`

This doesn't work:
`/#move -y -1`
It says: "The number you have entered (-1.00) is too small, it must be at least 0".

MC 1.12.2
Recurrent Complex 1.4.6
Forge 14.23.1.2555

**Comment by Ivorforce** [comment]
You can't move a structure to y=-1. That's below the world :)

**Comment by ulkunderscore** [comment]
Then how do you move blocks downwards relative to their position?
[Picture](https://imgur.com/a/LgOzB)

**Comment by Ivorforce** [comment]
Ah yes, I see the problem now. It worked at an earlier date so I've missed breaking it :)
