### ISSUE TITLE
Structures saved to structures/active not being copied automatically to new worlds (?)

### ISSUE THREAD

**Issue by RiverC** [Ivorforce/RecurrentComplex#295]
This is likely some kind of issue on my end, but I can't for the life of me figure out what I'm doing wrong. 

Here are the steps: (singleplayer `1.12`, forge `14.23.1.2560`)

1. I create a structure in a world, with natural generation set to default Overworld for biomes/dimension
2. I export/edit it into `world/active`
3. When I like it I export it into `active`
4. I shut down that world
5. I check the structures folder for this profile, noting that the structure is present in `.profilename/structures/active` with the correct name
6. I create a new creative world with structure gen on, otherwise default
7. I check the `structures/active` dir for that save, but that structure is not there (it also is not generating.)

Note that I'm using multiple profiles through the Minecraft launcher, I'm going to try a few things to see what I might be doing wrong, and if there's something obvious let me know.

**Comment by RiverC** [comment]
As an update, I tried copying the new structure into the default `.minecraft/structures/active` folder which contains almost all of the structure files anyway (I noticed the new profile did not have anything other than my new structure in `structures/active`) but this didn't get that structure copied into the new world's `structures/active` folder.

Creating a new world and then manually copying the structure in seems to work, however. (Although it seems I lost my inventory generators, I'm trying to figure out if I saved the wrong version.)

**Comment by Ivorforce** [comment]
The world/active folders are for structures _exclusively_ for that specific save. Everything in the normal active folders gets loaded for each world, but not copied to the world/active folders. You can check that your structure is loaded most easily by /#lookup YourStructure.
