### ISSUE TITLE
Cascading WorldGen Lag

### ISSUE THREAD

**Issue by Jackiechun117** [Ivorforce/RecurrentComplex#296]
Didn't find an open issue on this, FML told me to report it.

 [FML]: Recurrent Complex loaded a new chunk (24, 16  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

Newest version installed, 1,12'

Lost Cities, BOP, IV Toolkit, Optifine, Mantle installed

**Comment by Ivorforce** [comment]
Please see #155.
