### ISSUE TITLE
Odd, random crash related to Hats.

### ISSUE THREAD

**Issue by starg09** [Ivorforce/RecurrentComplex#30]
Hi there. I prepared a modpack on the FTB Launcher, which includes your mod. But I noticed there seems to be some little, odd bug. [I originally thought it was a mystcraft error](https://github.com/XCompWiz/Mystcraft-Issues/issues/132), yet now that I've looked on it with them, it seems like there's some incompatibility between your mod and Hats.

Basically, in my case there was some Mystcraft age where a recurrent complex structure may have generated, and which might have some spawner that messed with hats, and caused a crash every time that chunk loaded. Removing either mystcraft (which means it happened on one of its dimensions), hats or your mod (the two which apparently conflict) seems to fix the issue.

For now, I've disabled Mystcraft on the pack, but the chance of this happening again in a more regular dimension still exists. Do you have any idea what could be causing it exactly? Thanks for reading =)

(PS: If you want it, I can send you a backup of the affected world. You can add my modpack with the code "frutas", then use v2.0.2, which is where it happened)

(PS2: As mentioned in the mystcraft report, this has been tested with and without fastcraft or betterfps. Same result)

**Comment by Ivorforce** [comment]
Yeah, MystCraft isn't really at fault here.

What's happening is that Recurrent Complex spawns an entity, to which the hat mod responds - it seems to ask some mob spawner nearby if it is activated, where the tile entity hasn't been fully initialized yet (aka World obj is probably missing). 

I'm sorry to delegate this again, but it's really nothing I can fix from my end. The context in which the entity is spawning is valid, and thus it's ultimately the hat mod that is crashing. I can only recommend directing it to its maintainer.

Feel free to ask me if there are any questions left though.
