### ISSUE TITLE
[1.12.2] Cascading WorldGen Lag

### ISSUE THREAD

**Issue by Axebeard2025** [Ivorforce/RecurrentComplex#300]
I was getting some cascading worldgen lag warnings in both SSP and SMP Minecraft 1.12.2 after adding Recurrent Complex.

This behavior seems to occur both during initial worldgen and as you explore new chunks in the world.

The mod [PrimalCore](https://www.curseforge.com/minecraft/mc-mods/primalcore) also has this problem.  I first noticed this problem when I had added PrimalCore and Recurrent Complex at the same time in my modpack.  Individually, each mod creates lag, but when you put them together, the lag is much, much worse.

Here are the test results from using different versions of Forge with the 2 versions of Recurrent Complex for Minecraft 1.12.2.  I've also uploaded the log files for each test in separate zip files.  I did not do any Creative or Hardcore tests.

Test 1
	Files:
		- Minecraft 1.12.2
		- Forge 1.12.2-14.23.1.2585 without Mercurius
		- IvToolkit 1.3.3-1.12
		- Recurrent Complex 1.4.5.1
	SSP Result: Cascading worldgen lag
	SMP Result: Cascading worldgen lag

Test 2
	Files:
		- Minecraft 1.12.2
		- Forge 1.12.2-14.23.1.2555 without Mercurius
		- IvToolkit 1.3.3-1.12	
		- Recurrent Complex 1.4.5.1
	SSP Result: Cascading worldgen lag 
	SMP Result: Cascading worldgen lag

Test 3
	Files:
		- Minecraft 1.12.2
		- Forge 1.12.2-14.23.1.2585 without Mercurius
		- IvToolkit 1.3.3-1.12
		- Recurrent Complex 1.4.6
	SSP Result: Cascading worldgen lag 
	SMP Result: Cascading worldgen lag

Test 4
	Files:
		- Minecraft 1.12.2
		- Forge 1.12.2-14.23.1.2555 without Mercurius
		- IvToolkit 1.3.3-1.12	
		- Recurrent Complex 1.4.6
	SSP Result: Cascading worldgen lag 
	SMP Result: Cascading worldgen lag

[Test 1.zip](https://github.com/Ivorforce/RecurrentComplex/files/1594847/Test.1.zip)
[Test 2.zip](https://github.com/Ivorforce/RecurrentComplex/files/1594848/Test.2.zip)
[Test 3.zip](https://github.com/Ivorforce/RecurrentComplex/files/1594849/Test.3.zip)
[Test 4.zip](https://github.com/Ivorforce/RecurrentComplex/files/1594850/Test.4.zip)

**Comment by LiskoSlayer63** [comment]
I noticed this too, I'm using Biomes O' Plenty and if the world isn't pre-generated this causes so much lag that users will timeout.

**Comment by Ivorforce** [comment]
See #155. I'm working on it, but as ReC has a lot of large structures, it isn't as straightforward at times.
