### ISSUE TITLE
OOM when generating poem

### ISSUE THREAD

**Issue by BrisingrAerowing** [Ivorforce/RecurrentComplex#304]
[Crash Log](https://gist.github.com/BrisingrAerowing/995ba4d0ec4b8a932962600a49fa5acc)

I have 16GB allocated to MC (14 usable), and I usually hover around 10GB allocated (I had to allocate more for Twilight Forest, but I don't use that mod anymore due to numerous OOM issues I had with it), so a poem generation taking up ~4GB of memory is kind of bizarre. From the stack trace, I think your tokenizer has a bug.

**Comment by Ivorforce** [comment]
Hah, dang. I'll be looking into it.
