### ISSUE TITLE
Cascading lag / rapid generation attempts

### ISSUE THREAD

**Issue by raltus** [Ivorforce/RecurrentComplex#306]
It looks like it is trying to generate in the same area as SteamWorld when it happens. There was more but I copied the largest Recurrent Complex sections from the log. They have the structures listed with them. I did notice a spike on another world when I was checking the generation. The giant oak and the building with pool and giant statues spawned close together and my frames dropped to 9 fps while they loaded. I was flying around in creative in case it makes a difference, but it still seems to try multiple structures in a second even when I'm walking. 
Forge 2611 MC 1.12.2
Recurrent Complex 1.4.7

https://gist.github.com/raltus/62925c768294d54d7c2abd0760413ee0

**Comment by Ivorforce** [comment]
Please see #155. Cascading chunk gen can be a problem but it usually isn't; especially after initial world generation it usually makes little difference by itself. I'm working on improving this every version but in the meantime I hope it's okay that it has some initial lag, but like I said usually it doesn't persist over longer play :)
