### ISSUE TITLE
Question or Suggestion

### ISSUE THREAD

**Issue by Boolyman** [Ivorforce/RecurrentComplex#307]
Is there a way to completely prevent the 187 default structures from loading.  They already are not generating, but I don't even want them to take up loading time.  I just want to use ReC for a couple spawn structures, but would really like to minimize the loading time impact.

**Comment by Ivorforce** [comment]
See [this wiki page](http://minecraft-recurrent-complex.wikia.com/wiki/Using_Recurrent_Complex_as_a_Utility).
