### ISSUE TITLE
Trying to connect two maze exits crashes the game.

### ISSUE THREAD

**Issue by HogPilot01** [Ivorforce/RecurrentComplex#309]
I am trying to connect maze-exits with a maze generator, but whenever I try to edit the element, the game crashes and displays this as the error:

The game crashed whilst updating screen events
The game crashed whilst updating screen events
Error: java.lang.IllegalArgumentException: titles: 3, dimensions: 1

**Comment by Ivorforce** [comment]
I'm gonna need the full log, a tiny section isn't really enough.

**Comment by dcdc2541** [comment]
I am also encountering this crash.
Attached is my crash report

[Crash Report.txt](https://github.com/Ivorforce/RecurrentComplex/files/2903923/Crash.Report.txt)

**Comment by Ivorforce** [comment]
Thanks for the report. Just apparently a dumb error on my part :)
