### ISSUE TITLE
Easier way to enable and disable structures

### ISSUE THREAD

**Issue by lesdmark** [Ivorforce/RecurrentComplex#31]
I like that this mod has so many great random structures it can generate, but is there any way it could be made easier to enable and disable structures? The biggest problem I have most of the time is even knowing what structures exist in the first place. The wiki lists so few of them.

**Comment by Ivorforce** [comment]
It's very easy to enable / disable structures at will - just use the structureLoadMatcher option.

As for what structures exist: All structure IDs are logged to the console, as well as being auto-completed on /#gen etc. In the following version, there will also be /#search to find more specific structures too.
