### ISSUE TITLE
Custom NPCs not working

### ISSUE THREAD

**Issue by CostDeathYT** [Ivorforce/RecurrentComplex#311]
Every time I try to create a structure with a Custom NPC the NPC will disappear from the original structure as soon as the export is complete and if i try and import the new structure it won't show up.
If it helps I am using the 1.4.5 Mod version for Recurrent Complex, 1.10.2_beta for CustomNPCs  and 1.10.2 Minecraft version.
Thanks for the help, Cost.

**Comment by thephoenixlodge** [comment]
That's not the fault of ReC, it's just the way CustomNPCs work. When you spawn in the NPC as an entity it gets data listing the coords you spawned it as its home (an area for it to hang around essentially). ReC just copies the entity data (as makes sense, this needn't be changed), which as a result includes the home position for the NPC, so if your structure just has the NPC there as an entity, it'll poof off to its home location when the structure spawns with it.
To work around this you need to use script blocks or command blocks to run a command to spawn them as a clone (you'll need to use the mob cloner from CNPC to make clone data for them).

**Comment by CostDeathYT** [comment]
Could you link me to a tutorial/a step by step guide on how to do it? Thx

**Comment by CostDeathYT** [comment]
I think i got my head around it but ummm how am i meant to open up a gui for the script block? Im right clicking and it does nothing.

**Comment by CostDeathYT** [comment]
Nevermind I forgot I had been de-oped. Thanks.
