### ISSUE TITLE
[1.12.2] Maze generation hangs world generation + possible broken structure

### ISSUE THREAD

**Issue by NotAVerb** [Ivorforce/RecurrentComplex#317]
This appears in the logs every time world generation freezes.
https://gist.github.com/NotAVerb/c38e04652710ff925e64d266cd6dd9b9

The StatueTemple caused the issue this time. I'm pretty sure its responsible for most of the other times this has happened.
I'm not even sure if _any_  maze components where generated in the temple. I broke into the emerald treasure room and there didn't seem to be any way to get in without busting through stone. The two entrance looking areas lead to dead ends too.

I've been able to cause the same warning messages by running /#gen StatueTemple
No maze components generated either.
Looks like somethings broken with this structure.

edit: just to be sure I did a test with only recurrent complex installed and a fresh structure folder.
The same issue occurred upon running /#gen and StatueTemple generated without an inner maze to its treasure rooms.

**Comment by BrisingrAerowing** [comment]
I've noticed this all the way back in 1.10.2 as well. Also saw it on the FoolCraft 2 series that FalseSymmetry did.

**Comment by Ivorforce** [comment]
The StatueTemple is the most ambitious maze gen structure so far and often exceeds the maze solving time. I am hoping to improve the algorithm even further in the future to make that structure work.

For now, I recommend pushing down the mazeTimeout to solve the issue.
