### ISSUE TITLE
[Suggestion/Enhancement] More user-friendly way to enable/disable in-mod structure content

### ISSUE THREAD

**Issue by Seth0067** [Ivorforce/RecurrentComplex#329]
Not that I don't absolutely love ALL of your content, but when pairing with my own usage, it seems to be a ton of work to got through the big list of RC content and then toggle all the things on or off.  True, you can white/blacklist things after viewing in game, but having to do it at command line in-game is really arduous when I might see a big list in a txt file and address in that way.  

Maybe you can include a commented out list in the default config where the structure generation matcher cfg is?

For bonus points your Wiki might contain pictures of all your structures for reference. I might also volunteer some of my time to do these shots if you elected to do something like this (I wouldnt ask you to do something I wouldnt do myself if I could!)

Thanks for all the hard work, man.

**Comment by darchitectlp** [comment]
I whole-heartedly agree. Please Ivorius, can you have your .rcsts *not* be included in you .jar file? 

This is what I wrote on the modpack comments page (if you want a work around):
 Actually, what I wound up doing was unzipping a copy of your .jar (like @Imrielle suggested) and dragged all the .rcst files I didn't want to the structures>inactive folder. That was way simpler than anything involving a command prompt within the game. Even having a built in structures>active/inactive folder inside your .jar seems counter-intuitive and confusing. My first thought when I started using your mod was to check in that visible folder for the structures, but it was empty... and that left me very confused.
Again, just a suggestion, but from a ux perspective, having those initial files load into the user-accesible minecraft>structures>active folder makes it very clear how your system works, and makes it easier for users to pull and delete things they don't want (and add, as well!) Please take all of this as healthy commentary. Your mod is an awesome addition for pack makers and players. I don't want you to construe this as criticism. Thanks so much!

**Comment by Seth0067** [comment]
I whole-heartedly appreciate your seconding, darch, and I also echo your sentiments regarding commentary (not criticism).  You modders do such a great job all for love and community (and maybe Amazon gift cards, ok), that raising such things seems sometimes ungrateful. As a UX professional I would love to even directly contribute towards a better experience for your users, and would be eager to help in any way I can to assist!

**Comment by Ivorforce** [comment]
You guys are, of course, correct. ReC has very powerful systems that often fail to provide a good experience for average users.

Buut I am not at all a fan of editing text files (config file included - ReC has always provided a usable config GUI in the mods section).

I'd rather have a GUI that makes it possible and easy to edit the spawnTweaks option. 
Say we have a GUI like this:

* StoneMaze [Spawn Tweak] [Set To Default] [Generate for Testing]
* GenericTree [Spawn Tweak] [Set To Default] [Generate for Testing]
* MeteorSite [Spawn Tweak] [Set To Default] [Generate for Testing]

There'd be one line for each structure in the mod, and setting to 0 will disable the structure (as the spawnTweaks option does).

I'd include a comment in the config file / GUI with how to access this GUI. It's already possible to edit it ingame, but it doesn't have a nice GUI for it.

How would that sound?

**Comment by Ivorforce** [comment]
Welp, looks like I got ahead of myself. I will link this command in as many places as possible and I hope it makes it easier for people to go through structures to tweak and/or disable them.

In ReC fashion, this is how it looks right now:

<img width="1176" alt="Bildschirmfoto 2019-03-17 um 16 44 25" src="https://user-images.githubusercontent.com/2308167/54493763-ee9bd480-48d3-11e9-990c-e196b2fe02d1.png">

I will probably adjust this some some more but it seems pretty usable.

**Comment by Seth0067** [comment]
Sounds good - will check this out this week when I have some time.
