### ISSUE TITLE
[BUG]only one type of custom trees is generated

### ISSUE THREAD

**Issue by Lodugh** [Ivorforce/RecurrentComplex#333]
Tried it with latest(14.23.4.2708) and recommended(14.23.4.2705) forge with nothing but Recurrent Complex installed, default configs and default world generation. The only generated custom trees are these dead ones:
![2018-06-16_13 51 26](https://user-images.githubusercontent.com/13154183/41498400-076e495a-716d-11e8-8ddc-8aade1512d34.png)
![2018-06-16_13 52 06](https://user-images.githubusercontent.com/13154183/41498401-078cf6de-716d-11e8-8939-731297b23ec1.png)
And there are no custom spruce trees.

**Comment by Ivorforce** [comment]
Try /#lookup GenericTree (and perhaps a few others) and see if they're marked as _Active_. Also try /#sanity.

Do you have any biome mods installed?

**Comment by Lodugh** [comment]
I really just used a clean forge install with nothing but Recurrent Complex and IVToolkit in it and i didnt change any configs and used the default world generation..
Here the output of the commands:
![2018-06-28_13 34 42](https://user-images.githubusercontent.com/13154183/42031869-0e3ac9a6-7ad8-11e8-93c9-8c419045bbb3.png)

**Comment by Lodugh** [comment]
Hey, I really dont wanna push you, just wanted to say that I'd be very happy if this got fixed, because its the only thing that holds me away from starting my new modded world. The terrain just looks so much better with your custom trees :). Is there any other way I could help? I am a coder by myself just never got into java and minecraft mods so I dont know whether there really is much I can do.

**Comment by Lodugh** [comment]
I hope I am not annoying you but I really love this mod and I don't want to see it die.. I guess you got a lot of other things to do at the moment but is it actually hard to fix? Because if it isn't I would try to get into modding for it.

**Comment by Ivorforce** [comment]
Sorry for no responses - i haven't been working on ReC in quite a while. A fix will probably soon follow if I can figure this out. There have been a lot of people with this problem either way.

**Comment by Ivorforce** [comment]
Fixed in #fc3a407e. I hope sapling placement still works, but for now I'm glad I found the fix to this thing.

**Comment by Lodugh** [comment]
Thanks a lot for the fix :)
