### ISSUE TITLE
Does It Spawns in Biomes O Plenty Biomes?

### ISSUE THREAD

**Issue by Jasondia16** [Ivorforce/RecurrentComplex#339]
I Have a question to ask here can the structure spawn in Biomes o Plenty Biomes because I'm building a structure (Boss Dungeon) in a Biomes O Plenty I want t Know so I don't waste time?

**Comment by Ivorforce** [comment]
Yes, as long as you use Biome Dictionary IDs rather than individual biome IDs for the spawn configuration, you should encounter no problems.

**Comment by Jasondia16** [comment]
Thanks Man
