### ISSUE TITLE
Overwrite the schematic part of a structure while keeping it's data

### ISSUE THREAD

**Issue by WolfieWaffle** [Ivorforce/RecurrentComplex#34]
As far as I am aware, there is no way to change the actual block structure of a structure while keeping it's metadata and generation rules. You can use /#edit, but that only changes the data of a structure, not the block portion. You can use /#export to overwrite it, but that removes all it's generation rules.

If it does not already exist and I'm juts missing it, I would like a way to re-export a structure while keeping all the generation rules the same. It would really help in tweaking the default structures.

**Comment by Ivorforce** [comment]
Not sure why I didn't answer this earlier.

You can just use /#export MyStructure to copy all of its previous generation data into the GUI (effectively only overriding the world data / 'schematic part').

**Comment by WolfieWaffle** [comment]
Hm, ok thanks. I thought I tried that before, but I didn't know what I was doing at the point, so I'll try it again XD
