### ISSUE TITLE
How do you make the structure deep? so my house's underground floor goes underground?

### ISSUE THREAD

**Issue by Jasondia16** [Ivorforce/RecurrentComplex#340]
Hello again! So I Have a Problem I've Encountered so I made a house with a Underground floor,and a floor grass level and a floor which is in the roof. Is there a way to make the structure deep so the underground floor is not on ground level and Explain me how to do it. Thanks

**Comment by Ivorforce** [comment]
Just use the surface placer but set your base y level to the height where you expect the floor (surface) to be at.

**Comment by Jasondia16** [comment]
I'm still having that problem mind giving me a cli or a video how to do it because i'm using surface placer but not letting me do it

**Comment by Filmos** [comment]
![Gif](https://i.imgur.com/sy18N5b.gif)
Now the most bottom block of the structure will generate 3 blocks below the surface level.

**Comment by Jasondia16** [comment]
Now it stops spawning the structure trying to make it 25 blocks (X) Away from spawn LOL.
