### ISSUE TITLE
[Issue] Holders not rotating/mirroring with structures

### ISSUE THREAD

**Issue by Filmos** [Ivorforce/RecurrentComplex#342]
Blocks generated by holders aren't rotated/mirrored, even when the structure is.
This is a very serious issue because, for example, if we had a holder with 3x11 area and a structure rotated by 90 degrees, block generated by the holder would completely destroy the structure.

**Comment by Filmos** [comment]
Edit: It appears that the content of the area is being rotated/mirrored, but not it's position.
That means that all square areas with the holder in the center are rotated properly, but if the area is a square which center is 2 blocks north of the holder, it will always be on the north, even if the structure is rotated.
If the area isn't a square an empty script block might generate as well.
Unfortunately, due to #343, my testing capabilities are limited.

**Comment by Ivorforce** [comment]
Oh, good to know. I thought I'd have to look into rotation logic again, that stuff is horrible haha.
I'll be fixing this in the next update.

**Comment by Ivorforce** [comment]
Ah wait, wrong issue. lol
