### ISSUE TITLE
[Suggestion] Holders containing multiple areas

### ISSUE THREAD

**Issue by Filmos** [Ivorforce/RecurrentComplex#344]
The idea is very simple, yet extremely useful - let holders contain multiple areas, from which one would be randomly selected. This is basically the same mechanic that is already implemented in **Run Command**.

It would allow for bigger randomization of the structures, such as a secret room inside a house, which is sometimes a diamond stash, sometimes an art gallery and sometimes a hidden dirt collection.

I know that it can be achieved using local triggers and conditions, but that would require extensive logic and extreme amount of variables (especially since each variable can only be 0 or 1, and not an actual integer).

**Comment by Ivorforce** [comment]
For anything with more complex room setups, I'd definitely recommend opting for structure list spawning (with a structure script) rather than a holder block. They were designed for exactly this use-case! :)
Those holders are meant to be used for simple cases, but not for anything more than that.
