### ISSUE TITLE
[Issue] Blocks generated by holders aren't affected by transformers

### ISSUE THREAD

**Issue by Filmos** [Ivorforce/RecurrentComplex#345]
If a holder contains a block that's supposed to be replaced with a transformer (such as **Solid 0**, **Solid 1** or **Space 0**), it will just place that block and no transformation will occur.
The same thing happens to script blocks, they are just being placed, but not executed.

While this isn't strictly a bug, it definitely decreases possibilities of the holders.

**Comment by Ivorforce** [comment]
Yep, you're right. I'll be looking into a solution for this.

**Comment by Ivorforce** [comment]
Fixed in 452516f.
