### ISSUE TITLE
I'm still having the Problem I'm making my structure with a Atic, basement and a floor in the floor level of the world

### ISSUE THREAD

**Issue by Jasondia16** [Ivorforce/RecurrentComplex#346]
I'm still having that problem mind giving me a cli or a video how to do it because i'm using surface placer but not letting me do it

**Comment by Filmos** [comment]
![Gif](https://i.imgur.com/sy18N5b.gif)
Now the most bottom block of the structure will generate 3 blocks below the surface level.

**Comment by Jasondia16** [comment]
Lol I Derped

**Comment by Jasondia16** [comment]
Thanks
