### ISSUE TITLE
1.11 structure doesn't generate in 1.12 MC; crashes on placer inspection.

### ISSUE THREAD

**Issue by talonos2** [Ivorforce/RecurrentComplex#348]
I made a structure in a 1.11 (or maybe 1.10?) version of Minecraft, and tried to use in in a 1.12 instance. It would not generate. Suspecting it may have had something to do with its placer, I tried to #Edit it and check its placer. When I did so, MC crashed with the following stack trace:

https://pastebin.com/raw/1t158DvX

Structure file is attached.

[CityRuin00.zip](https://github.com/Ivorforce/RecurrentComplex/files/2343914/CityRuin00.zip)

Thanks for looking into this!

**Comment by Ivorforce** [comment]
I'll be looking into it soon. I usually try to keep complete and uncompromising backwards compat, so this would definitely be an error on my part :)
