### ISSUE TITLE
Generate structure in nether

### ISSUE THREAD

**Issue by skydark** [Ivorforce/RecurrentComplex#35]
Is it possible to add a cave-like structure generation base that can be used in nether? It is difficult to generate structures in nether since they will spawn above the ceiling(the "surface"), or most likely be buried in netherracks.

**Comment by Ivorforce** [comment]
This goes hand in hand with the conditional spawn generation (i.e. spawn on 'some surface' < y=100 rather than 'top surface).

Please refer to #15 for its completion.
