### ISSUE TITLE
Most structures not loading in Terrafirmacraft 1.12 alpha builds

### ISSUE THREAD

**Issue by JonJonsonsSon** [Ivorforce/RecurrentComplex#352]
The only 2 structures I've seen spawn after traveling 15k-20k blocks are ShrineSmallAir and ShrineSmallWater. Newly made/Self-made structures aren't spawning either.
TFC 1.12 .jars: https://jenkins.dries007.net/view/TFC//job/TerraFirmaCraft
Complete list of mods in case something other than TFC is responsible: https://i.imgur.com/ISftuDo.png

**Comment by JonJonsonsSon** [comment]
Dungeons from Dungeons2 also don't seem to be spawning. Interestingly, most/all structures from another mod called "Ruins (Structure Spawning System)" are spawning in the world. I'm not sure why some structure generation mods are working while others aren't. Hopefully this info helps in some way.
Link to the latter mod: https://minecraft.curseforge.com/projects/ruins-structure-spawning-system

**Comment by Ivorforce** [comment]
I'm guessing TFC is changing biomes enough for ReC not to match anything anymore. 
Have you tried poking its authors about if they use the biome dictionary properly? Because that would usually resolve the issue.

**Comment by JonJonsonsSon** [comment]
I just contacted him. He replied, "No I didn't, I'll relay this to the other devs too."
So I guess that solves that. Thanks!

**Comment by JonJonsonsSon** [comment]
Test
