### ISSUE TITLE
Excessive amount of Dead Trees in every biome that has trees!

### ISSUE THREAD

**Issue by SirAron111** [Ivorforce/RecurrentComplex#355]
Excessive amount of Dead Trees in every biome that has trees!
Nearly every 3 chunks there is one thats to many what s going on even tried instaling only the mod and nothing else still so many?
Forgeversion: 14.23.5.2768

**Comment by Lodugh** [comment]
Duplicate of #333

**Comment by Ivorforce** [comment]
Yup, duplicate.
