### ISSUE TITLE
ChurchGraveyardRuins Script Block

### ISSUE THREAD

**Issue by NillerMedDild** [Ivorforce/RecurrentComplex#357]
Hey o/ 

There's a Script Block generated somewhere on the grass of the ChurchGraveyardRuins structure. Survival players can break it with a pickaxe, move it elsewhere and use for whatever they like. 

I suggest replacing it with a Vanilla Zombie Spawner.

Original report: https://github.com/NillerMedDild/Enigmatica2Expert/issues/367

RecurrentComplex-1.4.7

**Comment by Ivorforce** [comment]
Good to know, thanks for the report. I will remove it in the next update :)

**Comment by Ivorforce** [comment]
Welp, this was probably one of the smallest seeming bug reports that helped stabilise some behavior a lot better haha
