### ISSUE TITLE
Watching Server crash on dedicated server

### ISSUE THREAD

**Issue by Furuchiru** [Ivorforce/RecurrentComplex#358]
Mod version: 1.4.7
Using Enigmatica 2 Expert 1.44
The server has crashed around 4 times with the same crash
https://pastebin.com/v0igBTVY
https://pastebin.com/7yGwdbQN

**Comment by berendbro** [comment]
I got the same problem with a crash similar to that second crashlog.
I "solved" it by adding "!$reccomplex" to the structureGenerationMatcher config option, however that just stops the structures from generating, so it prevents the problem, doesn't solve it :/

**Comment by MJRamon** [comment]
Of course, it prevents the problem, because it's in structure generation itself, and you just disable the mod :)
There was no release for a year from now, who knows, maybe it will be fixed, maybe not.

**Comment by Ivorforce** [comment]
Duplicate of #155. I recommend pushing down the structureSpawnChance and / or tree decoration replacement chance down in the config for now. A fix will, hopefully, soon follow.
