### ISSUE TITLE
[Suggestion] Protected structures

### ISSUE THREAD

**Issue by Kiyaku** [Ivorforce/RecurrentComplex#359]
Hey,

i think a useful addition would be some sort of block protection to created structures. Basically something that acts as if the player was in adventure mode by either making anything in the bounding box of the spawned structure unbreakable, or each block individually. 

The Betweenlands has a similar system for their own structures, maybe that explains it a bit better (https://github.com/Angry-Pixel/The-Betweenlands/blob/9a3102d24c935bad4e53c773e23a3ce015b3a447/src/main/java/thebetweenlands/common/world/storage/location/guard/BlockLocationGuard.java). 

I think this would help a lot with adventure/exploring type modpacks where the user has to go through a certain dungeon/structure without being able to just dig through the blocks. 

Cheers,
SC

**Comment by Ivorforce** [comment]
I like the thought of this and have considered it in the past also.

However, I want ReC to always stay a pure generation mod - there will never be any repercussions when removing or adding it, which means I cannot offer "indestructible" blocks in it. 

I had a plan for adventure dimension structures with custom portals in a separate mod once, but as it looks I will not be starting another MC mod project anytime soon. But you might find other mods offering indestructible blocks and could use those in ReC structures :)
