### ISSUE TITLE
Server stalls then crashes

### ISSUE THREAD

**Issue by CritFlaw** [Ivorforce/RecurrentComplex#361]
Forge 2780
Minecraft 1.12.2
Rec Complex 1.4.7

Crash Log: https://hastebin.com/oceboqayak.rb

This keeps happening. Turned down the structure chance to 0.4, then 0.2, but this just keeps happening Server isn't weak, neither is the client, so this seems to be the mod using too many resources.

**Comment by Ivorforce** [comment]
I'm not sure about the generation hacks but turning down maze timeout might solve crashes for some things. It might also help to turn down tree replacements, since some of those are rather large and can thus cause chained chunk gen as well.
