### ISSUE TITLE
How to disable all mazes?

### ISSUE THREAD

**Issue by MJRamon** [Ivorforce/RecurrentComplex#365]
I cannot check with /#whatisthis because maze generation crashes my server. Parameters like 

```
B:decorationHacks=false
S:mazePlacementReversesPerRoom=1.0
I:mazeTimeout=1
```
had no effect. Would appreciate a solution or list of all mazes in mod, so I can disable them manually. Thanks.

**Comment by Ivorforce** [comment]
mazeTimeout=1 should do the trick. It will, however, only remove the actual maze solving, not the structures themselves. If you want to remove the structures, /#search for maze or /#search --maze might also work (I don't recall). 

If mazeTimeout=1 doesn't stop mazes from being solved, please re-report this in a new issue.
