### ISSUE TITLE
Cascading worldgen lag 

### ISSUE THREAD

**Issue by RealSenZ0** [Ivorforce/RecurrentComplex#366]
Recurrent Complex loaded a new chunk [834, -1406] in dimension 2 (overworld) while populating chunk [834, -1407], causing cascading worldgen lag.

Recurrent Complex loaded a new chunk [833, -1405] in dimension 2 (overworld) while populating chunk [834, -1406], causing cascading worldgen lag.

Recurrent Complex loaded a new chunk [834, -1405] in dimension 2 (overworld) while populating chunk [833, -1405], causing cascading worldgen lag.

and so on.

no clue why this is a thing

**Comment by P3rf3ctXZer0** [comment]
He is not lining structures in a single chunk.

**Comment by Mindlessmrawesome** [comment]
I am having the same issue.

**Comment by NocturneBlock** [comment]
Same issue in 1.12.2. After reading [Investigating extreme Worldgen lag](https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/) on Reddit, I checked, and all the RC structures do seem to be centered pretty solidly on the intersections of chunks. so using the +8 +8 offset would help a lot, as most of the structures fit in a single chunk if placed at or near the center to start with.

**Comment by Ivorforce** [comment]
Yes, I am lining the structures correctly. The issue is unfortunately more complex than that - though I have a solution.

Either way - Duplicate of #155. I recommend pushing down the structureSpawnChance and / or tree decoration replacement chance down in the config for now.
