### ISSUE TITLE
Burning mills and some others structures made of wood

### ISSUE THREAD

**Issue by har5core** [Ivorforce/RecurrentComplex#368]
I use a Recurrent Complex 1.4.7 with ItemPhysic Full, and the thing is some wood structures have one or two torches dropped while generating. Dropped torches cause fire, this is ItemPhysic Full's (not Lite) feature. Could you please check out for dropped torches in wood structures and fix them ?

**Comment by Ivorforce** [comment]
Hrm, falling torches and similar had been a problem for a while, but usually aren't these days. Can you give an example of a structure that has those problems? (Using /#whatisthis while inside)

**Comment by CREEATION** [comment]
Confirmed.

### Versions:
Minecraft: `1.12.2`
Forge: `14.23.5.2776`
Recurrent Complex: `1.4.7`
ItemPhysic Full: `1.4.19`
CreativeCore: `1.9.40`

### Screenshots
![2019-03-15_04 59 00](https://user-images.githubusercontent.com/3277769/54407731-458c8880-46df-11e9-885d-35cc5e68385d.png)

### Structure
[the_torch_test.zip](https://github.com/Ivorforce/RecurrentComplex/files/2969394/the_torch_test.zip)

### Additional information
In around 50 generations without the ruins transformer, torches never broke once. After ~20+ generations **with** the ruins transformer (and playing around with parameters), it happened.

With the gravity property _(in the ruins transformer)_ set to `true`, torches never generated at all _(open separate issue for this? Might just be coincidence)_.

**Comment by Spiderfoxtail** [comment]
I had the same problem but managed to configure ItemPhysic Full. The fires have stopped. This is the link to the issue resolved for me by the mods creator.

https://github.com/CreativeMD/ItemPhysic/issues/94#issuecomment-536170257

Hope this helps.
