### ISSUE TITLE
Import export of architecturecraft elytradev

### ISSUE THREAD

**Issue by pkej** [Ivorforce/RecurrentComplex#373]
Hi,
It seems that recurrent complex doesn't export and import structures with custom blocks made with ArchitectureCraft. It works well with WorldEdit save and load.

![2019-03-06 14_45_51-minecraft 1 12 2](https://user-images.githubusercontent.com/7883794/53885668-9c7ac980-401e-11e9-8372-99af0cb0bbc5.png)

**Comment by Ivorforce** [comment]
Please report this to the ArchitectureCraft devs. This usually means they have some custom positioning logic and/or weird data code. If they can't figure it out, direct them to me and I'll talk with them :)
