### ISSUE TITLE
Error loading entity with ID 'ArmorStand'

### ISSUE THREAD

**Issue by Dimentive** [Ivorforce/RecurrentComplex#374]
I’m playing the [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version 1.62, the latest as of today) modpack for Minecraft 1.12.2 (which uses Recurrent Complex version 1.4.7, the latest as of today), and while pregenerating chunks with the [Chunk-Pregenerator](https://minecraft.curseforge.com/projects/chunkpregenerator) mod, I got the following errors in the server console:

    [20:13:57] [Server thread/WARN] [minecraft/EntityList]: Skipping Entity with id minecraft:armorstand
    [20:13:57] [Server thread/ERROR] [reccomplex]: Error loading entity with ID 'ArmorStand'
    [20:13:57] [Server thread/WARN] [minecraft/EntityList]: Skipping Entity with id minecraft:armorstand
    [20:13:57] [Server thread/ERROR] [reccomplex]: Error loading entity with ID 'ArmorStand'
    [20:13:57] [Server thread/WARN] [minecraft/EntityList]: Skipping Entity with id minecraft:armorstand
    [20:13:57] [Server thread/ERROR] [reccomplex]: Error loading entity with ID 'ArmorStand'

**Comment by Dimentive** [comment]
I also saw this error in the server console while my friend was exploring and generating new chunks:
`[reccomplex]: Error preparing structure: TemplePyramid1, Cause: Maze generation timed out: MesoMaze`

**Comment by Ivorforce** [comment]
I don't know what the issue is with ArmorStand, but the timeout can happen in some of the larger maze structures since the algorithm isn't perfect yet. I'll investigate the armorstand thing.

**Comment by Dimentive** [comment]
All right, thank you.

Does the pyramid time out affect the generation of the structure in any way?

**Comment by Dimentive** [comment]
I also got these errors when pregenerating chunks just now:

    [07:39:09] [Server thread/ERROR] [reccomplex]: Error trying to emulate vanilla decoration
    java.lang.NullPointerException: null
    [07:39:22] [Server thread/ERROR] [reccomplex]: Error trying to emulate vanilla decoration
    java.lang.NullPointerException: null
    [07:39:22] [Server thread/ERROR] [reccomplex]: Error trying to emulate vanilla decoration
    java.lang.NullPointerException: null
    [07:39:24] [Server thread/ERROR] [reccomplex]: Error trying to emulate vanilla decoration
    java.lang.NullPointerException: null

**Comment by Dimentive** [comment]
I also got [a crash](https://pastebin.com/raw/t3EyndV3) that’s apparently related to Recurrent Complex and Biomes o’ Plenty when prepregenerating chunks.

**Comment by Ivorforce** [comment]
The generation timeout means the maze was not properly generated (and instead filled with sandstone).

Your error means you have to allocate more memory to Minecraft if possible. Although I plan to make a fix for that (since that usually becomes a problem in larger worlds).

**Comment by Dimentive** [comment]
I have 7.1 GB of RAM allocated to my client and 5 GB to the server. Shouldn’t that be enough?

**Comment by Ivorforce** [comment]
Hrm probably. Take a look at #353, they are having the same problem. Workaround for now is to simply delete the structureData file.

**Comment by naqaden** [comment]
The problem is some built-in RC structure is trying to generate **minecraft:armorstand** when it should be **minecraft:armor_stand**

**Comment by Dimentive** [comment]
Well, there we have it.

**Comment by Viresneaker** [comment]
Minecraft Wiki:
1.11 | 16w32a | The entity ID is changed from ArmorStand to armor_stand.

**Comment by Kai-Alpha12** [comment]
I dont see this id in reccurrent and in normal MC ids it's already armor_stand. How do I fix this?

**Comment by naqaden** [comment]
I found the old IDs in the UndergroundCultChamber.rcst file. I uploaded my fix [here](https://github.com/naqaden/RecurrentComplex/raw/87fe8a55bdc45ff4e4465da5b4c5045871168c2a/src/main/resources/assets/reccomplex/structures/active/structures/overworld/UndergroundCultChamber.rcst) for [this PR](https://github.com/Ivorforce/RecurrentComplex/pull/427). To edit the IDs yourself: browse src/main/resources/assets/reccomplex/structures/active/structures/overworld, open RCST files as ZIP, and edit worldData.nbt.

**Comment by Ivorforce** [comment]
Thank you all for figuring this out. Full disclosure, I'm not planning on an update to ReC in the near future, but I will reopen until it is fixed.
