### ISSUE TITLE
Server Crash 1.12.2

### ISSUE THREAD

**Issue by AngelusQQ** [Ivorforce/RecurrentComplex#378]
Get server Crash with the latest Recurrent Complex 1.4.8
https://pastebin.com/Xj6Dh3KE

Client loads fine

Minecraft Version 1.12.2
Forge Version: 2768

**Comment by dottiekh** [comment]
Seems like its caused by Recurrent Complex calling net/minecraft/client/gui/GuiScreen, which did not occur in version 1.4.7. Falling back seemed to work on servers just fine, so just do that for now until its fixed.

**Comment by Ivorforce** [comment]
Oh god damnit, this happens every time I update.
Thanks for reporting :)
