### ISSUE TITLE
Custom trees generate over other trees/structures

### ISSUE THREAD

**Issue by CREEATION** [Ivorforce/RecurrentComplex#379]
This destroys tree logs + leaves:

![2019-03-18_00 23 45](https://user-images.githubusercontent.com/3277769/54499650-7570a180-4914-11e9-934a-2b8e38a7619f.png)
![2019-03-18_00 24 22](https://user-images.githubusercontent.com/3277769/54499651-7570a180-4914-11e9-875c-63e7a978f963.png)

The other tree is the pine tree from [Climatic Biome Placement](https://minecraft.curseforge.com/projects/climatic-biome-placement).

**Comment by Ivorforce** [comment]
Hmm I guess they do. I'll be playing around with those values again later.

**Comment by CREEATION** [comment]
They basically just overwrite anything it seems? 🐢 

![2019-03-18_04 36 24](https://user-images.githubusercontent.com/3277769/54505280-7ff06280-4937-11e9-83c5-351a7a4b39e0.png)

**Comment by Ivorforce** [comment]
Fuck yeah i finally figured this bug out. Fix will be available soon®
