### ISSUE TITLE
Have an easier way to generate test structures

### ISSUE THREAD

**Issue by Berstarke** [Ivorforce/RecurrentComplex#39]
What I am looking for is a way to somehow merge /#gen <coordinates> and /#confirm. This (or anything to the same effect) would be pretty useful during structure development, when said structure would factor some random aspect, like chest contents or substructures. When you have to iterate a lot, having two steps goes from trivial to bothersome after a while.

Also possibly something that could be automated. I tried making a chain of commands with vanilla command blocks, but they don't have permission (which I imagine is due to the mod needing player data, for the clipboard for example). Them again, I don't have much permission with command blocks to begin with.

**Comment by Ivorforce** [comment]
/#gen works on command blocks, no confirm needed.

As for players - you can enable and disable previews with the /#preview command.
