### ISSUE TITLE
Pillar transformer not functioning

### ISSUE THREAD

**Issue by SirSquidly** [Ivorforce/RecurrentComplex#396]
Recently, I've been attempting to make a structure which spawns in water, and uses the Pillar transformer for a single pole to reach the bottom of the sea. After countless attempts and failure, I do not believe the pillar transformer is functioning, or isn't explained properly enough.

All attempts include generating it multiple times, generating it in the air, changing what blocks to replace, or what blocks to begin at, along with all between. So far as I can tell, the transformer only functions within a structure's saved boundary.

If anything, I'd just like clarification.

**Comment by Ivorforce** [comment]
Fixed with b9decf24b6ce7c583bfff64cb2369f914812258f. Thanks for the report!
