### ISSUE TITLE
Dissabling Vanilla Structures

### ISSUE THREAD

**Issue by blocks119** [Ivorforce/RecurrentComplex#407]
Hi, I'm just wondering if it's possible to remove vanilla structures without disabling my own structures that I've added with recurrent complex, basically, I really want to remove vanilla villages entirely but if I disable structures then it stops recurrent complex generating stuff

any help would be appreciated, it's for a mod pack that I'm making.

**Comment by blocks119** [comment]
I am happy to use another mod to remove them , I just need it to be something i can export with a modpack so i cant really go deleting minecraft's files on villages

**Comment by blocks119** [comment]
Nevermind :D i found the solution , I was combing through the config file and found the setting 'honorStructureGenerationOption' , if its set to false then even with the structures setting on a world set to false recurrent complex structures will generate anyway , this might be a reccord for the shortest lived question on the forum :P anyways , if thats helpful to anyone then there you go :D

**Comment by vinnyg0621** [comment]
https://www.spellcheck.net/misspelled-words/dissabling
