### ISSUE TITLE
[Question] Spawning conditions

### ISSUE THREAD

**Issue by Polyblock** [Ivorforce/RecurrentComplex#42]
I did some research and didn't find anything relevant to what I'm looking for.

Is it possible with Reccurent Complex to disable the possibility that a structure spawn over liquid? 
Example of what I'd like to not be possible: http://i.imgur.com/3RKJnjS.jpg

I've find that blacklisting ocean biomes eliminate most of the possibility for this to happen, but my main problem are a set of structures that I spawn on Beach biomes.

If this is not currently possible you can conciser my post as a suggested new feature.

Thx for the fantastic mod

**Comment by filloax** [comment]
You could use a Biome expression, yes. Check the wiki for that.

**Comment by Ivorforce** [comment]
Yeah, this is a planned feature. I still need to figure out how exactly I'm gonna go about it though.

'Official' issue for this would be #15.
