### ISSUE TITLE
Are RecCom Structures Registered As Structures?

### ISSUE THREAD

**Issue by VinterNacht** [Ivorforce/RecurrentComplex#420]
In short, can I use a spawn controller like In Control to spawn critters only within designated RecComplex structures?  (Or to make things, like skeletons, stronger if they are spawned within a RecCom structure?)

**Comment by smoothuk** [comment]
Pretty sure they are not, but you can spawn mobs into the structure manually before exporting it.  They should then always generate in the structure.  Be warned though, if you don't set their persistence tag to 1 they will usually despawn long before you find the structure.

**Comment by Ivorforce** [comment]
They aren't registered as vanilla structures, because those aren't really compatible with how I do things.
