### ISSUE TITLE
[Suggestion] Make the books you generate modifiable

### ISSUE THREAD

**Issue by Sunconure11** [Ivorforce/RecurrentComplex#43]
Some of them are pretty much gibberish, plus I imagine some players, not just myself, might want to use them to generate lore for their own worlds.

**Comment by Ivorforce** [comment]
What you _can_ do currently is change the theme of the randomized poems (see https://github.com/Ivorforce/RecurrentComplex/tree/master/src/main/resources/assets/reccomplex/structures/active/poems).

You can also edit the structures books appear in and replace the book generation tags with inventory generation tags filled with your lore books (and / or the book generation tag for randomized gibberish books). Or if you don't need to, just use one for your own structures. The problem with adding static lore to the book generation tag itself is that you'll get the same pieces a lot. Also, the code just kind of 'eyeballs' the words needed per site which makes them a little unappealing at times, compared to handwritten ones.

I see how specific lore pieces would be interesting though (I even tried to implement it once but it involved lots and lots of writing work), so I'm willing to help out here. Do you just want specific pieces randomly distributed or are you also interested in randomized lore?

**Comment by Sunconure11** [comment]
Specific pieces randomly distributed at the moment, since the current books you provide are weird, and I would like to add my own.

**Comment by Sunconure11** [comment]
I'm pretty sure I'm doing something wrong. How do I change the generation tag proper?

This is what I'm using currently:

    ```
# Chance to use the customArtifactTag when an artifact generation tag fires. [range: 0.0 ~ 1.0, default: 0.0]
    S:customArtifactChance=0.0

    # Custom Inventory Generator to override when an artifact generation tag fires. [default: ]
    S:customArtifactTag=

    # Chance to use the customArtifactTag when a book generation tag fires. [range: 0.0 ~ 1.0, default: 0.0]
    S:customBookChance=1.0

    # Custom Inventory Generator to override when a book generation tag fires. [default: ]
    S:customBookTag=newbooks.rcig
```

**Comment by Sunconure11** [comment]
NVM, got it.
