### ISSUE TITLE
Generic.transformers crash?

### ISSUE THREAD

**Issue by Raithion** [Ivorforce/RecurrentComplex#431]
Hello, Recurrent Complex recently crashed my server for reasons unknown. The crash log suggests it has something to do with "generic.transformers."

Here's the server crash log. Any help would be much appreciated:
https://pastebin.com/b66VrwpK

**Comment by Ivorforce** [comment]
Paste has expired. Closing for non-reproducibility (I didn't work on the mod for about 4 years!)
