### ISSUE TITLE
Crash while editing a structure

### ISSUE THREAD

**Issue by Voidi** [Ivorforce/RecurrentComplex#44]
Reproducable with
/#edit MonolythUnholy -> Generation -> Natural -> Dimensions -> Scrolling with the Mousewheel
https://gist.github.com/Voidi/705b07299784225b98ce

MinecraftForge 1.7.10-Forge10.13.4.1614

**Comment by Ivorforce** [comment]
Fixed in f9104382fed1a7238fc5c170e2363fd097561d93.
