### ISSUE TITLE
Weird Insta-Crash Depending on Gen Size

### ISSUE THREAD

**Issue by Merancapeman** [Ivorforce/RecurrentComplex#45]
I encounter this weird issue. I say weird because while it seems like it's a size thing, I've noticed it's definitely interchangeable. I've shrunk the size, checked all the blocks to make sure something wasn't causing an issue... I'll be attempting to make a fairly small sized structure, get everything in place, place the markers, and export. When I attempt to gen it, though, suddenly everything goes haywire. It _immediately_ shuts down the internal server. I've generated plenty of other structures, and while not as large as this one, I can't see why it's an issue. I'll shift the dimensions so I'm only exporting the top half, works fine. I'll export the bottom half, works fine. But both? Nope. 

http://pastebin.com/maDwgbPr

Regardless, thank you for your excellent mod. This is a nice alternative to WorldEdit.

**Comment by Merancapeman** [comment]
After this post, I shrunk the size a little more, finally worked. Extended it by one block just to see, crashed. The area that was included in the extension had no conflicting blocks or anything weird, and this was, mind you, a part of the structure I was already able to successfully generate prior.

**Comment by Ivorforce** [comment]
Does this still happen in the nightlies? I have this wrapped in a try/catch so theoretically this should just fail the operation (and add some stuff to the log) rather than crash the whole server.
