### ISSUE TITLE
Generating custom structure creates holes

### ISSUE THREAD

**Issue by S0NGER** [Ivorforce/RecurrentComplex#458]
Trying to create a 'ruined' aether portal structure, similar to the ruined nether portals added to Minecraft in 1.16

When generating the structure, whether by generating a world or using /#gen BrokenAetherPortal, a crater generates around with it.

![umu2yipu52n61](https://user-images.githubusercontent.com/78628049/111087804-41bbb880-84e9-11eb-9400-b9ef4d58ab84.png)

I've tried to tweak the generation settings but cannot figure out what's causing this..

Here's the structure file > [BrokenAetherPortal.zip](https://github.com/Ivorforce/RecurrentComplex/files/6138885/BrokenAetherPortal.zip)

**Comment by Ivorforce** [comment]
That sounds like you exported the structure with air blocks. I recommend looking up on the wiki on [generating natural structures](https://minecraft-recurrent-complex.fandom.com/wiki/Guide:_Making_a_Natural_Structure) - specifically with natural floor and negative space blocks in mind.
