### ISSUE TITLE
How to place structures only on certain blocks? To avoid placing on water (ground structures are in seas/oceans)

### ISSUE THREAD

**Issue by iBars** [Ivorforce/RecurrentComplex#459]
Hello, our generator hasn't $WATER biome types, but has seas and oceans depending on neighbour biomes. So structures are generating in non-water biomes, but in water. How to check for solid ground under structure? (Water isn't solid block and I want to avoid it any way). Thank you very much!

**Comment by Ivorforce** [comment]
My primary strategy for this is just integrating some ground into the structure - so it won't care if there's water below it or not on generation. That works for most cases.

To avoid generating an island somewhere, you could use an Ensure transformer to check for water. I think there are some examples in the base mod, but I cannot exactly remember which. Sorry!
