### ISSUE TITLE
Mazes sometimes spawn with the exits not connected to eachother

### ISSUE THREAD

**Issue by filloax** [Ivorforce/RecurrentComplex#46]
Not really any error log to report, as this is more unintended behaviour, but mazes (in #323, don't know about other builds) with a set entrance and exit (in my case, 2 exits at [2,0,0] and [2,0,4] in a [4,0,4]-sized maze) sometimes spawn with the two of them not connected to eachother, thus making the maze impossible.

**Comment by Ivorforce** [comment]
This is now achievable with connection maze rules.
