### ISSUE TITLE
[Feature Request] Generating ruins, with random block spawn percentages

### ISSUE THREAD

**Issue by 0xebjc** [Ivorforce/RecurrentComplex#462]
The idea came from this mod ruins, originally by AtomicStryker.  Where specific blocks can have a specific weight for generation and individual blocks can have different weights so that when a structure is generated, the structure (a ruin for this example) generates differently each time.   I know this is already a mod as previously indicated, but I've identified that the Ruins mod creates some significant ConcurrentModificationException errors.  So I'm looking to replace all my structure generating mods and copy the structures into and have recurrent complex do all the mod generating.  Just an idea, and thanks for an awesome mod!

https://www.curseforge.com/minecraft/mc-mods/ruins-structure-spawning-system#comments
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/tree/1.14.3/Ruins

[Version Request]
Minecraft: 1.12.2
Forge: 14.23.5.2847

**Comment by 0xebjc** [comment]
One idea I had was specify the generation by block type, say stone blocks generate 90% of the time, wood planks generate 80%, cauldron, brewing stations, and chests generates 60% of the time.

**Comment by QuImUfu** [comment]
Something comparable is already in the mod. See:  
https://minecraft-recurrent-complex.fandom.com/wiki/Guide:_Transformers

**Comment by Ivorforce** [comment]
Yes, the "ruins" transformer does some work to "ruinify" structures. You can also use "replace" transformers to go a bit further if you're willing to put in the effort. Does that cover it?

**Comment by 0xebjc** [comment]
Great, Thanks for the advice and recommendation, I'll look into the ruins transformer.

**Comment by 0xebjc** [comment]
Ruins, really helps for what I was looking for, thank you. I also posted two questions about the transformers on your Wiki

https://minecraft-recurrent-complex.fandom.com/wiki/Guide:_Transformers
