### ISSUE TITLE
Failed to find preset console spam

### ISSUE THREAD

**Issue by Jordan231111** [Ivorforce/RecurrentComplex#466]
Server thread/WARN [reccomplex]: Failed to find preset (transformer preset): DesertAdjustment
22.04 10:05:23 [Server] Server thread/WARN [reccomplex]: Failed to find preset (transformer preset): DesertAdjustment
22.04 10:05:23 [Server] Server thread/WARN [reccomplex]: Failed to find preset (transformer preset): DesertAdjustment
22.04 10:05:23 [Server] Server thread/WARN [reccomplex]: Failed to find preset (transformer preset): DesertAdjustment
22.04 10:05:23 [Server] Server thread/WARN [reccomplex]: Failed to find preset (transformer preset): DesertAdjustment
22.04 10:05:23 [Server] Server thread/WARN [reccomplex]: Failed to find preset (transformer preset): DesertAdjustment
22.04 10:05:26 [Server] Server thread/WARN [reccomplex]: Failed to find preset (transformer preset): DesertAdjustment
22.04 10:05:26 [Server] Server thread/WARN [reccomplex]: Failed to find preset (transformer preset): DesertAdjustment

**Comment by Ivorforce** [comment]
That means you have some structure that is missing a preset. The preset should be distributed with the structure - otherwise there's a chance the structure won't generate correctly.
