### ISSUE TITLE
Structures are not generated correctly:  "causing cascading worldgen lag"

### ISSUE THREAD

**Issue by Doming3000** [Ivorforce/RecurrentComplex#467]
The structures generated by the mod are "cut" between chunks, (This on a server) and the console indicates a lot of errors that cannot be solved, I attach screenshots and the last log I have from the server, I appreciate an answer and a solution (I don't speak English well, I think it shows)

[latest.log](https://github.com/Ivorforce/RecurrentComplex/files/6533335/latest.log)
https://cdn.discordapp.comhttps://cdn.discordapp.com/attachments/811079033835356232/846403664364175400/unknown.png/attachments/811079033835356232/846403519623069716/2021-05-24_12.04.29.png

**Comment by Mandlemankiller** [comment]
I am also having this error on my LAN world, i solved that by using older version of Recurrent Complex (RecurrentComplex-1.4.8.2 ==> RecurrentComplex-1.4.8.1)
