### ISSUE TITLE
[Build #329]Mod-added structures spawn with the negative-space blocks instead of using them

### ISSUE THREAD

**Issue by filloax** [Ivorforce/RecurrentComplex#47]
So, to make it short, structures spawn with the negative space/natural ground blocks like the structure was imported, instead of adapting them to the terrain.

To recreate this, do /#gen DinosaurSkeleton

For some reason it only seems to happen with mod-added structures or structures made in the last non-nightly build.

**Comment by Ivorforce** [comment]
Fixed in 69b5d861d2c60d658470a6c45026f6b50c10aba8.
