### ISSUE TITLE
No way to select modded biomes with Expression

### ISSUE THREAD

**Issue by roccscout** [Ivorforce/RecurrentComplex#470]
1.12.2. Able to use expression to select "name=plains", but not "name=fen". Can't find any literature on it, and it seems others have similar issues.

Really surprised this mod wouldn't have the ability to select ONLY individual biomes, and not just dictionary ones.

**Comment by Ivorforce** [comment]
I think you're looking for `id=fen`

**Comment by roccscout** [comment]
Tested, and it doesn't work. id=plains does, but fen does not. Nor Redwood Forest, or Sugi Forest. I don't think there's a way to select modded biomes by ID or Name.

**Comment by Ivorforce** [comment]
Are you sure "fen" is an ID? If you want to match biomes with spaces, eg.g. Redwood Forest, you need parentheses such as "id=Redwood Forest".

**Comment by roccscout** [comment]
`id=fen` does not work, however, `name=Fen` _does_ work. Using name= has worked beautifully, thanks for your help. This has to be the greatest structures mod to ever exist!

**Comment by Ivorforce** [comment]
Thanks, glad to get this sorted out :)

**Comment by roccscout** [comment]
For anyone who searches and finds this: 

The Syntax is `id=modid:biomeid`. 

Example: `"id=minecraft:savanna"`, or "biomesoplenty:redwood_forest".

This will let you select specific biomes, without crashing mutliplayer. 
If you use `name=Biome`, it will "work" in singleplayer generation, but will crash your server upon startup. Example: "name=Redwood Forest" works in singleplayer, but causes crashes on server startup.
