### ISSUE TITLE
I fail to find a specific structure

### ISSUE THREAD

**Issue by SirEdgen** [Ivorforce/RecurrentComplex#477]
Hello everyone. I have a problem - in one of my deleted worlds I've found a structure that I'm sure is from this mod (I also had roguelike dungeons and mysticalworld but I doubt they would add one like that). It was a gigantic tree, surrounded by its roots, hollow inside and divided into several floors. If I remember correctly, it had an entrance with redstone mechanism (pistons, failed to figure out how to activate them at that time). Between its branches there were additional corridors. Can anyone help me with its name? I've tried searching with #structures commands by blocks and possible name, but failed to find anything

**Comment by Ivorforce** [comment]
There are several giant trees in this mod, but unless I missed something, none of them are hollow or have redstone.

Tip: You can easily identify any ReC structure by stepping inside it and running `/#whatisthis` :)
