### ISSUE TITLE
1.16.5?

### ISSUE THREAD

**Issue by Colonizor48** [Ivorforce/RecurrentComplex#478]
This mod would be perfect for 1.16.5. Any plans to update?

**Comment by MagmaBro123** [comment]
Mod's been dead for 2 years. Doubt it.

**Comment by RaafatTurki** [comment]
I hope it gets more attention, it has unparalleled features, the inventory generation system alone blows everything else I've tried out of the water.

**Comment by MagmaBro123** [comment]
> I hope it gets more attention, it has unparalleled features, the inventory generation system alone blows everything else I've tried out of the water.

Again, its been dead for 2 years.

**Comment by Ivorforce** [comment]
No plans to update. Someone might adopt it yet though.
