### ISSUE TITLE
Server problems (forge 1.16.5)

### ISSUE THREAD

**Issue by inedhelp** [Ivorforce/RecurrentComplex#479]
Hi after 13 tries I resigned to ask help online.

I'm currently trying to make a modded server on forge 1.16.5 but here is the problem: even if the mods are there and I can take their items in creative there is no naturally generated structure and the items normally craftable aren't. Another problem is that I can't open the curios sloth but the button is there when I press E. normally when I create a forge server normally there already is a empty mod folder but now I need to create it.

here is the mod list
- Artifacts
- Curios
- Expandability
- Backpacked
- Comforts
- Ferritecore
- GottschCore
- Structure compass ( the mod dosen't work when I try and send a message to Shift + right click which is what I am doing )
- Treasure 2 ( I tried locating most of the structure with /locate but they don't seem to exist for the server )
- Xptomes 

I am running the server on I7 8 cores and on 16 gb of rams

here is a screenshot of the server startup and a screenshot of the server files

![server startup](https://user-images.githubusercontent.com/97255433/148446391-2004a427-269b-4e3a-a601-018d8070e277.png)
![Screenshot 2022-01-06 152027](https://user-images.githubusercontent.com/97255433/148446418-b0eaacbc-1a01-481d-8231-5c1c97335ce3.png)

I tried loading new chunks, creating the mod files before the server creation but nothing seems to make it work please help me I have 2 friends dying to play

**Comment by JustFoxx** [comment]
This mod is currently dead, its not updated to 1.16.5

**Comment by Ivorforce** [comment]
Yes, there is no plan to update to 1.16.
