### ISSUE TITLE
There are too few houses generated by the village.

### ISSUE THREAD

**Issue by Ironnoob73** [Ivorforce/RecurrentComplex#489]
I wanted Rec's own structure to completely replace the village houses, but most of the time only a few houses would be generated, as opposed to a large number of intricate roads.

**Comment by Ivorforce** [comment]
Unfortunately, that's how those villages are programmed. I tried integrating into their systems as well as possible, but cranking up spawn rates unfortunately affects villages in this way. I don't think it is possible to do it better, at least with just ReC.
