### ISSUE TITLE
The grid type static spawn doesn't spawn in a grid.

### ISSUE THREAD

**Issue by Ivorforce** [Ivorforce/RecurrentComplex#497]
![Screenshot_20220514-014930_Telegram](https://github.com/Ivorforce/RecurrentComplex/assets/2308167/5aae18fb-7fed-465d-b968-9a379d439990)

Reported by Whipe.

**Comment by HEHABUZTb** [comment]
It spawns in grid, but endlessly. Like 1 time in 10 seconds another structures in grid spawning 1 on top of another

**Comment by Ivorforce** [comment]
See #508
