### ISSUE TITLE
Weird crash on server (Part 2)

### ISSUE THREAD

**Issue by xJon** [Ivorforce/RecurrentComplex#5]
well..this crash is looking diffrent..at least.
http://pastebin.com/fSjFjfd9

**Comment by Ivorforce** [comment]
I still don't see what the latest log has to do with RecurrentComplex. When exactly does this even occur? On launch?

**Comment by xJon** [comment]
Really happy to see you comment here, thank you for the support.
Some time passed so let me just try again everything.

**Comment by xJon** [comment]
Okay, so I tried using the 0.9.3.n13 version on the server and it did generate a crash report, unfortunately.
http://pastebin.com/Wqxuq98H

**Comment by Ivorforce** [comment]
Alright, I had a closer look, and apparently it's a Windows 7 JDK bug -- https://bugs.openjdk.java.net/browse/JDK-7108548?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel
I'm afraid there is nothing I can do until *they* fix it.

As a workaround, I recommend putting your MC jar in a directory containing no spaces:     
file:/C:/Users/Admin/Downloads/The-1.7.10-Pack-Server-Public-v0.7.0/mods/RecurrentComplex-0.9.3.n13.jar

**Comment by xJon** [comment]
Gotcha. Awesome you figured it out, also thank you for the workaround, I'll use it!
