### ISSUE TITLE
[r350]"Did not find fitting component for maze!" When there is one fitting the description

### ISSUE THREAD

**Issue by filloax** [Ivorforce/RecurrentComplex#50]
I'd try to link the log, but it would refer only to 1 specific random case which I would need to link the hole save for, and also all times I've tried to recreate this either it randomly got only the parts which actually worked or it froze

Anyways, I get errors in the log like this

`[23:41:33] [Server thread/WARN]: Did not find fitting component for maze!
[23:41:33] [Server thread/WARN]: Suggested: X with exits [MazeRoomConnection{left=[8, 0, -1], right=[8, 0, 0]}=Wall, MazeRoomConnection{left=[8, 0, 0], right=[9, 0, 0]}=Wall, MazeRoomConnection{left=[8, 0, 0], right=[8, 0, 1]}=Path, MazeRoomConnection{left=[7, 0, 0], right=[8, 0, 0]}=Path, MazeRoomConnection{left=[8, -1, 0], right=[8, 0, 0]}=Wall, MazeRoomConnection{left=[8, 0, 0], right=[8, 1, 0]}=Wall]`

and no component is spawned there; but, in that case, I had a turn (2 exits on different sides,mirror and rotation on; that's what the log meant, right?) that had been used in other parts of the maze, but not there.

[Structures](https://drive.google.com/folderview?id=0B3oMCEcSQqBjNGJMNllVcUVMMHM&usp=sharing) to test (VMazeTest is the one to spawn the maze)

The maze itself is 0-8x,0-1y,0-8z,with 3 exits: 0-0-0(north),4-0-8(south),8-1-0(up), the walls are deafult, the path connectors Path, the vertical path connectors PathY

Also, it seemed to try to generate dead ends at exits from the maze when the maze is set to connect all exits, but I may be reading the log wrong for this

Sometimes the maze doesn't spawn until I exit and reenter the world, and sometimes the game freezes "server"-side (in singleplayer), as in, I can move around but nothing is saved and exiting the world will freeze the game

**Comment by filloax** [comment]
Apparently, it seems to happen with "Connect all" but not "Connect 2"

**Comment by Ivorforce** [comment]
The maze rules can cause this to happen. In the case of the connect rules, there's still some determination inaccuracy that I will fix rather soon - which would specifically cause this to happen more often.
