### ISSUE TITLE
[Feature Request] Chunk Align

### ISSUE THREAD

**Issue by jagprog7** [Ivorforce/RecurrentComplex#504]
I have a structure which includes a 2x2 flying machine. Flying machines should not straddle a chunk border; when a chunk gets unloaded and loaded it can break it.

I want recurrent complex to cancel generation if the gen x or y causes this to be true:

`(x + provided_offset) % 16 == 0`

Is there currently a way of doing this with the natural gen type? I know that static + pattern can do this but it's not really what I'm looking for.

Thanks.

**Comment by Ivorforce** [comment]
That's quite an unusual request. I suppose it currently isn't possible. The best way to do this would be to allow math on positions in the positioned block expressions, but I think this would explode the scope of a niche feature. Maths are currently not supported in boolean algebra (expressions).

If you're capable of coding, it would be possible to create a sub-mod to recurrent complex that implements a transformer that checks for this, similar to `TransformerEnsureBlocks`. You could add this transformer to your structure by registering it in the transformer registry, like the others, and either adding GUI or adding it by directly editing the JSON.

I'm struggling to find a formulation for this kind of transformer that would be useful for more than this exact use-case though. Hence I'm suggesting you code it yourself.

If you have any other suggestions for how this would be fixable, please let me know. If you find a way that would be easy to implement and useful for more use-cases than this exact one, I'm open to adding it to the mod.

**Comment by jagprog7** [comment]
I ended up using a workaround: a hopper with an item in it can point to an unloaded chunk to keep adjacent chunks loaded. In my used case, this requires 4 hoppers to guarantee coupling between the 2x2 vertical columns.

Thanks for your response. I think this case is too niche for support.
