### ISSUE TITLE
[Bug] End dim generation not working

### ISSUE THREAD

**Issue by jagprog7** [Ivorforce/RecurrentComplex#505]
Minecraft: 1.12.2  
Recurrent complex: 1.4.8.5  
IvToolkit: 1.3.3  
Forge: 14.23.5.2860  
No other mods.

I can't get anything to generate in the end.

For example, if I were to edit the pre-existing AbandonedWoodTower with the following:

 - Under natural generation
   - Category: frequent
   - Biomes:
     - Remove all and add a single "Any Biome: 1.0"
   - Dimensions:
     - Remove all and add a single "Any Dimension: 1.0"

I have ensured that the structure is active. I've also tried various changes to the above config but can't get anything to work.

Thanks for reading this.

**Comment by Shahelion** [comment]
There seems to be something about the End that refuses to generate structures. I spent quite a while trying to get something to appear there, but I think it just isn't possible, sadly.

**Comment by Ivorforce** [comment]
Please check out the wiki entry for this matter: https://github.com/NoMoreUsernames999/Recurrent-Complex-Wiki/wiki/End-Compatibility

**Comment by Shahelion** [comment]
What effect would this have on other mods that add End worldgen? For example, Hardcore Ender Expansion and Chromaticraft.

**Comment by Ivorforce** [comment]
It depends on how they're implemented. Some of them should be unaffected, but you'll have to try it out.

**Comment by Shahelion** [comment]
It seems that JED isn't available for 1.7.10, so that isn't an option for me.

**Comment by jagprog7** [comment]
@Ivorforce

User error; the fault is mine. I had unfortunately forgotten to add the End to the `universalBiomeMatcher` (which now is "0|1"). However, I am confused by:

> Please check out the wiki entry for this matter: https://github.com/NoMoreUsernames999/Recurrent-Complex-Wiki/wiki/End-Compatibility

On my setup (as listed above), this is not necessary. It works without Just Enough Dimensions. I'm confused by why that page exists, and why it is located under a different account. But thank you anyways.

**Comment by NoMoreUsernames999** [comment]
> @Ivorforce
> 
> User error; the fault is mine. I had unfortunately forgotten to add the End to the `universalBiomeMatcher` (which now is "0|1"). However, I am confused by:
> 
> > Please check out the wiki entry for this matter: https://github.com/NoMoreUsernames999/Recurrent-Complex-Wiki/wiki/End-Compatibility
> 
> On my setup (as listed above), this is not necessary. It works without Just Enough Dimensions. I'm confused by why that page exists, and why it is located under a different account. But thank you anyways.

I'm the wiki maintainer. It's listed under a different account as the new wiki overhaul was started as an independent project that was later backed by Ivorius as the official wiki. 
That method was to fix a long standing issue with users being unable to get it working even with universalBiomeMatcher. If you can confirm it works with the latest version of RC and no other mods installed, I can update the wiki page.
