### ISSUE TITLE
r350 Non-cube maze room setups not working

### ISSUE THREAD

**Issue by filloax** [Ivorforce/RecurrentComplex#52]
I'm trying to make a maze generate in a reverse-pyramid, using multiple additive rooms like this:
[3,0,3]->[3,0,3]
[2,1,2]->[4,1,4]
[1,2,1]->[5,2,5]
[0,3,0]->[6,3,6]
etc
I thought that'd be possible, as the wiki has a similar example regarding the room settings (a pyramid), but when I /#copy it for testing it sets the low y of the highest layer to 0, in this example turning the thing to
[3,0,3]->[3,0,3]
[2,1,2]->[4,1,4]
[1,2,1]->[5,2,5]
[0,0,0]->[6,3,6]
thus making it all a cube.

Sorry for the issue spam, I've been experimenting with mazes lately and I guess I'm being unlucky with bugs.

**Comment by Ivorforce** [comment]
Well, I am currently working on a lot of low-level generation stuff, so things are very unstable in the nightlies. I appreciate the issues though, sometimes I'm missing bugs and finding them early on streamlines the process :)

**Comment by Ivorforce** [comment]
Cannot reproduce. I've tried taking the StoneMaze, editing the maze generation script for exactly the rooms you pasted here, used /#copy and then /#paste. Are you sure you didn't just accidentally set it back to 0?

**Comment by filloax** [comment]
I'm sure, I'll try again when I'm not in mobile and upload the structure
file
Il 25/Mar/2016 00:44, "Ivorius" <notifications@github.com> ha scritto:

**Comment by filloax** [comment]
Yep, still happening: 
[Mazetest.zip](https://github.com/Ivorforce/RecurrentComplex/files/190899/Mazetest.zip)
The main structure is MazeTest
