### ISSUE TITLE
Incompatibility with BiomeTweaker

### ISSUE THREAD

**Issue by Sunconure11** [Ivorforce/RecurrentComplex#55]
https://github.com/superckl/BiomeTweaker/issues/78

**Comment by Ivorforce** [comment]
This is a Recurrent Complex issue and has been fixed in the latest nightlies already.

**Comment by Ivorforce** [comment]
No wait, I think I judged too quickly. It does look like a BiomeTweaker problem. I'll just throw a try / catch around it for now and try to avoid the problem.

**Comment by superckl** [comment]
It's not from BiomeTweaker. It's an isssue in Forge. I actually submitted the PR to fix it in 1.8. Lex rejected the PR for 1.7.10. I have code in BT for 1.7.10 to get around it when I add biome types to the dictionary.

MinecraftForge/MinecraftForge#1935
