### ISSUE TITLE
r362 Vanilla village structures spawn inside of this mod's

### ISSUE THREAD

**Issue by filloax** [Ivorforce/RecurrentComplex#56]
Examples:
![2016-04-03_10 58 16](https://cloud.githubusercontent.com/assets/3884952/14231640/47507ca2-f98b-11e5-871d-b10d68895e64.png)

![2016-04-03_10 58 44](https://cloud.githubusercontent.com/assets/3884952/14231642/4d48ac2e-f98b-11e5-9068-165ac1b6f340.png)

Yes, the house is from Immersive Engineering, but exported as a Rec Complex structure to edit it.

**Comment by Ivorforce** [comment]
I think this has been fixed with the village fixes from 1.0. Please reopen if this happens again.
