### ISSUE TITLE
Odd bug with CustomNPCs and boss bars

### ISSUE THREAD

**Issue by filloax** [Ivorforce/RecurrentComplex#58]
For some reason, if you include an NPC from the customnpcs mod with his boss bar active in a structure, the boss bar isn't visible for npcs spawned in structures, even if it did work for the exact same one spawned normally. I don't know on which side this is, but Noppes isn't developing that mod for 1.7 anymore, so it would be pointless to report the bug to him.

**Comment by Ivorforce** [comment]
I looked at some code and can't see any reason why this might be happening. You could try comparing the NBTs of the NPCs in terms the showBossBar byte (that would mean a save/load issue).

**Comment by filloax** [comment]
The bar doesn't work even if I enable it afterwards with scripts, but it
seems but and miss, as with some it works. I cannot understand what's the
common thing with the ones that don't, but it seems that it only happens
when they're spawned inside of a structure inside another one, not when the
structure directly containing them is spawned. I'll experiment a bit to see
when it happens and when it doesn't.

**Comment by Ivorforce** [comment]
One thing that's to be considered is that the boss bar will only show up when the entity can 'see' the player - so maybe if you get closer it will show up?

**Comment by filloax** [comment]
It seems to be something related to this, I'll test.
