### ISSUE TITLE
Child structures aren't rotated correctly

### ISSUE THREAD

**Issue by filloax** [Ivorforce/RecurrentComplex#59]
I made a wall-skull 1 block structure to use as arandomly placed decoration, but while it does rotate it, it randomly rotates it towards the right direction on in the opposite one.
Structures to test (WMzI is the parent): 
[active.zip](https://github.com/Ivorforce/RecurrentComplex/files/222339/active.zip)
![2016-04-16_20 17 59](https://cloud.githubusercontent.com/assets/3884952/14582866/ee89f8ce-0410-11e6-86e2-0a39b15bac30.png)

**Comment by Ivorforce** [comment]
Are you sure it's not just skulls in general that don't work?

**Comment by filloax** [comment]
That also happens with Witchery moss (didn't include that as it requires another mod) and the skull gets rotated, just not in the right direction sometimes.

**Comment by Ivorforce** [comment]
Some blocks don't rotate correctly - when I asked Lex about it he said it was because it wasn't 'standardized'. Try with just the skulls in a small normal structure - if that works but it doesn't in structure blocks I'll investigate :)

**Comment by filloax** [comment]
Still happens, I even tried with Mirrored On/Off, and by placing the small normal structure in a list and spawning the structure generator in another structure.

**Comment by filloax** [comment]
To be more clear, in the small normal structure they rotate correctly, the "still happens" was related to Mirrored on/off.

**Comment by filloax** [comment]
![2016-04-18_18 13 19](https://cloud.githubusercontent.com/assets/3884952/14611212/5cee5324-0591-11e6-966a-588bbbacb243.png)

This also seems to happen with some stairs, and those aren't in a separate substructure, but in the same structure as the maze component itself.

**Comment by filloax** [comment]
Ok, the problem, it seems, stemmed from mirrorability, as turning Mirrorable to off for all maze components and child structures eemed to fix this. The stairs still don't work, but as they're from amod I didn't really expect them to.
