### ISSUE TITLE
remove the ID

### ISSUE THREAD

**Issue by SvEgiiVEteR** [Ivorforce/RecurrentComplex#61]
my friend was upset. you remove the ID in the future.
example.
#replace 12 0
You can leave them in mod?
easier to write a short number, than a long name.

sorry confused.
The game is written a message:
that ID will be deleted. write the names.

close

**Comment by Ivorforce** [comment]
Removing the number IDs is not my decision (albeit a good one). It's ultimately up to Mojang.
I recommend using tab to autocomplete blocks, then you don't have to type out the full name.
