### ISSUE TITLE
[1.7.10] No default structures spawning in Overworld

### ISSUE THREAD

**Issue by ArmandVestibule** [Ivorforce/RecurrentComplex#63]
Good day!

I am experiencing a peculiar issue. I set up a brand new SMP box with a handful of mods and cannot get the default RC structures to spawn. When I jump over to SSP, it works fine. Structures spawn naturally as anticipated.

I am unable to locate any logs or anything to help pinpoint where the issue could lie -- any insight as to where I might go to troubleshoot this further?

Thanks!

**Comment by Ivorforce** [comment]
Try using the ReC commands (/#gen for example). If that works, then it might be that the structures don't want to spawn in the biomes being generated. You can check that part with /#biomedictionary.

**Comment by MasterAvarice** [comment]
I am having the same issue, except none of the basic structures seem to be in the dictionary.  Only ones that I created are showing up in the list.  The ones I created spawn fine, its just the standard structures seem to not spawn or in the list of spawnable structures.

**Comment by ArmandVestibule** [comment]
I have since migrated to 1.10.2, where the issue continues to persist on a fresh SMP server.  The /#gen commands do prompt me for syntax but /#list comes up empty. Is this an improper installation on my part?

/#list gives me a full structure list in SSP.

**Comment by Ivorforce** [comment]
I'm guessing you have an active structureLoadMatcher or something preventing structures from being loaded? Try deleting your config file and reloading the game. At the very least, something should be logged, if ReC is active.

**Comment by ArmandVestibule** [comment]
I have moved away from this issue and settled on another mod instead so I have not been able to fully pursue this troubleshooting. Thanks for following up.
