### ISSUE TITLE
PlaceholderStrings and some buttons cannot be translated and German Translation

### ISSUE THREAD

**Issue by QuImUfu** [Ivorforce/RecurrentComplex#65]
I'm currently translating all the mods in my private modpack to German (just for fun^^) and i noticed that you can not translate the PlaceholderStrings and some buttons (e.g. Save, Cancel button) in you mod.

[Here] (https://dl.dropbox.com/s/fqszbu3zftim8xs/de_DE_RC.lang) is a link if you want to include the translation (everything that is translatable is translated, i think).
I added the "structures.gui.random.value(.tooltip)" string (same as "structures.gui.random.weight(.tooltip)") because it gets used in the 1.7.10 version i am using instead of the .weight string.

**Comment by Ivorforce** [comment]
I added the translation (with some minor adjustments) in the newest commit. I also changed back the .value to .weight, thanks for the report on that. :)

Regarding the untranslateable components, I'll work on that later. I'll leave the issue here until I fix that one.
