### ISSUE TITLE
Does not appear to be structure in the worlds Galacticraft

### ISSUE THREAD

**Issue by Shurik1236** [Ivorforce/RecurrentComplex#66]
Структуры просто не появляются./(Google)Structure does not simply appear.
Вот параметры:/(Google)Here are the parameters:
<details> 
  <summary>

Screenshots</summary>

<img src="http://s019.radikal.ru/i640/1605/bf/813d0b4a1e1e.jpg" >
<img src="http://s012.radikal.ru/i320/1605/73/a799c34e05f0.jpg" >
</details>

**Comment by Ivorforce** [comment]
Try using /#biomedict and /#dimensiondict to confirm that the dimensions and biomes actually match up.

If that doesn't work, it's an event issue caused by the mod itself. Will need to add an Issue / PR to Galacticraft to fix it.

**Comment by Ivorforce** [comment]
Closing stale issue.
