### ISSUE TITLE
1.8.9 crash when  attempting to generate a spawn structure

### ISSUE THREAD

**Issue by Divineaspect** [Ivorforce/RecurrentComplex#70]
http://pastebin.com/KYLLqR6u

**Comment by belathus** [comment]
I'm not sure if these are related, but parts of the crash log look similar: http://pastebin.com/Ku3SEfp8

So, when using /#gen or /#import on certain structures, I get an error that says, "An unknown error occurred while attempting to perform this command." It doesn't crash, but I suspect when genning it as part of worldgen, it crashes the server.

In particular, one structure that gave me that error had a chisels and bits chair in it. Destroying the chair resolved the error.

I'm trying to gen every structure we made now and check and see if removing all those that have errors will stop the crash from happening.

**Comment by Ivorforce** [comment]
Your logs should say something like "An entity X has thrown an exception during loading" - that the entity doesn't load mean either a bug in the entity's mod's code or a missing mod. 
Anyway, I wrapped the loading so it doesn't crash anymore, just skip the entity and log an error. I just forgot.
