### ISSUE TITLE
[1.7.10] FTB Infinity with added mods including Recurrent Complex & Reika's Mods Crashes every ~20 minutes

### ISSUE THREAD

**Issue by Yamanagi** [Ivorforce/RecurrentComplex#71]
Link to crash
http://pastebin.com/bbDrUJc4
The game freezes and then crashes every 20 minutes or so, or whenever I reload chunks. Similar crash reports every time. Happens with every world, and with some worlds it happens right after the world gets created. Temporary solution i've been using is to disable Recurrent Complex, however, I really like the structures added. No clue whats going on with Reika's mods either, posting it here because RC is the main issue. 

Thank you in advance for any solutions or responses you may have for me.

**Comment by Ivorforce** [comment]
Your version of IvToolkit is out of date.

**Comment by Yamanagi** [comment]
The newest version for 1.7.10 on curseforge is 1.2.1.jar which is the same one I'm using. If there is a newer version for 1.7.10 would you kindly link me to it, or upload it onto curseforge?

**Comment by Ivorforce** [comment]
That's... weird. Yes you are using the latest versions linked, apparently. Try redownloading them from curse though - perhaps you're using outdated nightly builds. There's definitely use of a method that hasn't been implemented yet and I _really_ imagine I forgot to make a final 1.7 build for IvToolkit.

**Comment by Yamanagi** [comment]
Latest 1.7.10 version on curse is 1.2.1.jar
I have 1.2.1n109.jar 
Drone.io has latest build 1.2.6n148.jar
If I try to use that, it crashes as soon as it starts,  and I can't download any other build
