### ISSUE TITLE
Java 8 Requirement Bug

### ISSUE THREAD

**Issue by hero887** [Ivorforce/RecurrentComplex#74]
Hello,

I am running MC 1.8 on Forge build .1563 and I keep getting the error message saying I need to update my Java to 1.8 but it is. (see screenshots)

Error Message from IvToolKit:
https://gyazo.com/44ce1c4daa73bcd08bf5ad6ea35fd7dc

Proof of Java 8 Installed on my computer:
https://gyazo.com/a1044dbb9dedd4059d1cfa18af87d529

Any solutions? I don't know how to bypass this issue when clearly I am running Java 8 already. Note that your mod is not the only mod in this modpack. There are about 55 other mods installed.

And final question, must both these mods be installed on a server AND client to run?

Thanks!

**Comment by Ivorforce** [comment]
To use Java 1.8 successfully on OS X, please refer to [this tutorial](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/2167922-jre-list-tool-switching-to-java-7-on-os-x).

Recurrent Complex can be run on just the server, without needing to be installed on clients, in [lightweight mode](http://minecraft-recurrent-complex.wikia.com/wiki/Using_Recurrent_Complex_as_a_Utility).
