### ISSUE TITLE
[1.10.2] Server crash on load

### ISSUE THREAD

**Issue by c0rn3j** [Ivorforce/RecurrentComplex#76]
http://pastebin.com/3N3819Hh

**Comment by c0rn3j** [comment]
Client seems to load fine, didn't actually test it by loading a world.

**Comment by Ivorforce** [comment]
I can't really see anything in this crash log. Can you include the full runtime log?

**Comment by c0rn3j** [comment]
Using 1.0 version, bug still occurs.

http://pastebin.com/Y529FJn1
