### ISSUE TITLE
Request: Option to turn off default structures easily

### ISSUE THREAD

**Issue by Saphrym** [Ivorforce/RecurrentComplex#8]
I'd like to turn off the structures that come with the mod. Is there an easy way to do it? Or am I going to have to put the entire list of structures in the config?

**Comment by Ivorforce** [comment]
This is simple - Navigate to the config menu, find 'disabledModGeneration' and add 'reccomplex' to the list.

**Comment by Saphrym** [comment]
*facepalm* Sorry for bugging you with that. No idea why I didn't think of that. Thanks!
