### ISSUE TITLE
[1.0] server crash during startup

### ISSUE THREAD

**Issue by InsaneJ** [Ivorforce/RecurrentComplex#80]
Using RecurrentComplex-1.0 for Minecraft 1.10.2 with Forge 1.10.2-12.18.1.2076 on a server. The following crash occurs during startup.
http://paste2.org/4abLtNWt

Using the same mods as the server, but on a client, works without crashing.

**Comment by Ivorforce** [comment]
This has already been fixed and will be part of the next release.

**Comment by InsaneJ** [comment]
Awesome, thanks!
