### ISSUE TITLE
smallwoodencottage2 has an incorrect y-shift

### ISSUE THREAD

**Issue by Alan19** [Ivorforce/RecurrentComplex#81]
The cottage has stairs leading to the door which means it should not have a y offset or else it will cause the stairs to be buried in the ground.
![2016-09-02_23 05 01](https://cloud.githubusercontent.com/assets/11682762/18222317/e87a8782-7161-11e6-8edb-239b6330da16.png)
I removed the cobblestone in the image for resources in SSP

**Comment by Ivorforce** [comment]
It seems fine to me. It has an offset of -1, which just about corrects for the natural floor it has generating below it.

**Comment by Alan19** [comment]
Shouldn't it be one higher so the stairs would be on the ground which would lead to the cabin that is one  block above the ground? I'll check how it looks like in 1.10 later.

**Comment by Alan19** [comment]
The screenshot was taken on 1.8.9. It might have changed in 1.10.2

**Comment by Ivorforce** [comment]
Works fine for me. Please reopen the issue if the problem persists in 1.10.
