### ISSUE TITLE
[1.10.2] Vanilla Village house spawning on top of RC one

### ISSUE THREAD

**Issue by BBoldt** [Ivorforce/RecurrentComplex#82]
![](http://i.imgur.com/NuLTImQ.png)

**Comment by Sunconure11** [comment]
I can confirm that I've also seen similar shenanigans on earlier versions of MC as well. However, vanilla has some derpy generation with villages by default.

**Comment by Ivorforce** [comment]
I say probably - I didn't see any overlaps anymore. If this didn't fix it, please reopen the issue.
