### ISSUE TITLE
I can't find the GUI option for changing the static and other options. (1.10.2)

### ISSUE THREAD

**Issue by Lightone** [Ivorforce/RecurrentComplex#84]
try click on plus button but nothing happend and same with structure list with that button 

![2016-09-06_23 59 00](https://cloud.githubusercontent.com/assets/2113099/18300557/b7d983a4-748f-11e6-981d-e0df3a33a4eb.png)

**Comment by Ivorforce** [comment]
Already fixed - and available in the latest nightlies. It will be part of the next release.
