### ISSUE TITLE
[1.10.2] Client crash when generating maze

### ISSUE THREAD

**Issue by ruyanve** [Ivorforce/RecurrentComplex#85]
Updated to 1.0.3 and crashed after running a couple of minutes... Used to work fine with RecurrentComplex-1.0.2.jar in combination with RTG
https://gist.github.com/ruyanve/d2720fd0b2c1fcd5f856d954ad8f01a1

**Comment by Ivorforce** [comment]
Is that a custom structure / maze? I can't reproduce the issue with either stone or forest mazes.

**Comment by Ivorforce** [comment]
Nevermind, I just got it. Working on resolving the issue.

**Comment by Ivorforce** [comment]
Fixed in the latest IvToolkit nightly.
