### ISSUE TITLE
[1.10.2] Crash with Maze Gen - latest versions

### ISSUE THREAD

**Issue by b0bst3r** [Ivorforce/RecurrentComplex#86]
http://pastebin.ubuntu.com/23181953/

IvToolkit-1.2.8.5
RecurrentComplex-1.0.3
Forge 2086

**Comment by Ivorforce** [comment]
Try redownloading IvToolkit. I fixed this in IvToolkit-1.2.8.5_a.jar.

**Comment by b0bst3r** [comment]
Yeah I saw that but the mod downloaded as IVtoolkit-1.2.8.5.jar so I thought I had it already.

**Comment by Ivorforce** [comment]
Yeah, the filename stayed the same. I just changed the curse entry + display name - I should probably change the filename too, next time.
