### ISSUE TITLE
[CTD] java.lang.IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by drakray** [Ivorforce/RecurrentComplex#88]
Was moving in Creative in a Superflat Overworld new world, when *BAM*, crashlog:
http://pastebin.com/GJWCtqiu

**Comment by Ivorforce** [comment]
I think you have a faulty loot table somewhere. The code crashes in complete vanilla code anyway.
What I did is make it just log an error rather than crash - I can't do more in this case.
