### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by xJon** [Ivorforce/RecurrentComplex#9]
Hi there [:
I don't think it's a bug but I wanted to ask if there's anything you can do when it comes to this FPS killer:
![image](https://cloud.githubusercontent.com/assets/8945347/6216708/1fdd1050-b615-11e4-8cf2-0d5286783f9d.png)
I saw this on almost every structure-spawning-mod and I have to admit I don't understand why it happens.
Thanks for the support,
Jon

**Comment by Ivorforce** [comment]
What do you mean by 'this' fps killer? What exactly is slowing your game down? 'gameRenderer' tells me little by itself. (You can navigate the categories by pressing 0-9).

**Comment by xJon** [comment]
The dropped items on the floor, from ladders to flowers and grass :)

**Comment by Ivorforce** [comment]
Personally I don't even experience any lag - that is, on my pretty old laptop without much gaming power. Maybe you should just turn down your render quality settings?

**Comment by xJon** [comment]
It is helping, thanks :P
But just out of curiosity what is actually causing the items to be stopped on the floor when structres spawn?

**Comment by Ivorforce** [comment]
It only happens with some - for me, only with the ruins transformer. Bad mods might leave items everywhere if you're unlucky :P
The ruins transformer runs an algorithm that decays the structure. It happens that stones are decayed whereas ladders or torches are not, leaving them to fall to the ground as the wall deteriorates. It's only logical if you think about it.

**Comment by xJon** [comment]
Well that's weird and unfortunate but I guess it's not that critical, 1 of 1,000 tiny bugs in modded Minecraft.
Thank you for the good support and awesome mods :)

**Comment by Ivorforce** [comment]
Oh, tons. I'm implementing as I ago, though, so I wouldn't be able to tell you what will come sooner and what later.
