### ISSUE TITLE
Ticking Block Entity Crash

### ISSUE THREAD

**Issue by cattrfly** [Ivorforce/RecurrentComplex#90]
My RFTools dimension builder stalled for a few seconds at 99% while powering up a new simple dimension, then my game crashed. This mod is listed in the crash report, linked below. This happened just after I'd updated to the newest version, RecurrentComplex-1.1. When I reverted to the previous version I'd been using, RecurrentComplex-0.9.8.3, the dimension builder was able to fully power up a different new dimension with no problems (although the one it had been working on when the game crashed seems to be corrupt). Running MC1.10.2, Forge 2092, and a good amount of other mods, using MultiMC.

http://pastebin.com/EE40DmW3

**Comment by Ivorforce** [comment]
Your version of IvToolkit is outdated.

**Comment by cattrfly** [comment]
Oops, sorry about that. Didn't notice an update for it when I updated Recurrent Complex. >_<
