### ISSUE TITLE
Loot not generating in structures

### ISSUE THREAD

**Issue by JetstormLP** [Ivorforce/RecurrentComplex#93]
I have RC 1.1.1 and IvToolkit 1.2.8.5, with Forge 12.18.1.2094 installed. I changed one option which was to stop the nature (trees, mushrooms, etc.) from spawning since they were causing me to lag heavily due to immense numbers of leaf decay updates. After changing that option suddenly there is no loot spawning in any of the chests. Tested multiple worlds, multiple structures. attached my fml-client-latest log for you.
 
[fml-client-latest.txt](https://github.com/Ivorforce/RecurrentComplex/files/499610/fml-client-latest.txt)

**Comment by Ivorforce** [comment]
Pretty sure the generateNature has no effect on generating loot. Maybe the specific structures just don't generate loot, or you have them overriden not to in some way. What structures are you looking at?

**Comment by Badcholo** [comment]
I did not change anything in the configs, but have just started exploring my new server world and i keep finding empty chests. I had increased the spawn rate of buildings drastically and it's this mod that is not spawning anything in the chests.

**Comment by Ivorforce** [comment]
Can you name one or two specific structures? It might be that I have overseen them, but some should definitely work (e.g. SmallAbandonedMine).

**Comment by knoxhack** [comment]
Im having the same problem, no loot on any chest

http://imgur.com/y8fBj9C
http://imgur.com/M1MNWAM

**Comment by Ivorforce** [comment]
Some structures in the fort ruins did indeed not contain loot - but this was an individual case, not a systematic problem. If you find any more empty chests please do report them and I'll fix the contents.

**Comment by knoxhack** [comment]
All of them aren't generating loot

**Comment by knoxhack** [comment]
Every single chest in any structure are empy

**Comment by Badcholo** [comment]
Sorry, for the late reply. I have went all over my world and there is no loot at all in any chests. I forgot about uploading the server logs, but will as soon as i get home.

**Comment by Ivorforce** [comment]
Right. That's an issue on a different level then.

Can you check if all the inventory generation tags are there, and generating? And do you have some mod installed that overrides chests or something?

**Comment by darkhax** [comment]
This issue, or at least the one knox is having is likely related to that E+ issue you had reported. A new build has been published which should fix this.

**Comment by knoxhack** [comment]
\o/

**Comment by knoxhack** [comment]
I'll test it when i get home

**Comment by Ivorforce** [comment]
Oh right, that makes sense. Closing this issue too then.
