### ISSUE TITLE
[Crash] Exception access violation

### ISSUE THREAD

**Issue by bondgb** [Ivorforce/RecurrentComplex#95]
Hard crash on creating a world with Recurrent Complex. Not 100% of the time.

Log: https://gist.github.com/bondgb/202cc813d00ec8cbdd61ba403350f452
Relevant error at the bottom.

And hs_error_pid3684.log: https://gist.github.com/bondgb/44f45c68bf130f5c6f3a8b86717a6b76

**Comment by Ivorforce** [comment]
That's a Java issue. I recommend updating your JRE, or if it's reproducable somehow submitting it as a Java bug report - there is nothing I can do though.
