### ISSUE TITLE
Planted oak trees won't grow next to each other

### ISSUE THREAD

**Issue by thiakil** [Ivorforce/RecurrentComplex#97]
I updated to 1.1.1 from 1.0.3 last night. MC 1.10.2 Forge 2094

1. plant oak saplings next to each other e.g. 1x3

2. Apply bonemeal to make the middle one grow

3. The bonemealed sapling and some around it will despawn

**Comment by Ivorforce** [comment]
Trees only spawn if there's enough space around. That means for any oak or leaves block the tree has, there has to be air, a replaceable block or leaves in the world. If there's already a tree very close by, it will have logs in it that block the spawn of the next one. You can change that by editing the tree transformer preset.

The sapling despawn was a bug and will be fixed in 1.1.2.

**Comment by thiakil** [comment]
Do I need to edit that to restore vanilla behaviour? If so, how?

For example, top down:
xxx
xxx
xxx

On vanilla I can bonemeal all these (or let grow naturally) and I will have a fat tree of 3x3

**Comment by Ivorforce** [comment]
As far as I can see in the source code, there is no 3x3 vanilla tree, only 2x2. It must be added by a mod.
If you want to disable ReC sapling growth, you can set saplingTriggerChance to 0 in the config. You can also edit each specific tree to remove the sapling generation type to disable them individually, or set generateNature to false to disable all ReC trees overall.

**Comment by thiakil** [comment]
Yeah 3x3 is just an example of how I've been able to grow them before, e.g. In a ender io farming station that creates a mass of trees

**Comment by Ivorforce** [comment]
Since Forge's event implementation is very limited, there's little I can do to support modded content, save supporting each one individually (which is very time consuming). 

I have improving the event itself on my TO-DO list, but for now you have those 3 options to choose from.

**Comment by thiakil** [comment]
I have not once been talking about modded content, apart from yours. Only about **planting** saplings by hand or with machine.

![2016-10-10_21 25 18](https://cloud.githubusercontent.com/assets/1788847/19237570/3fc9a9e6-8f30-11e6-8dfa-1da123cd5033.png)
I am talking about growing trees in adjacent blocks. Either bone meal (used here) or left to naturally grow. This screenshot is vanilla 1.10.2.

As soon as I add this mod, this seems not possible. (default config as mentioned)
