### ISSUE TITLE
Script block not working with spawn generation

### ISSUE THREAD

**Issue by WolfieWaffle** [Ivorforce/RecurrentComplex#98]
I don't know if I am maybe doing something in the generators wrong, because I don't understand them and can't find any documentation, but my script command blocks aren't running when I start a new world. The structure spawns fine, and if I use /#gen it works fine, but when it naturally generates it does not run the commands.

Are they any options that might be causing this?

**Comment by Ivorforce** [comment]
At least I think that was your issue. Please report back if it still doesn't work in the latest nightly :)
